import hashlib,os,json
R='/home/na/projects/evo-sim/sources/raw/critics/'
def h(f):
    return hashlib.sha256(open(R+f,'rb').read()).hexdigest()
E=[
# key, side, author, date, title, url, files, access, branch, targets, notes
('MC-1','critic','Dennis McCarthy','2026-09-11 (orig. paid 2026-01-26)','Why "Probability Zero" is Wrong About Evolution (free repost)','https://dennismccarthy.substack.com/p/why-probability-zero-is-wrong-about-0d1',['mccarthy-why-probability-zero-is-wrong-about-0d1.json'],'full text (Substack API JSON)','G3,B5,A5','Darwillion (1/20,000)^20M; GF=1,600 LTEE transfer','Original 2026-01-26 post is paywalled; this repost is the free full text. Day replied at voxday.net ("Do Try to Keep Up, Dennis").'),
('MC-1p','critic','Dennis McCarthy','2026-01-26','Why "Probability Zero" is Wrong About Evolution (paid original)','https://dennismccarthy.substack.com/p/why-probability-zero-is-wrong-about',['mccarthy-why-probability-zero-is-wrong-about.json'],'preview only (paywall)','G3,A5','as MC-1','Preview = intro paragraph; full body assumed identical to MC-1 but NOT verified.'),
('MC-2','critic','Dennis McCarthy','2026-09-17 (orig. paid 2026-02-03)','Vox Day Responds (free)','https://dennismccarthy.substack.com/p/vox-day-responds',['mccarthy-vox-day-responds.json'],'full text (Substack API JSON)','B1,B2,A3x,B4,F','Day\'s 4Ne time-component reply; 410 Mb figure; 3x harmful:neutral','Contains Day quotes (secondhand). Speciation/fossil/biogeography sections are out of math scope.'),
('MC-2p','critic','Dennis McCarthy','2026-02-03','Response to Vox Day & Evolution-Skeptics (paid original)','https://dennismccarthy.substack.com/p/response-to-vox-day-and-evolution',['mccarthy-response-to-vox-day-and-evolution.json'],'preview only (paywall)','-','-','Title/date/preview only. Likely the original of MC-2 (unverified).'),
('MC-3','critic','Dennis McCarthy','2026-01-07','The Comic That Frustrates All Creationists (free)','https://dennismccarthy.substack.com/p/the-comic-that-frustrates-all-creationists-b51',['mccarthy-the-comic-that-frustrates-all-creationists-b51.json'],'full text','-','-','Reposts a Day rebuttal; no fixation math found by keyword scan (fixat/mutation/math/kimura: 0 hits).'),
('MC-4','critic','Dennis McCarthy','2026-01-12','The Exhilarating Beauty & Explanatory Power of the Theory of Evolution (paid)','https://dennismccarthy.substack.com/p/the-exhilarating-beauty-and-explanatory',['mccarthy-the-exhilarating-beauty-and-explanatory.json'],'preview only (paywall)','-','-','Preview says one rebuttal came from Day.'),
('MC-5','critic','Dennis McCarthy','2026-02-13','Three Mind-Melting Mathematical Facts That People Refuse to Believe (paid)','https://dennismccarthy.substack.com/p/three-mind-melting-mathematical-facts',['mccarthy-three-mind-melting-mathematical-facts.json'],'preview only (paywall)','-','-','Preview refers to the book as "Population Zero" (sic).'),
('MC-6','critic','Dennis McCarthy','2026-02-15','Quick Takes (AI, Impossible Math, Evolution, Subscriber Comments) (paid)','https://dennismccarthy.substack.com/p/fast-thoughts-on-important-events',[],'preview only (paywall); not downloaded','-','-','Preview: "important comments on recent posts from experts in the field". Listed in archive JSON only.'),
('MC-arch','critic','Dennis McCarthy','retrieved 2026-10-07','Substack archive listing + RSS feed (enumeration evidence)','https://dennismccarthy.substack.com/api/v1/archive',['mccarthy-archive.json','mccarthy-archive2.json','mccarthy-feed.xml'],'listing','-','-','73 posts enumerated; MC-1..MC-6 are the posts touching Day/PZ; the 2026-07-24 plagiarism post does not.'),
('PM-1','critic','P.Z. Myers','2026-10-02',"Vox Day's amazing ego, and Bill Dembski don't care",'https://freethoughtblogs.com/pharyngula/2026/10/02/vox-days-amazing-ego-and-bill-dembski-dont-care/',['pz-vox-days-amazing-ego-and-bill-dembski-dont-care.html'],'full text','G1,G2,adhom','MITTENS 3.0 (sequential estimate); Dembski interview','Quotes Dembski interview (secondhand Day). Comments not harvested.'),
('PM-2','critic','P.Z. Myers','2026-10-03','Can we be done with Vox Day now?','https://freethoughtblogs.com/pharyngula/2026/10/03/can-we-be-done-with-vox-day-now/',['pz-can-we-be-done-with-vox-day-now.html'],'full text','G2','points to GG/Hancock video','Short; no math.'),
('PM-3','critic','P.Z. Myers','2026-10-04','Vox Day responds to my criticism of his refutation of evolution','https://freethoughtblogs.com/pharyngula/2026/10/04/vox-day-responds-to-my-criticism-of-his-refutation-of-evolution/',['pz-vox-day-responds-to-my-criticism-of-his-refutation-of-evolution.html'],'full text','adhom,G2','-','Mostly block-quotes of Day plus a short reply.'),
('PM-s','critic','P.Z. Myers','retrieved 2026-10-07','Pharyngula site-search RSS (Vox Day / MITTENS / Probability Zero / Dembski)','https://freethoughtblogs.com/pharyngula/?s=Vox+Day',['pz-feed-search.xml','pz-feed-MITTENS.xml','pz-feed-Probability+Zero.xml','pz-feed-Dembski+Vox.xml','pz-feed-Vox+Day+evolution.xml','pz-search.html'],'listing','-','-','Only the three 2026-10 posts concern MITTENS/PZ. Older hits (2012-2024) are about Day generally; not harvested.'),
('CF-1..6','critic','Camestros Felapton','2026-01-23 to 2026-01-30','Reading Vox Day So You Don\'t Have To 2026 [1]-[6]','https://camestrosfelapton.wordpress.com/category/rabids/reading-vox/probzero/',['ca-part1.html','ca-part2.html','ca-part3.html','ca-part4.html','ca-part5.html','ca-part6.html','ca-feed.xml','ca-reading-vox-probzero.html'],'full text, parts 1-6 (series ends at 6; category feed lists no part 7)','A,A2,A4,B6,G1,G3,adhom','PZ 1st-edition: Fmax equation, GF=1,600, d, Darwillion, Ch.8 examples, IGM','Reviews the first edition (pre-MITTENS 2.x/3.0). Parts 1,6 mostly non-math. Comments not harvested.'),
('GG-1','critic','Gutsick Gibbon (Erika) with Zach Hancock','2026-10-03','No, Vox Day\'s AI-Generated Books Did Not Debunk Evolution (3:30:28)','https://www.youtube.com/watch?v=_Vu0ZVVjwHc',['yt/_Vu0ZVVjwHc.info.json','yt/_Vu0ZVVjwHc.en.vtt','yt/_Vu0ZVVjwHc.transcript.txt'],'auto-captions + 2,000 of ~3,157+ comments (cap)','A,A3x,A5,B1,B5,G1,G2,B6','Duffy presentation of MITTENS 2.x (252,000 gens; 1,400 gens/fix; 205M)','Math segment ~t=01:28:00-02:05:00. Whiteboard not captured by captions. Addresses the Duffy-presented version, not MITTENS 3.0.'),
('GG-2','ally-adjacent','Gutsick Gibbon (host) / Will Duffy (presenter)','2026-09-22','Teaching Famous Creationist Will Duffy Evolutionary Theory (LIVE) Human Evolution #2 (4:57:53)','https://www.youtube.com/live/6jXiwrcC5PQ',['yt/6jXiwrcC5PQ.info.json','yt/6jXiwrcC5PQ.en.vtt','yt/6jXiwrcC5PQ.transcript.txt'],'auto-captions + 2,000 comments (cap)','A,A4,G1','Duffy presentation t=00:19:12-00:43:30; Q&A t=04:04:56-04:14:11','Primary record of Duffy presenting Day\'s argument. Erika\'s live math response is minimal (defers to later guests).'),
('GG-3','critic','Gutsick Gibbon (Erika)','2026-10-01','r/DebateEvolution: Vox Day is Wrong on Evolution According to Every Scientist But Ten*','https://www.reddit.com/r/DebateEvolution/comments/1wv4zeg/',['arctic-tree-1wv4zeg.json','arctic-title-Vox%20Day.json'],'full text + 137-comment tree (via Arctic Shift archive)','epistemic','Day\'s "10 math PhDs" claim','Call for credentialed commenters; no math in post.'),
('JG-1','critic','Jan Ghijselen (@DeDzjang)','2026-09-28','Will Duffy\'s math on Gutsick Gibbon\'s channel. (4:53)','https://www.youtube.com/watch?v=nTVRiEcswI8',['yt/nTVRiEcswI8.info.json','yt/nTVRiEcswI8.en.vtt','yt/nTVRiEcswI8.transcript.txt'],'auto-captions + all 115 comments','G2,A','Duffy-presented 252,000 / 1,400 = 180','Marathon analogy.'),
('RD-1','ally','Rebekah Davis (Examining Origins)','2026-09-23','Can Evolutionists Finally Face the Math? Challenge Issued! (20:02)','https://www.youtube.com/watch?v=jDxFtCOGZ3A',['yt/jDxFtCOGZ3A.info.json','yt/jDxFtCOGZ3A.en.vtt','yt/jDxFtCOGZ3A.transcript.txt'],'auto-captions + all 819 comments','D,G1','Duffy presentation; Wistar','Presenter says she has not read the book. Mansfield thread is in comments.'),
('TH-1','critic-context','Zach B. Hancock (@talkpopgen)','2024-03-06','Waiting-time? No Problem. (42:11)','https://www.youtube.com/watch?v=KLPZxAU9nAM',['yt/KLPZxAU9nAM.info.json','yt/KLPZxAU9nAM.en.vtt','yt/KLPZxAU9nAM.transcript.txt'],'auto-captions only; downloaded, not analysed','H?,E','Pre-dates Day; Behe/Snoke-type waiting-time papers','Context for Hossjer-style waiting-time models. NOT used for Day quotes.'),
('RE-1','critic','Dumb-and-Dumber (Reddit)','2026-09-28','New anti-evolution "paper" today from Vox Day (MITTENS 3.0)','https://www.reddit.com/r/DebateEvolution/comments/1wss2wj/',['arctic-tree-1wss2wj.json','arctic-title-Vox%20Day.json'],'full text + 93-comment tree (Arctic Shift)','A2,A3x,A5,B1,B5,E','MITTENS 3.0 (Zenodo 23003785) secs 4.3,6.4,7,8.2','Reddit blocks direct fetch (403/login wall); Arctic Shift is a third-party archive. First published detailed critique of 3.0. Day-posted paper reported "now gone" in one comment (unverified).'),
('RE-2','critic','Sparky_6_4 (AI-assisted, "Clauwd Meowgorithm")','2026-10-04','KITTENS: rebuttal to Vox Day\'s MITTENS 3.0','https://www.reddit.com/r/DebateEvolution/comments/1wxgsjm/',['arctic-tree-1wxgsjm.json','arctic-title-Vox%20Day.json','arctic-title-MITTENS.json'],'full text (25k chars) + comments','A2,A3x,A5,B1,E','MITTENS 3.0 decomposition 94,000 x 11.7 = 1.1M','Two posts (1wxgamf, 1wxgsjm) with same title. Self-discloses AI use and from-memory citations.'),
('RE-3','critic','jnpha (Reddit)','2026-10-02','"Vox Day" has trained his AI author on himself','https://www.reddit.com/r/DebateEvolution/comments/1wvzng3/',['arctic-tree-1wvzng3.json'],'comments tree only (post text in arctic-title files not read)','adhom','-','Not analysed for math.'),
('RE-4','critic','Dumb-and-Dumber (Reddit)','2026-09-27','IS VOX DAY A WHITE SUPREMACIST?','https://www.reddit.com/r/DebateEvolution/comments/1wrw50e/',['arctic-tree-1wrw50e.json'],'comments tree only','adhom','-','Out of scope (person, not math); recorded for completeness.'),
('PS-1','critic','Nesslig20 (Peaceful Science)','2026-10-05','Response to Will Duffy | PART I - Population Genetics','https://discourse.peacefulscience.org/t/18094',['ps-topic-18094.json'],'full text (OP + 4 replies)','B5,H,A3x','Duffy presentation of MITTENS 2.x','Neutral-theory derivation; k=75 per generation.'),
('PS-2','critic','Nesslig20 (Peaceful Science)','2026-10-05','Response to Will Duffy | PART II - Clades, Chromosomes and ERVs','https://discourse.peacefulscience.org/t/18095',['ps-topic-18095.json','ps-s3.json','ps-Beale%20evolution%20order%3Alatest.json','ps-Vox%20Day%20order%3Alatest.json','ps-Gutsick%20Gibbon%20Vox.json','peacefulscience.json'],'full text + search results','adhom,A','Sec 2.1 identifies Day as source','Only Peaceful Science thread on Day found. Search results saved.'),
('RO-1','critic','Joe Felsenstein (describing J. Rosenhouse)','2022-05-18','Jason Rosenhouse\'s book on mathematical anti-evolutionism is available (annotated TOC)','https://pandasthumb.org/archives/2022/05/rosenhouse-on-mathematical-anti-evolutionism.html',['felsenstein-rosenhouse-toc.html'],'full text','D','Ch.4 Wistar; ch.6 protein space/Weasel/NFL','Felsenstein gave manuscript comments and a back-cover blurb (self-disclosed). Book itself NOT accessed.'),
('RO-2','critic','Matt Young (reviewing J. Rosenhouse)','2022-06-14','The Failures of Mathematical Anti-Evolutionism: Review (Panda\'s Thumb)','https://www.pandasthumb.org/archives/2022/06/Mathematical-Anti-Evolutionism.html',['rosenhouse-pt-review.html'],'full text','D','Track-1/Track-2 framing','Pre-dates Probability Zero.'),
('RO-3','critic','Jason Rosenhouse','2022-08-19','The Failures of Mathematical Anti-Evolutionism (Cambridge blog essay)','https://cambridgeblog.org/2022/08/the-failures-of-mathematical-anti-evolutionism/',['rosenhouse-cbblog.html'],'full text','D','-','Cambridge TOC PDF (assets.cambridge.org ...toc.pdf) timed out in curl and WebFetch: not retrieved. No Rosenhouse reply to Day found (Panda\'s Thumb search page: 0 hits for "Vox").'),
('JB-1','critic','Joe Bowers (via Day repost)','2026-03-04 (repost)','A Critical Review of Probability Zero (Day repost + point-by-point reply)','https://voxday.net/2026/03/04/a-critical-review-of-probability-zero/',['vd-bowers-repost.html'],'full text of repost; ORIGINAL NOT LOCATED','F,G2,B5','7 generic objections','Day says title was "Ignorant and Unscientific Drivel". Web searches for Bowers\' original found nothing.'),
('JF-1','critic','J-F Gariepy (via Day)','2019-02-11','Whopping the floor (Day quoting Gariepy transcript)','https://voxday.net/2019/02/11/whopping-the-floor/',['gariepy-whopping.html'],'full text; secondhand','A5,G1','2019 debate','Debate video/transcript itself not located (see harvest log). Gariepy\'s own channel not fetched.'),
('HO-1','ally','Ola Hossjer','2026-09-14','MITTENS - Convincing Arguments Against Neo-Darwinism (PDF, 8 pp)','https://billdembski.substack.com/api/v1/file/f5a8533e-7b7c-407b-880b-1ecbd256784c.pdf',['hossjer-mittens-review.pdf'],'full text (PDF)','A5,B3,B4,H','F_max numbers 127 -> 15,800 -> 10M; neutral 7.6M','Existence of the guest post CONFIRMED (resolves pass-1 disagreement).'),
('HO-2','ally','Bill Dembski (editor) / Ola Hossjer','2026-09-14','A Review of Vox Day\'s Main Argument in PROBABILITY ZERO (abridged, with Dembski brackets and intro)','https://billdembski.substack.com/p/a-review-of-vox-days-main-argument',['dembski-hossjer.json'],'full text (Substack API JSON)','A5,H','-','Dembski lists 24 earlier Day posts (via Grok) in the intro; list is secondhand. Brackets are Dembski\'s, not Hossjer\'s.'),
('DM-1','ally','Bill Dembski (interviewer) / Vox Day','2026-09-28','Vox Day Interview on Evolutionary Theory','https://billdembski.substack.com/p/vox-day-interview-on-evolutionary',['dembski-interview.json'],'full text','A5,B5,G1 (questions)','Attaches MITTENS 3 PDF (112KB) and PZ 2nd-ed ch.6','Attachment PDF not downloaded. Dembski\'s own questions are the ally-side steelman of A5, B5, G1.'),
('DM-2','ally','Bill Dembski','retrieved 2026-10-07','Dembski Substack feed/archive (enumeration)','https://billdembski.substack.com/feed',['dembski-feed.xml','dembski-archive.json','dembski-mr-improbability.json'],'listing','-','-','"Jason Rosenhouse\'s Whoppers" is a 2022 post (seen via search-result title on a Goodreads mirror), not on this Substack feed; not harvested (pre-dates Day; about Rosenhouse CSI chapters).'),
('KN-1','ally','Steve Keen','2026-02-03','Natura Facit Saltum (preface to The Frozen Gene)','https://profstevekeen.substack.com/p/natura-facit-saltum',['keen-natura.json'],'full text','ROOT','Frozen Gene (not PZ)','No equations; cites McFadden 2001, Schwartz 2000, Cairns 1988, Gorczynski & Steele 1980.'),
('TW-1','ally','Tree of Woe (interviewer) / Vox Day','2026-01-08','Why is the Probability Zero?','https://treeofwoe.substack.com/p/why-is-the-probability-zero',['treeofwoe.json'],'full text','A,G1','Day answers: 202,500 gens; 5.3 sigma','Interviewer adds no math. Source of Tipler foreword quote (secondhand).'),
('FP-1','ally','Jon Del Arroz (Fandom Pulse)','2026-10-05','Probability Zero Has the Evolution Internet Scrambling','https://www.fandompulse.com/p/probability-zero-has-the-evolution',['fandompulse.json'],'full text (569 words)','G (framing)','-','Names Hancock "Dr. Hanson". Mentions Day review "The Best They\'ve Got" of Rosenhouse (not harvested; Day-side).'),
('UJ-1','ally','John Samson (Uncle John\'s Band)','2026-01-24','Not a Chance','https://unclejohnsband.substack.com/p/not-a-chance',['ujb-notachance.json'],'full text','G1','average-rate argument','Worldview commentary; one math paragraph.'),
('UJ-2','ally','John Samson (Uncle John\'s Band)','2026-02-11','Freeze Frame','https://unclejohnsband.substack.com/p/freeze-frame',['ujb-freeze.json'],'downloaded, not analysed','?','-','Surfaced in search with "faulty math" snippet; not read in this pass.'),
('AH-1','ally','American Hypnotist','2026-02-05','Does Math Refute Evolution?','https://americanhypnotist.substack.com/p/does-math-refute-evolution',['amhyp.json'],'full text','A','Quotes PZ intro (450,000 gens / 1,600 = 281)','No independent math.'),
('KR-1','adjacent (ally who retracted)','keruru (C. Kereru)','2026-08-26','The Epicycle Was Elsewhere','https://claudekeruru.substack.com/p/the-epicycle-was-elsewhere',['ck-the-epicycle-was-elsewhere.json'],'full text','B3,B5,C,B4','retracts Ne-equivocation and aDNA claims','Linked from Day\'s blog (2026-08-26 "The Irrelevance of k = mu").'),
('KR-2','adjacent','keruru','2026-02-04','The broken evolutionary math.','https://claudekeruru.substack.com/p/the-broken-evolutionary-math',['ck-the-broken-evolutionary-math.json'],'full text','B3,A4,H','"mainly claude" summary of Day & Athos','Superseded by KR-1.'),
('KR-3','adjacent','keruru','2026-08-31','Kimura and the Red Flock','https://claudekeruru.substack.com/p/kimura-and-the-red-flock',['ck-kimura-and-the-red-flock.json'],'full text','B1,C,B4','quotes Day\'s critique of KR-1','Code/data on Zenodo not retrieved.'),
('KR-4','adjacent','keruru','2026-01-29/30','Probability Zero, a review too late. / Probability Zero (Part II)','https://claudekeruru.substack.com/p/probability-zero-a-review-too-late',['ck-probability-zero-a-review-too-late.json','ck-probability-zero.json'],'full text','A5,H','LLM-run calc: ~18M neutral vs 35M observed','Endorsing at the time; later retracted parts (KR-1).'),
('KR-5','adjacent','keruru','2026-02-05/09','The Winter of the Mayfly; The generational slowing of Humanity','https://claudekeruru.substack.com/p/the-winter-of-the-mayfly',['ck-the-winter-of-the-mayfly.json','ck-the-generational-slowing-of-humanity.json'],'downloaded, not analysed in depth','A4','d defined from life tables','Relevant to d (A4); to be mined in R2.'),
('KR-6','adjacent','keruru','2026-08/09','Other posts (Forty-Seven; Nobody in the Room; It Runs Does Not Mean It Is Correct; Nothing to Dismantle)','https://claudekeruru.substack.com/',['ck-forty-seven.json','ck-nobody-in-the-room.json','ck-it-runs-does-not-mean-it-is-correct.json','ck-nothing-to-dismantle.json','ck-archive.json','ck-archive2.json','ck-feed.xml'],'downloaded; off-topic or not analysed','-','-','Forty-Seven (chr 2 fusion) is evolution-adjacent but not about MITTENS. Other posts unrelated.'),
('KR-x','not-keruru','another "Keruru" (keruru.substack.com)','2026','religious-history newsletter','https://keruru.substack.com/',['keruru-feed.xml'],'feed only','-','-','NOT the author sought. Excluded.'),
]
out=['# Bibliography: critics, allies and adjacent commentators (R1 pass 2)','',
'Harvested 2026-10-07. `local path` is relative to `sources/raw/critics/` (gitignored). `sha256` is of the first local file listed; every file is listed with its hash in the appendix. Sides: `critic`, `ally`, `adjacent` (self-corrected ally), `critic-context`.','',
'Third-party archives used: Arctic Shift (Reddit mirror, because reddit.com returns 403/login wall to non-browser clients). Substack content was read via each publication\'s public JSON API and RSS (read-only GETs, 1 s between requests).','',
'| key | side | author | date | title | URL | local path | sha256 | access | branch | targets | notes |','|---|---|---|---|---|---|---|---|---|---|---|---|']
for k,side,au,dt,ti,url,fs,acc,br,tg,nt in E:
    lp=', '.join(fs) if fs else '(none)'
    hs=h(fs[0])[:64] if fs else '-'
    esc=lambda s:s.replace('|','/')
    out.append(f'| {k} | {side} | {esc(au)} | {dt} | {esc(ti)} | {url} | `{esc(lp)}` | {hs} | {acc} | {br} | {esc(tg)} | {esc(nt)} |')
out+=['','## Appendix: sha256 of every local file','','| file | bytes | sha256 |','|---|---|---|']
for root,_,files in os.walk(R):
    for f in sorted(files):
        p=os.path.join(root,f); rel=os.path.relpath(p,R)
        out.append(f'| {rel} | {os.path.getsize(p)} | {hashlib.sha256(open(p,"rb").read()).hexdigest()} |')
open('/home/na/projects/evo-sim/docs/research/sources/bib-critics.md','w').write('\n'.join(out)+'\n')
print(len(E))
