# key -> (label, url, date)
SRC={
'MC1':('McCarthy, "Why Probability Zero is Wrong About Evolution" (free repost)','https://dennismccarthy.substack.com/p/why-probability-zero-is-wrong-about-0d1','2026-09-11 (original paid post 2026-01-26)'),
'MC2':('McCarthy, "Vox Day Responds"','https://dennismccarthy.substack.com/p/vox-day-responds','2026-09-17'),
'PZ1':('Myers, "Vox Day\'s amazing ego, and Bill Dembski don\'t care"','https://freethoughtblogs.com/pharyngula/2026/10/02/vox-days-amazing-ego-and-bill-dembski-dont-care/','2026-10-02'),
'PZ2':('Myers, "Can we be done with Vox Day now?"','https://freethoughtblogs.com/pharyngula/2026/10/03/can-we-be-done-with-vox-day-now/','2026-10-03'),
'PZ3':('Myers, "Vox Day responds to my criticism of his refutation of evolution"','https://freethoughtblogs.com/pharyngula/2026/10/04/vox-day-responds-to-my-criticism-of-his-refutation-of-evolution/','2026-10-04'),
'CA1':('Camestros Felapton, Reading Vox Day So You Don\'t Have To 2026 [1]','https://camestrosfelapton.wordpress.com/2026/01/24/reading-vox-day-so-you-dont-have-to-2026-1/','2026-01-23/24'),
'CA2':('Camestros Felapton, ... 2026 [2]','https://camestrosfelapton.wordpress.com/2026/01/25/reading-vox-day-so-you-dont-have-to-2026-2/','2026-01-24/25'),
'CA3':('Camestros Felapton, ... 2026 [3]','https://camestrosfelapton.wordpress.com/2026/01/28/reading-vox-day-so-you-dont-have-to-2026-3/','2026-01-27/28'),
'CA4':('Camestros Felapton, ... 2026 [4]','https://camestrosfelapton.wordpress.com/2026/01/29/reading-vox-day-so-you-dont-have-to-2026-4/','2026-01-28/29'),
'CA5':('Camestros Felapton, ... 2026 [5]','https://camestrosfelapton.wordpress.com/2026/01/29/reading-vox-day-so-you-dont-have-to-2026-5/','2026-01-29'),
'CA6':('Camestros Felapton, ... 2026 [6]','https://camestrosfelapton.wordpress.com/2026/01/31/reading-vox-day-so-you-dont-have-to-2026-6/','2026-01-30/31'),
'KR-epi':('keruru, "The Epicycle Was Elsewhere"','https://claudekeruru.substack.com/p/the-epicycle-was-elsewhere','2026-08-26'),
'KR-broken':('keruru, "The broken evolutionary math."','https://claudekeruru.substack.com/p/the-broken-evolutionary-math','2026-02-04'),
'KR-flock':('keruru, "Kimura and the Red Flock"','https://claudekeruru.substack.com/p/kimura-and-the-red-flock','2026-08-31'),
'KR-rev':('keruru, "Probability Zero, a review too late."','https://claudekeruru.substack.com/p/probability-zero-a-review-too-late','2026-01-29'),
'HO-pdf':('Hossjer, "MITTENS - Convincing Arguments Against Neo-Darwinism" (PDF attached to Dembski post)','https://billdembski.substack.com/api/v1/file/f5a8533e-7b7c-407b-880b-1ecbd256784c.pdf','2026-09-14'),
'DEM-HO':('Dembski Substack, "A Review of Vox Day\'s Main Argument in PROBABILITY ZERO" (Hossjer guest post, abridged)','https://billdembski.substack.com/p/a-review-of-vox-days-main-argument','2026-09-14'),
'DEM-INT':('Dembski Substack, "Vox Day Interview on Evolutionary Theory"','https://billdembski.substack.com/p/vox-day-interview-on-evolutionary','2026-09-28'),
'KEEN':('Keen, "Natura Facit Saltum" (preface to The Frozen Gene)','https://profstevekeen.substack.com/p/natura-facit-saltum','2026-02-03'),
'TOW':('Tree of Woe, "Why is the Probability Zero?" (interview)','https://treeofwoe.substack.com/p/why-is-the-probability-zero','2026-01-08'),
'FP':('Del Arroz, Fandom Pulse, "Probability Zero Has the Evolution Internet Scrambling"','https://www.fandompulse.com/p/probability-zero-has-the-evolution','2026-10-05'),
'UJB':('Samson, Uncle John\'s Band, "Not a Chance"','https://unclejohnsband.substack.com/p/not-a-chance','2026-01-24'),
'AH':('American Hypnotist, "Does Math Refute Evolution?"','https://americanhypnotist.substack.com/p/does-math-refute-evolution','2026-02-05'),
'BOW':('Day repost of Bowers review + Day reply, "A Critical Review of Probability Zero"','https://voxday.net/2026/03/04/a-critical-review-of-probability-zero/','2026-03-04'),
'GAR':('Day, "Whopping the floor" (quotes Gariepy transcript)','https://voxday.net/2019/02/11/whopping-the-floor/','2019-02-11'),
'RO-FEL':('Felsenstein, "Jason Rosenhouse\'s book on mathematical anti-evolutionism is available" (annotated TOC)','https://pandasthumb.org/archives/2022/05/rosenhouse-on-mathematical-anti-evolutionism.html','2022-05-18'),
'PS-18094':('Nesslig20, "Response to Will Duffy | PART I - Population Genetics" (Peaceful Science)','https://discourse.peacefulscience.org/t/18094','2026-10-05'),
'YT-_Vu0ZVVjwHc':('Gutsick Gibbon + Zach Hancock, "No, Vox Day\'s AI-Generated Books Did Not Debunk Evolution" (auto-captions)','https://www.youtube.com/watch?v=_Vu0ZVVjwHc','2026-10-03'),
'YT-6jXiwrcC5PQ':('Gutsick Gibbon, Will Duffy livestream, Human Evolution #2 (auto-captions)','https://www.youtube.com/live/6jXiwrcC5PQ','2026-09-22'),
'YT-nTVRiEcswI8':('Jan Ghijselen, "Will Duffy\'s math on Gutsick Gibbon\'s channel." (auto-captions)','https://www.youtube.com/watch?v=nTVRiEcswI8','2026-09-28'),
'YT-jDxFtCOGZ3A':('Rebekah Davis / Examining Origins, "Can Evolutionists Finally Face the Math? Challenge Issued!" (auto-captions)','https://www.youtube.com/watch?v=jDxFtCOGZ3A','2026-09-23'),
'YTC-jDxFtCOGZ3A':('Comments under Examining Origins video jDxFtCOGZ3A','https://www.youtube.com/watch?v=jDxFtCOGZ3A','retrieved 2026-10-07'),
'RE-1wss2wj':('r/DebateEvolution, Dumb-and-Dumber, "New anti-evolution paper today from Vox Day"','https://www.reddit.com/r/DebateEvolution/comments/1wss2wj/','2026-09-28'),
'RE-1wxgsjm':('r/DebateEvolution, Sparky_6_4, "KITTENS: rebuttal to Vox Day\'s MITTENS 3.0 by Clauwd Meowgorithm"','https://www.reddit.com/r/DebateEvolution/comments/1wxgsjm/','2026-10-04'),
'RE-1wv4zeg':('r/DebateEvolution, Gutsick_Gibbon call for credentialed reviewers','https://www.reddit.com/r/DebateEvolution/comments/1wv4zeg/','2026-10-01'),
}
# (id, src, branch, who, quote, note, flags)  flags: 'second' = secondhand attribution within source
Q=[
# ---------- McCarthy
('MC-01','MC1','G3/D','McCarthy',"What Vox Day calculated—(1/20,000)20,000,000 —are the odds that a particular group or a pre-specified list of 20 million mutations (or 20 million mutations in a row) would all become fixed.",'Darwillion specific-vs-any objection.',''),
('MC-02','MC1','G3','McCarthy',"But our evolutionary history does not require that an exact group of 20 million mutations become fixed—only that some 20 million out of an enormous pool of candidate mutations become fixed.",'',''),
('MC-03','MC1','B3/B5','McCarthy',"50,000 x 9 million = 450 billion new mutations altogether.",'Uses Day\'s own inputs (100 mutations/person, Ne=10,000, 9 My). Derived: (100 x 10,000)/20 y = 50,000/yr.',''),
('MC-04','MC1','B5','McCarthy',"450 billion x 1/20,000 = 22.5 million fixed mutations.",'Equivalent to k=mu with all mutations treated as neutral.',''),
('MC-05','MC1','A5','McCarthy',"The human nuclear genome contains approximately 3.1 billion base pairs, roughly 690 times larger than the compact E. coli genome of about 4.6 million base pairs.",'',''),
('MC-06','MC1','A5','McCarthy',"Every newborn averages 60 to 100 de novo mutations.",'Uncited in-text; range, not a point value.',''),
('MC-07','MC1','A5','McCarthy',"As clear, the expected rate of fixed mutations has to be determined according to the particular circumstances of the population in question—its genome size, mutation rate, etc.",'',''),
('MC-08','MC2','B1/F','McCarthy',"Obviously, mutations, whether neutral or not, do not have to increase in frequency throughout a population one at a time.",'',''),
('MC-09','MC2','B1','McCarthy',"400 billion x 1/20,000 =20 million fixations. So when we apply the time available to the numbers we land on the exact correct result.",'Time-adjusted version: subtracts 40,000 gens (4Ne) from 360,000 gens.',''),
('MC-10','MC2','B2','McCarthy',"Across the genome as a whole, only 3% of new mutations are deleterious.",'Uncited. Relevant to Day\'s "3x more harmful than neutral" reply.',''),
('MC-11','MC2','A3x','McCarthy',"The 410 million base pair difference refers to structural variation, which includes duplications, insertions, etc., in which a single mutational event can cause hundreds, thousands, or even millions of base-pair differences.",'bp-vs-events.',''),
('MC-12','MC2','B4','McCarthy',"population geneticists actually use Kimura’s neutral-theory result to date the human–chimpanzee divergence.",'Circularity claim for the 6-9 My date; no citation given.',''),
# ---------- Myers
('PZ-01','PZ1','G1/G2','Myers',"This is not how evolution works. Evolution is a property of populations and involves massively parallel action on multiple traits and individuals at once.",'Serial-vs-parallel objection; no numbers.',''),
('PZ-02','PZ1','adhom','Myers',"There was no peer review, but just a dump of his assertions to an archive with no critical assessment.",'Process critique, not math.',''),
('PZ-03','PZ1','adhom','Myers',"Even worse, 7 of those citations are to the LTEE, and contradict his conclusions, and 2 are to ape genome sequencing papers",'Citation count claim (11 total) for MITTENS 3.0; not independently checked here.',''),
('PZ-04','PZ2','G2','Myers',"I debunked Vox Day’s stupid evolution “disproof” in one fairly short written post.",'',''),
('PZ-05','PZ3','G2','Myers',"My criticism was that his math was invalid and that he thinks evolution is a simple serial process (the same thing Zach Hancock pointed out)",'',''),
# ---------- Camestros
('CA-01','CA2','A','Camestros (transcribing Day)',"Fmax = (tdiv × d) ÷ (glen × Gf)",'Transcription of Day\'s equation from the book (first edition), intro.','second'),
('CA-02','CA2','A','Camestros',"Aside from whatever d is, the arithmetic itself isn’t wrong and Day appears to have taken care to pick numbers that would disadvantage his position.",'Internal-validity concession by a critic.',''),
('CA-03','CA2','A4','Camestros',"Day does not say in the introduction, nor does he say what it is in Chapter 1 or indeed any of the actual chapters.",'Author later corrects: d is defined in Ch.13 and App. A (see ETA in post).',''),
('CA-04','CA2','B6','Camestros',"So Day is treating ALL the genetic differences between chimps and humans as mutations that initially only occurred after the point of divergence of the two species.",'Ancestral-polymorphism objection.',''),
('CA-05','CA2','G1','Camestros',"It will cause him problems though because “Generations per fixation” reads as if he means each fixation must occur one at a time.",'',''),
('CA-06','CA3','A2','Camestros',"35 mutations in at 15,000 generation are present in all the subsequent generations i.e. fixed by 15,000. 1500÷35≈429 generations per fixed mutation as an average?",'Arithmetic typo in source: 15,000/35 = 428.6; text prints 1500. Author hedges ("I may well be misreading").',''),
('CA-07','CA3','A2','Camestros',"Day simply has not shown that. He has one estimate for his Gf term that he claims, without demonstrating it, to be a particularly fast fixation rate.",'',''),
('CA-08','CA3','A5','Camestros',"Assuming that it is a good model then what Day has shown is that if humans reproduced in the way e.coli reproduce then maybe humans would never have evolved from our common ancestor with chimps",'',''),
('CA-09','CA4','G3','Camestros',"However, the probability that SOME number is picked is close to 1 (not certain because the machine might break or an enraged horde of koalas might invade the studio).",'Lottery analogy for Darwillion.',''),
('CA-10','CA5','G1','Camestros',"He is correct that when he calculated the number it was an average. It isn’t intended to be a time for an individual chromosome.",'Concession in Day\'s favour on G1.',''),
('CA-11','CA5','A2','Camestros',"If the figure is an average then it includes some mutations that fixed quicker and so is not the fastest fixed mutation rate.",'',''),
('CA-12','CA5','A4','Camestros',"As this figure would clearly have changed during human evolution (and indeed demonstrably changed during human history), it doesn’t make a lot of sense.",'On d.',''),
# ---------- keruru
('KR-01','KR-epi','B5','keruru',"Mutation supply is 2Nμ with N the census count — mutations occur in gametes, and every reproducing individual contributes gametes.",'Self-retraction of the Ne-equivocation claim (ally -> concedes to critics).',''),
('KR-02','KR-epi','B5','keruru',"The fixation probability of a single new mutant in both chains: exactly 1/(2N_census), to fifteen decimal places.",'Exact Markov chain (Wright-Fisher + sweepstakes); code deposited per author (not retrieved).',''),
('KR-03','KR-epi','C','keruru',"Integrated across a million loci starting from intermediate frequencies, the expected number of fixations is somewhere near 10⁻²⁹.",'Zero fixations in 240 generations is expected under neutrality. Uses Ne~10^4 (circular, see KR-06).',''),
('KR-04','KR-epi','B5/C','keruru',"The claim about the substitution rate is withdrawn. The claim about the ancient-DNA finding is withdrawn.",'',''),
('KR-05','KR-epi','B4','keruru',"Calibrating against the fossil-dated human–chimpanzee split gives something closer to twice that.",'Context: pedigree rate ~1.2e-8; phylogenetic rate ~2x. Unreconciled per author.',''),
('KR-06','KR-flock','C/B6','Day via keruru',"He has retracted an empirical falsification of the clock by feeding in a parameter that the clock manufactures",'Day\'s critique of keruru\'s retraction as quoted by keruru: Ne~10,000 presupposes k=mu.','second'),
('KR-07','KR-broken','B3','keruru (LLM summary of Day & Athos)',"k = 2Nμ × 1/(2Ne) = (N/Ne)μ",'Pre-retraction statement of Day\'s B3 claim; post is "mainly claude".',''),
('KR-08','KR-rev','A5','keruru',"We observe 35 million differences. That’s already a 2-fold shortfall before we even consider positive selection.",'Ally-side LLM-assisted calc: ~30 mut/gen/lineage x ~300,000 gens x 2 lineages = ~18M vs 35M.',''),
('KR-09','KR-rev','A','keruru',"I can confirm his central thesis is mathematically sound—and he may have actually underestimated the severity of the problem.",'Advocacy claim, LLM-derived.',''),
# ---------- Hossjer
('HO-01','HO-pdf','A5','Hossjer',"This is a lot larger than the previous upper bound 127 of 𝐹 , but still more than three orders of magnitude smaller than 20 million fixations.",'Eq. 2.3: (1.25e-8/1e-10)*127 = 15,800. Check: 125*127 = 15,875.',''),
('HO-02','HO-pdf','A5','Hossjer',"which still is less than 20 million, but only by a factor of 2.",'Eq. 2.4: 15,800 * (3e9/4.6e6) ~ 10 million (assumes F proportional to L).',''),
('HO-03','HO-pdf','H','Hossjer',"it implies that the number of fixations with a selective advantage along the supposed human lineage is far less than what equation (4) predicts, perhaps more in line with equation (3).",'Haldane step asserted, not computed.',''),
('HO-04','HO-pdf','B3/B5','Hossjer',"equation (5) is based on the neutral theory of evolution.",'Context: Hossjer\'s neutral calc F_hum = 3e9*0.45*1.25e-8*450,000 = 7.6 million (eq. 3.1; PDF text numbers it (5)); he states both calcs assume parallel fixation between loci. Checks: 3e9*1.25e-8=37.5; *0.45=16.9; *450,000 = 7.59e6.',''),
('HO-05','HO-pdf','B4','Hossjer',"the neutral theory of evolution cannot explain common ancestry between humans and chimps at all based on genome-wide nucleotide differences between the two species, since the neutral theory is used in the first place to date the assumed time of divergence.",'Circularity claim (shared with McCarthy MC-12).',''),
('HO-06','HO-pdf','A','Hossjer',"I agree with this conclusion, also after adjusting the MITTENS equation for the different mutation rates of humans and E. coli.",'',''),
('HO-07','DEM-HO','A','Dembski (intermediary)',"Note that his positive remarks apply to Vox Day’s main argument, not to the book as a whole.",'Scope limit on the endorsement.',''),
('HO-08','DEM-HO','A','Dembski (editor of abridged text)',"That calculation yields a number very close to Day’s genome-size-adjusted bound.",'Bracketed summary inserted by Dembski, not Hossjer.',''),
# ---------- Dembski interview
('DE-01','DEM-INT','A5','Dembski (question)',"A critic could accept the logic of using experimental evolution as a benchmark yet argue that transferring a bacterial result (as in Richard Lenski’s Long-Term Evolution Experiment) to primates requires scaling for differences in mutation rate and genome size.",'Interviewer poses the A5 objection to Day.',''),
('DE-02','DEM-INT','B5','Dembski (question)',"Why does that result not bypass the fixation bottleneck MITTENS identifies?",'On k=mu.',''),
('DE-03','DEM-INT','ROOT','Dembski',"As an intelligent design proponent, I have my own arguments for thinking that evolutionary mechanisms face serious explanatory shortfalls.",'Stated position.',''),
# ---------- Keen / Tree of Woe / FP / UJB / AH
('KE-01','KEEN','ROOT','Keen',"The reason it fails, as Vox Day and Claude Athos show in this book, is time.",'Preface contains no equations or numbers; argument rests on cited Lamarckian/quantum hypotheses (McFadden 2001; Schwartz 2000).',''),
('KE-02','KEEN','ROOT','Keen',"The savage demolition that Day and Athos undertake in this book of the statistical implications of the “Blind Watchmaker” hypothesis",'Endorses The Frozen Gene (not Probability Zero).',''),
('TW-01','TOW','A','Day (answering Tree of Woe)',"The single most important number is 202,500 generations.",'Interview answer; yet another gens figure (6.3 My/25 yr = 252,000; 9 My/20 = 450,000).','second'),
('TW-02','TOW','A','Day (answering Tree of Woe)',"we’re talking about a 5.3 Sigma negative probability.",'Sigma framing for "probability zero".','second'),
('FP-01','FP','adhom','Del Arroz',"A headcount of degrees isn’t a rebuttal",'Valid process point against credential drives (aimed at Gutsick Gibbon).',''),
('FP-02','FP','G','Del Arroz',"The core claims are specific and testable: generations per fixation in the long-term E. coli experiment, and how that scales to human-chimp divergence.",'Names Hancock as "Dr. Hanson" (error in source).',''),
('UJ-01','UJB','G1','Samson',"The total number of mutations separating species includes all of them. Parallel, sequential, or however else. Hence the word “total”.",'Ally formulation of the average-rate argument.',''),
('UJ-02','UJB','G1','Samson',"And dividing “total” by “amount of time” gives a simple, unweighted average number. The rate.",'Weakness: an observed average divergence rate is not an upper bound on achievable rate.',''),
('AH-01','AH','A','American Hypnotist',"Given that the rate of gene fixation for a simple organism must be faster than what is possible with more complex organisms, this shows us that evolutionary theory is mathematically defeated even when given the greatest possible advantage.",'Unsupported generalisation; no calculation.',''),
# ---------- Bowers (via Day)
('BO-01','BOW','F','Bowers (as reposted by Day)',"The correct approximation for a beneficial mutation is roughly 2s (in diploids under weak selection), not 1/N.",'','second'),
('BO-02','BOW','G2','Bowers (as reposted by Day)',"Treating it like a serial lottery is a category error.",'','second'),
('BO-03','BOW','F','Day (reply to Bowers)',"The reviewer has confused fixation probability with fixation rate. These are two different things.",'Day\'s reply; no equation given in reply.',''),
('BO-04','BOW','adhom','Day (reply to Bowers)',"Not a single calculation. Not a single specific engagement with any of my actual numbers.",'Accurate as to the reposted text: Bowers\' seven points contain no numbers.',''),
# ---------- Gariepy (via Day)
('GA-01','GAR','A5','Gariepy (transcript as posted by Day)',"Fixation rate in single cell organism is not equal to fixation rate in mammal. And there is two reasons for it. One is sexual reproduction. The second is variability of population size.",'2019 debate follow-up; secondhand via Day; no numbers.','second'),
('GA-02','GAR','A','Day (reply)',"This rate reduced the average fixed mutation propagation time from 1,600 to 15.7 generations",'Day\'s 2019 minimum-viable-population bottleneck model.',''),
# ---------- Rosenhouse via Felsenstein
('RO-01','RO-FEL','D','Felsenstein (describing Rosenhouse ch.4)',"The Legacy of the Wistar Conference. Using the 1966 conference called by some mathematical critics of evolutionary biology, explains why their critiques were refuted, and how present-day creationists misrepresent what was said at that conference.",'Chapter scope only; book predates Probability Zero.',''),
('RO-02','RO-FEL','D','Felsenstein (describing Rosenhouse ch.6)',"Information and Combinatorial Search. Information theory, claims that random mutations always decrease the information content of biological systems. Protein space. Dawkins' Weasel. The No Free Lunch Theorem.",'Chapter scope only.',''),
# ---------- Peaceful Science
('PS-01','PS-18094','B5','Nesslig20',"Let’s assume a conservative neutral mutation rate of [ μ_G = 75 ]. That means [ k = 75 ] mutations will fix per generation.",'Weakness: 75 is a per-diploid-offspring de novo count; stated as per haploid genome.',''),
('PS-02','PS-18094','B5','Nesslig20',"So, the expected number of fixed neutral mutations that separates humans and chimps is ~37.8 million based on this rough calculation.",'2 x 75 x 6.3e6/25 = 37.8e6 (checks).',''),
('PS-03','PS-18094','A3x','Nesslig20',"since they use one (or a few) reference genomes, not all of the differences they identified between genomes are actually fixed in either the human or chimp populations.",'Reference-genome differences vs fixed differences.',''),
('PS-04','PS-18094','H','Nesslig20',"Haldane’s reproductive cost limit does not apply to drift, but can it account for most of the genomic differences between humans and chimps?",'',''),
# ---------- Gutsick Gibbon / Hancock video
('GG-01','YT-_Vu0ZVVjwHc','G1','Hancock',"it assumes that each mutation has to both arise and go to fixation before the next mutation can occur.",'Interpretation of F_max = t/(g*Gf) as sequential.',''),
('GG-02','YT-_Vu0ZVVjwHc','A','Hancock',"this basic math is off by a factor of two",'Both lineages accumulate fixations.',''),
('GG-03','YT-_Vu0ZVVjwHc','B5','Hancock',"and then what you're left with is a neutral substitution rate that's equal to the mutation rate",'Derivation via Taylor expansion of Kimura fixation probability.',''),
('GG-04','YT-_Vu0ZVVjwHc','B5','Hancock',"that's about 76.8 uh new mutations that are fixed in the population every single generation.",'Uses 6.4e9 (diploid) x 1.2e-8 = 76.8; corrected on-screen below.',''),
('GG-05','YT-_Vu0ZVVjwHc','B5','Hancock',"we can't use 6.4. This is the diploid genome size for the fixation rate because you fix on a hloid genome. So, it should be 3.2 e to the 9.",'In-video correction (post-edit insert).',''),
('GG-06','YT-_Vu0ZVVjwHc','B5','Hancock',"If we divide that in half to take the the hloid genome size that gives us 76.",'Keeps 76 via cited de novo count of 98-206 incl. structural variants (Perky? et al. 2025; name garbled in captions).',''),
('GG-07','YT-_Vu0ZVVjwHc','A5','Hancock',"you only expect four e to the neg5 mutations to fix per generation.",'Bacterial neutral expectation uses mu~1e-11; Wielgoss 2011 (via McCarthy) gives 8.9e-11/bp.',''),
('GG-08','YT-_Vu0ZVVjwHc','A5','Hancock',"under neutrality, it should take like 22,000 generations to fix one mutation.",'vs LTEE observed ~1,322-1,600; with 8.9e-11 the neutral figure is ~2,500.',''),
('GG-09','YT-_Vu0ZVVjwHc','B5','Hancock',"we'll say about 38 million.",'2 x 252,000 x 76.8 = 38.7e6.',''),
('GG-10','YT-_Vu0ZVVjwHc','A3x','Hancock',"the number is 205 million differences, right?",'Hancock suspects 205M includes gap divergences and is not a point-mutation count.',''),
('GG-11','YT-_Vu0ZVVjwHc','A3x','Hancock',"when you divide this out over 200 205 million you get something like 407",'Mutation count/gen needed for 205M: ~407; ~5x the 76.8 neutral supply.',''),
('GG-12','YT-_Vu0ZVVjwHc','A3x','Hancock',"we can account even for the highest end of the mutational differences with a model that assumes that selection was not involved at all.",'Applies SNV mutation-rate model to 205M structural-inclusive count (acknowledges difficulty).',''),
('GG-13','YT-_Vu0ZVVjwHc','B6','Hancock',"there would basically be no genetic variation amongst individuals except for the mutation that's increasing in frequency",'Empirical prediction of the serial model vs observed site-frequency spectra.',''),
# ---------- Duffy stream
('DU-01','YT-6jXiwrcC5PQ','A4','Duffy (presenting Day)',"the actual fixation time in a population where selection operates at 80% efficiency will take approximately 25 generations.",'Presentation of Day\'s overlapping-generations claim.','second'),
('DU-02','YT-6jXiwrcC5PQ','A','Duffy',"180 total fixed mutations is all there's time for using the fastest rate of mutational fixation ever observed in any organism",'MITTENS 2.x numbers: 252,000/1,400.',''),
('DU-03','YT-6jXiwrcC5PQ','G1','Duffy (live reply)',"the number he's using in the math is already parallel fixation.",'Day\'s G1 position restated by Duffy.',''),
('DU-04','YT-6jXiwrcC5PQ','epistemic','Duffy',"I am not a mathematician as I mentioned. So, I'm not certain he's right.",'',''),
('DU-05','YT-6jXiwrcC5PQ','epistemic','Gutsick Gibbon',"I'm not afraid of of any of Will's points coming to the table because frankly I think the science can handle it",'',''),
# ---------- Math teacher
('DZ-01','YT-nTVRiEcswI8','G2','Ghijselen',"Of course you say that's not possible, they run parallel. Well, the same goes with mutation and fixation.",'Marathon analogy: 60,000 runners x 4 h = 240,000 h serial.',''),
('DZ-02','YT-nTVRiEcswI8','A','Ghijselen',"The length of a generation for humans is 25 years times 1,000 400",'Arithmetic: 6.3e6/25 = 252,000; /1,400 = 180 (checks).',''),
# ---------- Davis
('RD-01','YT-jDxFtCOGZ3A','epistemic','Davis',"I haven't read his book. I am relying only on the presentation",'',''),
('RD-02','YT-jDxFtCOGZ3A','epistemic','Davis',"I predict that they will provide essentially no answer.",'A 3.5 h response (GG/Hancock, 2026-10-03) now exists; whether substantive is for R4.',''),
('RD-03','YT-jDxFtCOGZ3A','D','Davis (relaying Eden)',"it would take about 10 to the 36th power of genetic transmissions to do that.",'Wistar/Eden gene-pair figure relayed secondhand.','second'),
# ---------- YT comments (Mansfield etc.)
('MF-01','YTC-jDxFtCOGZ3A','B5','Mansfield',"Genetic drift happens in every population and his claim otherwise is mystifying. Population size only affects which alleles are effectively neutral.",'Replies to Day\'s "no drift above 10,000".',''),
('MF-02','YTC-jDxFtCOGZ3A','B5','Mansfield',"If even just 2 of these 100 are neutral - which is certainly way under the actual proportion - then in a population of size N there are about 2*N new neutral alleles introduced each generation.",'',''),
('MF-03','YTC-jDxFtCOGZ3A','B5','Mansfield',"So, the expectation is that there will be on average 1 neutral fixation every generation if just 2% of new mutations are neutral.",'Weakness: 1/gen x ~450,000 gens = 450,000 << 20M; the illustration does not by itself close the gap (needs ~44x more).',''),
('MF-04','YTC-jDxFtCOGZ3A','F','Mansfield',"The time it takes for one allele to get fixed is not important, it is the time BETWEEN successive fixations that is important.",'Latency vs throughput (truck analogy).',''),
('MF-05','YTC-jDxFtCOGZ3A','B1','Mansfield',"The ‘pipeline’ would have been full from the X generations preceding that point in time.",'Full-pipe assumption; the empty-pipe question is the B1/B6 crux.',''),
('MF-06','YTC-jDxFtCOGZ3A','A3x','Mansfield',"The numbers I’ve seen give this number around 25 million give or take, not 200 million.",'Uncited.',''),
('MF-07','YTC-jDxFtCOGZ3A','B5','Mansfield',"I’ve been a research geneticist for almost 40 years",'Self-described credential (unverified here).',''),
('MF-08','YTC-jDxFtCOGZ3A','A','Mansfield',"But the model that Day is using here is biologically naive and is not proof of the ‘impossibility’ of evolution by selection.",'Concedes the selection-specific question is distinct from neutral divergence.',''),
# ---------- Reddit
('RE-01','RE-1wss2wj','G1','Dumb-and-Dumber',"That assumes the entire genome waits for one mutation to finish before another starts.",'On MITTENS 3.0 sec. 8.2.',''),
('RE-02','RE-1wss2wj','A2','Dumb-and-Dumber',"Section 6.4 also makes a tenfold arithmetic mistake: 3.2 billion × 1.2 × 10⁻⁸ × 100 is 3,840 mutations per haploid genome, not 38,400.",'Checks: 3.2e9*1.2e-8 = 38.4; x100 = 3,840.',''),
('RE-03','RE-1wss2wj','E','Dumb-and-Dumber',"Their correction formula then produces minus 906 “true fixations” in Ara−2.",'Estimator artefact.',''),
('RE-04','RE-1wss2wj','A2','Dumb-and-Dumber',"Their Ara+5 count drops from 38 such mutations at 30,000 generations to zero at 60,000.",'',''),
('RE-05','RE-1wss2wj','A3x','Dumb-and-Dumber',"bases affected by a rearrangement are not separate mutation events: one structural change can affect millions of bases.",'',''),
('RE-06','RE-1wss2wj','B5','Dumb-and-Dumber',"or about 9.7 million over its proposed 252,000 generations.",'38.4 x 252,000 = 9.68e6 (checks); framed by author as illustration.',''),
('RE-07','RE-1wss2wj','A5','Dumb-and-Dumber',"It follows largely nonrecombining bacteria descended from one clone, repeatedly transferred into the same glucose-limited environment.",'',''),
('RE-08','RE-1wxgsjm','A5/B5','Sparky_6_4 (AI-assisted)',"Once one scales the LTEE rate for the mutation supply per genome and counts SNVs as events, the achievable number (17.9 million) is about equal to the required number (17.5 million).",'191 x ~94,000 = 17.9e6 (checks).',''),
('RE-09','RE-1wxgsjm','A5','Sparky_6_4 (AI-assisted)',"I present this as an illustration, not as a proof that adaptive fixations scale linearly with mutation rate.",'Author flags the linear-scaling assumption.',''),
('RE-10','RE-1wxgsjm','E','Sparky_6_4 (AI-assisted)',"A count of fixed mutations cannot be negative; the negative value comes from the paper’s own correction",'',''),
('RE-11','RE-1wxgsjm','epistemic','Sparky_6_4 (AI-assisted)',"Literature citations are from memory and should be verified before reuse.",'Self-disclosed limitation.',''),
('RE-12','RE-1wv4zeg','epistemic','Gutsick Gibbon',"I am only aware of three people with doctorates who have \"vetted\" Day's work, and they are all associates of the Discovery Institute",'Claim about Day\'s "10 math PhDs"; unverified.',''),
('RE-13','RE-1wss2wj','B5','DarwinZDF42',"ignores that neutral mutations fix at approximately the mutation rate",'',''),
('MC-13','MC1','epistemic','McCarthy',"I have published multiple peer-reviewed papers on evolution and biogeography",'Self-described.',''),
('PZ-06','PZ2','epistemic','Myers',"but as someone who is not a population geneticist, I did learn a few details, so that was worthwhile.",'On the Gutsick Gibbon video.',''),
('CA-13','CA1','epistemic','Camestros',"I’m not a biologist, I’m not really a mathematician and I have no real idea what the current state of mathematical modelling of genetics and evolution is",'Self-described; footnote digit follows in source.',''),
('GG-14','YT-_Vu0ZVVjwHc','epistemic','Hancock',"I have a PhD in ecology and evolutionary biology.",'Self-stated; unverified here.',''),
('GG-15','YT-_Vu0ZVVjwHc','epistemic','Hancock',"now I am an assistant professor at Augusta University where I teach population genetics.",'Self-stated; unverified here.',''),
('DZ-03','YT-nTVRiEcswI8','epistemic','Ghijselen',"I am a math teacher in secondary education.",'Self-described.',''),
('KE-03','KEEN','epistemic','Keen',"evolutionary dynamics has been a side interest of mine for decades.",'Self-described.',''),
('HO-09','DEM-HO','epistemic','Hossjer (byline)',"Professor of Mathematical Statistics, Stockholm University",'Byline as printed in Dembski post.',''),
('TI-01','TOW','ROOT','Tipler (via Tree of Woe)',"describes it as “the most rigorous mathematical challenge to Neo-Darwinian theory ever published.”",'Tipler\'s own foreword not retrieved.','second'),
('TI-02','PZ1','ROOT','Day (via Myers)',"even an Introduction and an Appendix from Dr. Tipler.",'','second'),
('TI-03','DEM-HO','ROOT','Dembski',"Tipler gave it a glowing endorsement and also contributed an appendix to the book.",'',''),
('KE-04','KEEN','epistemic','Keen',"I first read these works when researching evolutionary programming while undertaking my PhD in economics in the 1990s",'Self-described.',''),
('KE-05','KEEN','ROOT','Keen',"is orders of magnitude greater than the age of the Universe, let alone the age of the Earth.",'Check: 6.3e6 y x 1.075e6 (MITTENS 3.0 shortfall) = 6.8e12 y = ~490x the age of the universe (13.8e9 y); i.e. consistent with the claim only if the bacterial rate is taken as a fixed ceiling. Preface itself gives no numbers.',''),
('GG-16','YT-_Vu0ZVVjwHc','epistemic','Hancock',"or back of the napkin sort of way",'Self-described precision of the null-model calculation (no CI).',''),
('DU-06','YT-6jXiwrcC5PQ','A5','Duffy',"the mammal fixation rate is slower like way slower uh than bacteria",'Assertion in live Q&A; no numbers given.',''),
('HO-10','DEM-HO','ROOT','Hossjer',"I rather advocate uncommon descent between the two species.",'Ally disagrees with Day on common descent while endorsing the fixation argument.',''),
('HO-11','HO-pdf','H','Hossjer',"so that the overall fitness of the population declines over time and the population eventually (and quite rapidly) dies.",'Genetic-entropy-style claim about slightly deleterious fixations; no calculation in the text.',''),
('CA-14','CA5','A','Camestros',"Day’s core argument hasn’t changed since February 2019",'Contradicted by version drift (d, 205M, 1,322) in PLAN.md; he reviewed the first edition.',''),
]
