import sys; sys.path.insert(0,os.environ.get("EVO_WORK","work")+"")
from gen_lib import *
WP="Moorhead & Kaplan (eds), *Mathematical Challenges to the Neo-Darwinian Interpretation of Evolution*, Wistar Institute Monograph No. 5 (1967; symposium 25-26 Apr 1966), local copy = 1985 Liss reprint scan, OCR text; page = printed folio (page numbers from the PDF text layer headers; OCR garbles noted in place)"
DINT_S="[Vox Day Interview on Evolutionary Theory](https://billdembski.substack.com/p/vox-day-interview-on-evolutionary) (Dembski Substack), 2026-09-28, appended chapter 'From Probability Zero (2nd ed.) on 1966 Wistar Symposium, Chapter 6: The 1966 Meeting of the Minds' (primary Day text, posted with Day's permission)"
LIT0="| Cited work | What it actually says (quote) | Fidelity |\n|---|---|---|\n"
E1=ex('W',"We may think of words which are 250 letters long, constructed from an alphabet of 20 different letters. There are about 20250 such words or about 10 325 •")
E2=ex('W',"The number of protein molecules that ever existed is by this computation about 10 52 •")
E3=ex('W',"Clearly the number of species of protein molecules is much smaller than this, say 1040, but it would be immaterial to our purposes to try to make such a reduction.")
E4=ex('W',"Assume a biosphere of cells 1 cm. thick over the surface of the earth, a protein concentration in these cells of 30%, a density of 1, an age for life on earth of 10 billion years and an average lifetime of a protein molecule of 1 second. Of course all these quantities except density err very heavily toward the high side.")
E5=ex('W',"Yet this relatively small set of 1052 proteins contains within it all the useful proteins which have existed to date.")
E6=ex('W',"Now the space of all polypeptide sequences of length 250 or less contains about 10 350 members. Over the last billion years a very liberal estimate of the number of genetic couplings is about 1037 • In fact the number of protein molecules of such size that ever existed on earth can be estimated to be less than 10 55 •")
E7=ex('W',"Thus, either the vast proportion of polypeptide chains perform useful biological functions in some integrated entity (a rather implausible hypothesis) or else evolution was directed to the incredibly small proportion of useful protein forms")
E8=ex('W',"Either functionally useful proteins are very common in this space so that almost any polypeptide one is likely to find has a useful function to perform or else the topology appropriate to this protein space is an important feature of the exploration; that is, there exist certain strong regularities for finding useful paths through this space.")
E9=ex('W',"Until such time, neo-Darwinian evolution is a restatement in current terminology of Darwin's seminal insight that the origin of species can have a naturalistic explanation.")
E10=ex('W',"Of course, he is correct, but I believe he has misunderstood my argument.")
E11=ex('W',"Simply stated, there are some paths which lead fairly directly from one point to another in this space but there are many more paths of very much greater length between the same two points. The actual path-lengths traversed are limited by the number of generations in the organism'S history so that the long paths are inaccessible, only the short ones can have been taken.")
E12=ex('W',"On this basis we would expect on the order of 2,700,000 generations to be required for one hemoglobin chain to transform to the other. This is a little large but not implausible.")
E13=ex('W',"The mathematical problem appears to me to be a difficult one and I have no estimate to offer except that it clearly is many powers of 10 greater than the minimal distance of 120.")
E14=ex('W',"Then to achieve a single ordered pair of genes on these assumptions would require something like 1036 genetic transfers.")
WS=f"Eden, 'Inadequacies of Neo-Darwinian Evolution as a Scientific Theory', in {WP}"
# ---------------- D3
write('D3-eden-sequence-space-arithmetic','D3','Eden: there are about 20^250 = 10^325 polypeptide chains of length 250 versus about 10^52 protein molecules that could ever have existed','literature','D','D',
 "[{type: supports, target: D},{type: depends-on, target: D3a}]",'false','D is not required for ROOT','firsthand',
 'holds','20^250 = 10^325.26 reproduces; the 10^52 figure does not reproduce from the printed inputs (see D3a) but the comparison is insensitive to it','accurate','Day\'s transcription of the two numbers matches p.7; Day\'s "functional proteins" wording is looser than Eden\'s "protein molecules" (D3a)','contested','whether the size comparison bears on evolutionary search depends on landscape structure (D3b)',
 q(E1)+"\n\n"+q(E2)+"\n\n"+q(E3)+f"\n\nSource: {WS}, p.7. OCR renders 20^250 as '20250', 10^325 as '10 325 •', 10^52 as '10 52 •', 10^40 as '1040'. For comparison, Eden's pre-circulated working paper (same volume, p.110) states:\n\n"+q(E6)+f"\n— Eden, Preliminary Working Paper, p.110 ('10 350', '1037', '10 55' = 10^350, 10^37, 10^55).",
 "S = A^L with A = 20, L = 250: log10 S = 250*log10(20) = 325.257, i.e. S = 1.81e325 (recomputed; Eden: 'about 10^325'). N_ever = 10^52 (p.7; talk) or <10^55 (p.110; working paper). N_ever/S = 10^-273 (talk) or 10^-270 (working paper). The working paper's '10^350' for 'length 250 or less' is not reproduced: sum over lengths <=250 is 20^250*(1+1/20+...) = 1.05*20^250 = 10^325.3. Wright's discussion (p.117) quotes the working paper's 10^350 (D6).",
 "- Stated (Eden): the biosphere inputs; the upper bound is deliberately high; the real number of species of proteins is 'much smaller, say 10^40'.\n- Implicit: 250 residues is typical of a protein; 20 equiprobable letters; sequences of other lengths ignored; counting molecules, not distinct sequences, as the exploration budget.",
 "- Against: none on the arithmetic of 20^250. On 10^52: reproduction with Eden's own stated inputs gives 10^55 (D3a). Eden himself calls the reduction to 10^40 'immaterial'.\n- In support: Day (D), Rebekah Davis (D14) cite Eden.\n- Weaknesses: the number is not a probability; Eden uses it to pose a dichotomy (D3b), not a bound. Because Eden's two figures (10^325 and 10^52) differ by 273 orders of magnitude, the conclusion is not sensitive to any single input error of a few orders.",
 LIT0+"| Wistar p.7 | 'about 20^250 ... about 10^325'; 'about 10^52' | primary |\n| Wistar p.110 | 10^350; <10^55 | primary (working paper) |",
 "Written before the arithmetic. Prediction under the claimant (Eden/Day): 20^250 = 10^325 +- 0.5; 10^52 reproducible from the printed inputs within ~1 order. Under the opposing model (critics): arithmetic correct but the number is irrelevant. Result that would change the arithmetic verdict: log10(20^250) outside [324.7, 325.8].",
 "S1 (done): `python3 -I -c \"import math;print(250*math.log10(20))\"` -> 325.257 (reconciles). 10^52 reconstruction: see D3a (does not reconcile with p.7 inputs: 10^55.0).","Alphabet size A=20; length L=250; N_ever (exploration budget); distinct-sequence vs molecule-count budget.")

d3a_day=ex('dint',"Assume a biosphere one centimeter thick covering the entire Earth, filled with cells at a density of a billion billion per cubic centimeter, each containing proteins at a concentration of one ten-thousandth, with each protein molecule lasting an average of one second, over a total span of ten billion years. This yields approximately one followed by fifty-two zeros—ten thousand trillion trillion trillion trillion—protein molecules that could ever have existed.")
write('D3a-eden-molecules-not-functional-proteins','D3a','The 10^52 is a count of protein molecules that could ever have existed, not of functional proteins; Day restates Eden\'s inputs differently','literature','D','D3',
 "[{type: depends-on, target: D3},{type: attacks, target: D}]",'false','D is not required for ROOT','firsthand',
 'holds','the order of the count does not matter to the 273-order comparison','partial','Eden: "protein molecules ... ever existed"; Day (Best I): "functional proteins that have ever existed"; Day ch.6 restates the inputs (cell density 10^18 per cm^3, concentration 10^-4) differently from Eden (30%, density 1)','contested','',
 q(E4)+f"\n\nSource: {WS}, p.7.\n\n"+q(E5)+"\n\nSource: same, p.7 (the sentence that licenses reading the 10^52 as covering 'all the useful proteins which have existed').\n\n"+q(d3a_day)+f"\n\nSource: {DINT_S}. Day's Best They've Got I (2026-10-05) says: 'the number of functional proteins that have ever existed is ~10^52' (see D).",
 "Count: N_ever = (protein mass of biosphere / molecular mass) * (age / lifetime). Biosphere volume V = 4*pi*R^2 * 1 cm = 5.10e18 cm^3 (R = 6.371e8 cm); protein mass m = V * density(1 g/cm^3) * c; molecules alive = m*N_A/M; ever = alive * (1e10 yr = 3.156e17 s) / (1 s). With M = 27.5 kDa (250 residues x 110 Da):\n- Eden p.7 inputs (c = 0.30): m = 1.53e18 g; alive 3.35e37; ever **1.06e55** (log10 55.02). Matches Eden's working paper ('less than 10^55', p.110) and is 3 orders above the 10^52 he prints in the talk.\n- Day ch.6 inputs read as a 1e-4 mass fraction of the biosphere volume (cell density then irrelevant): m = 5.10e14 g; alive 1.12e34; ever **3.5e51** (log10 51.55), i.e. 'approximately 10^52'. As printed (cells at 10^18 per cm^3 each with proteins at 10^-4) the inputs are not self-consistent: a cell of volume 10^-18 cm^3 is ~10 nm across, below virus size.\nSo neither source's printed inputs reproduce Eden's 10^52 with a 27.5 kDa protein except Day's version, read charitably.",
 "- Stated (Eden): upper bound; inputs err 'very heavily toward the high side'.\n- Implicit: all proteins on Earth are 250-residue; one-second turnover.",
 "- Against: the distinction between molecules and distinct functional sequences: many molecules are copies of the same sequence, so distinct sequences ever realised is far below 10^52 (Eden's own 'say 10^40').\n- In support: Eden, p.7, says the 10^52 set 'contains within it all the useful proteins which have existed to date', so Day's paraphrase is a licensed shorthand if 'functional proteins' means 'contained in'.\n- Weaknesses: for D's argument the relevant budget is distinct sequences tested by lineages; neither the molecule count nor 10^40 is that quantity.",
 LIT0+"| Wistar p.7 | quoted above | accurate |\n| Wistar p.110 | working paper: less than 10^55 | accurate; matches the reconstruction |",
 "Written before the reconstruction. Prediction under Eden: 10^52 +- 1. Under a re-computation with Eden's printed inputs: 10^55. (The prediction under Eden failed; recorded as a fidelity finding, not a refutation of the comparison.)",
 "Script (arithmetic, not committed): area = 4*pi*(6.371e8)^2; mol = area*1*c/(27500/6.022e23); ever = mol*3.156e17. Results above. Recomputed twice (c=0.3 and c=1e-4).","N_ever (budget) as a parameter with distinct-sequence variant; generation/turnover time.")

write('D3b-eden-two-hypotheses-and-path-length','D3b','Eden: either functional proteins are very common or the topology of the space provides paths; the objection is path length, not search size','literature','D','D3',
 "[{type: depends-on, target: D},{type: attacks, target: D6}]",'false','D is not required for ROOT','firsthand',
 'pending','Eden says he cannot compute the path-length distribution','accurate','Eden states the dichotomy and the path-length reply himself','contested','topology horn is the live question (D2h)',
 q(E8)+f"\n\nSource: {WS}, p.7.\n\n"+q(E10)+"\n\n"+q(E11)+"\n\nSource: same, p.8 (reply to Wright's twenty-questions point, D6).\n\n"+q(E13)+"\n\nSource: same, p.8.\n\n"+q(E7)+f"\n\nSource: Eden, Preliminary Working Paper, p.110.\n\n"+q(E9)+"\n\nSource: same, p.109-110 (the sentence is in the paper's conclusion).",
 "Eden's dichotomy: H1 = functional proteins are common; H2 = the topology provides 'strong regularities for finding useful paths'. Eden considers H1 'against' the evidence (the chi-square observation that the great bulk of known proteins are samples from the same amino-acid distribution, p.7). His reply to Wright (p.8): the relevant quantity is the length of paths between functional points, limited by the number of generations; he states he has 'no estimate to offer' of the typical path length on a random fitness surface beyond 'many powers of 10 greater than the minimal distance of 120'.",
 "- Stated: path length, not space size, is the issue; paths are limited by generations.\n- Implicit: the fitness surface is 'random' in the sense that paths meander; the shortest path is unlikely to be the one followed.",
 "- Against: Wright (D6) points out selection reduces the search; Waddington (D2e) argues that local density of function is high. Eden does not claim a probability-zero result: his working paper ends 'an adequate scientific theory of evolution must await the discovery and elucidation of new natural laws' and states that neo-Darwinism is 'a restatement ... of Darwin's seminal insight that the origin of species can have a naturalistic explanation'. This differs from Day's gloss that the Wistar mathematicians showed evolution impossible (ROOT).\n- In support: Day (D); Wald (D2c, ruggedness).\n- Weaknesses: Eden's own estimate (D3c) for hemoglobin comes out at 2.7 million generations, 'not implausible'.",
 LIT0+"| Wistar p.7, 8, 110 | quoted above | accurate |",
 "Written before any check. Under Eden's H2 (strong regularities): a family of landscapes with local structure in which adaptive walks from random sequences reach high-fitness regions in O(L) steps. Under Eden's 'random surface': walk lengths scale as ln L (Kauffman-Levin) and end at local optima with expected rank ~1/(L+1). Result that would change a verdict: a measured distribution of path lengths or of adaptive-walk reachability on an empirical landscape (D2h).",
 "Specification: see D, step S2.","Landscape ruggedness; path-length distribution; generations available.")

d3c_day=ex('dint',"Eden then considered the specific case of hemoglobin. The alpha chain contains 141 amino acids and the beta chain contains 146 amino acids. A minimum of 120 point mutations would be required to convert alpha to beta if evolution proceeded from one chain to the other, or from a common ancestor to both, then each step along the path must have been independently viable. But the path requires traversing sequence space through intermediate forms, and Eden calculated that even under generous assumptions about mutation rates and selection coefficients, the time required to do so vastly exceeds the time available.")
write('D3c-eden-hemoglobin-2.7-million-generations','D3c','Eden calculated that hemoglobin alpha-to-beta conversion takes a time that "vastly exceeds the time available" (Day) versus 2.7 million generations, "not implausible" (Eden)','day','D','D3',
 "[{type: attacks, target: D2g},{type: depends-on, target: D3b}]",'false','D is not required for ROOT','firsthand',
 'pending','Eden\'s 2.7e6 cannot be reproduced from the printed inputs','misread','Eden\'s printed result is "a little large but not implausible"; the "vastly exceeds" conclusion appears only for the unspecified longer meandering path, for which Eden gives no estimate','contested','',
 d3c_day+f"\n\nSource: {DINT_S}, section 'The Arguments', Eden paragraph.\n\nPrimary text:\n\n"+q(E12)+f"\n\nSource: {WS}, p.8. Eden's inputs: 120 point mutations between alpha and beta by a unique path; 420 nucleotides; mutation rate 10^-6; population 10^6; 8-9 amino acids reachable per step; 20 generations to convert the population under strongest selection. He then argues the path likely meandered and gives no estimate (D3b).",
 "Eden's stated model: T = 120 * (t_wait + 20), t_wait unspecified. Tried reconstructions (this file): t_wait = 420 sites x 8.5 amino acids = 3,570 gen per step gives T = 4.3e5; with 3 nucleotide alternatives per site 1.3e6; Eden prints 2.7e6 (22,500 gen per step). The formula is not given, so the figure is not reproduced; the printed value is within a factor ~2-6 of simple reconstructions.",
 "- Stated: unique path, 8-9 reachable amino acids, mu = 1e-6, N = 1e6, strongest selection.\n- Implicit: each step requires a specific mutation to arise and sweep before the next (serial), no standing variation.",
 "- Against: Eden's own text calls the result 'a little large but not implausible'; the 'vastly exceeds' claim attaches in Eden to the (uncomputed) meandering path.\n- In support: Day's reading is that Eden's later qualitative remark (paths 'many powers of 10 greater') implies the conclusion.\n- Weaknesses: Day's rendition of residue counts (141) differs from Eden (140, 146), minor. The serial assumption is the same as the Ulam/Day 'single file' assumption (G).",
 LIT0+"| Wistar p.8 (Eden) | 2.7e6 generations 'a little large but not implausible' | accurate |",
 "Written before the reconstruction. Under Eden: 120*(t_wait+20) = 2.7e6 for t_wait ~ 2.25e4 gen. Under simple reconstructions: 4e5 to 1.3e6. The reconstruction does not reproduce the printed number; the discrepancy is under 1 order of magnitude. Result that would change a verdict: Eden's unpublished formula or a reconstruction that reaches 2.7e6.",
 "Arithmetic: `python3 -I -c \"print(120*(420*8.5+20), 120*(420*8.5*3+20))\"` -> 430,800; 1,287,600. Not committed.","Specific-step waiting time model; serial vs parallel; reachable-alternatives count (8-9 amino acids); mutation rate; N.")

# ---------------- D4 Ulam
U0=ex('W',"It appears, naIvely at least, that no matter how large the probability of a single mutation is, should it be even as great as one-half, you would get this probability raised to a millionth power, which is so very close to zero that the chances of such a chain seem to be practically nonexistent.")
U1=ex('W',"Let us assume that we have 1011 individuals. Each lives one day and let us say that the chance of a favorable mutation or \"improvement\" is 10- 10 per individual.")
U2=ex('W',"y is, of course, a small number and with a tiny advantage given by this one improvement, let us say y is 10- 6 , it will take about 106 generations before most of the population is endowed with this improvement.")
U3=ex('W',"In 10 6 generations, most of the population will have this advantage even with this small value of y. In 10 7 generations, say, almost all individuals will have it. Now, remember that we want not just one improvement but, say, 106 in succession. So we need about, say, 10 13 generations and not much more.")
U4=ex('W',"Of course it could mean that I am taking such naive schemes too seriously.")
write('D4-ulam-sequential-improvements-10-to-13-generations','D4','Ulam: 10^6 successive improvements each needing ~10^7 generations to spread requires about 10^13 generations','literature','D','D',
 "[{type: supports, target: D},{type: depends-on, target: D4b}]",'false','D is not required for ROOT; this is the historical precursor of the serial-sweep rate argument (branch A/G)','firsthand',
 'holds','arithmetic reproduces to order of magnitude (logistic: 2.3e7 per sweep, 2.3e13 total) given the serial assumption','n/a','Ulam\'s own claims; Day\'s ch.6 description ("a sequence of ten improvements") differs from the printed 10^6','contested','serial assumption and gamma = 1e-6 are disputed in the volume (Mayr, p.24)',
 q(U1)+"\n\n"+q(U2)+"\n\n"+q(U3)+f"\n\nSource: Ulam, 'How to Formulate Mathematically Problems of Rate of Evolution?', in {WP}, p.24. OCR: '1011' = 10^11, '10- 10' = 10^-10, '106' = 10^6, 'y' = gamma. The same page contains Ulam's remark: "+q(U4)+" (p.24).\n\nDay's chapter 6 summary of Ulam: 'Suppose evolution requires a sequence of ten improvements ... Ulam worked through the arithmetic and showed that even under optimistic assumptions, the time required grows rapidly.' (see "+DINT_S+").",
 "Ulam's scheme (p.24): population M = 1e11, generation = 1 day; favourable-mutation probability alpha = 1e-10 per individual, so 10 carriers per generation (p0 = 1e-10); advantage gamma = 1e-6 (offspring 1 + gamma). Time for the improvement to spread: Ulam: ~10^6 generations to 'most', ~10^7 to 'almost all'; for n = 10^6 improvements in succession: ~10^13 generations. Recomputed (deterministic logistic): t(p0 -> 0.5) = ln(1e10)/gamma = **2.30e7** generations; t(p0 -> 0.99) = **2.76e7**; times 1e6 = **2.3-2.8e13**. Ulam's '10^6 to most' understates the logistic result by 23x; his '10^7 for almost all' understates by 2.8x; his total 10^13 is within a factor of 2-3. Time available in the scheme: 'one billion years' x 365.25 = 3.65e11 one-day generations; shortfall 10^13/3.65e11 = 27x (2.3e13: 63x).",
 "- Stated: single-locus-at-a-time ('specific loci which determine the eye'), improvements 'in succession', each must spread through the population before the next; gamma and alpha are unknown, 'to give you some numbers'.\n- Implicit: no simultaneous sweeps (disputed by Mayr, 'Couldn't they all go on simultaneously?', Ulam: 'extremely unlikely'); no recombination between loci; genic selection; the 10^6 count of required improvements.\n- Ulam disclaims: 'not to put any credence whatsoever on the value of these parameters' (p.22) and 'it could mean that I am taking such naive schemes too seriously' (p.24).",
 "- Against: Mayr (D4b): gamma is 'really quite unreasonable'; 'very often a mutant has a 30 percent advantage'; improvements can proceed simultaneously. Wald: 'You have exaggerated the difficulties, so your argument is going to be a minimum' (p.24). Levins (p.24): 'Why don't we challenge the model after we disagree with the results?'.\n- In support: Day (D2a, ch.6); the serial sweep model is the ancestor of MITTENS (A): same structure with gamma replaced by measured G_f.\n- Weaknesses: the argument is wholly conditional on serial sweeps; the disagreement is the same as branch G (serial vs parallel).",
 LIT0+"| Wistar p.24 | quoted above | primary |",
 "Written before the Ulam simulation spec. Under Ulam's model (serial): total time T = n * t_sweep(gamma, N, alpha) with t_sweep ~ ln(1/p0)/gamma. Under the opposing model (Mayr): improvements at different loci proceed simultaneously; total time ~ t_sweep + waiting for the last arrival, with total mutation supply across 10^6 loci of order 10^7 carriers per generation if alpha applies per locus (Ulam's alpha is 'per individual' for 'an improvement'; whether it applies to each of 10^6 loci is ambiguous in the text, Medawar asks 'In one locus?', Ulam: 'specific loci'). Result that would change a verdict: a WF simulation of n loci with independent sweeps at gamma = 1e-6, M = 1e11 (scaled) showing whether the completion time is ~n*t_sweep (serial) or ~t_sweep*(1 + small) (parallel).",
 "Specification (later module): scaled WF with n in {10,100,1000} loci, gamma scaled, tracks completion time; compares serial prediction n*t_sweep with parallel max; checks Hill-Robertson interference at gamma*M scales. Arithmetic done: `python3 -I -c \"import math;print(math.log(1e10)/1e-6, math.log(1e10*99)/1e-6)\"` -> 2.30e7, 2.76e7. (Scratch.)","Population size M; generations per day; alpha (per locus vs per individual); gamma; number of loci n; serial/parallel switch; recombination rate.")

U5=ex('W',"But, I believe that the comments of Professor Eden, in the first five minutes of his talk at least, refer to a random construction of such molecules and even those of us who are in the majority here, the non-mathematicians, realize that this is not the problem at all.")
U6=ex('W',"A mathematical treatment of evolution, if it is to be formulated at all, no matter how crudely, must include the mechanism of the advantages that single mutations bring about and the process of how these advantages, no matter how slight, serve to sieve out parts of the population, which then get additional advantages. It is the process of selection which might produce the more complicated organisms that exist today.")
write('D4a-ulam-random-construction-is-not-the-problem','D4a','Ulam: Eden\'s first minutes concern random construction of molecules, "this is not the problem at all"; a mathematical treatment must include selection','literature','D','D4',
 "[{type: attacks, target: D3},{type: attacks, target: D}]",'false','D is not required for ROOT','firsthand',
 'holds','Ulam\'s sentence supports the critics\' reading that the random-assembly size comparison is not the right model','accurate','the quote as used by Rosenhouse (via Day) matches p.21','contested','Eden replied that Wright\'s analogue misunderstood his path-length argument; Ulam then does a rate calculation that he says illustrates what Eden had in mind',
 q(U5)+"\n\n"+q(U6)+f"\n\nSource: Ulam, in {WP}, p.21 (both sentences; the first is the start of the talk's discussion of Eden). Context sentence immediately before: "+q(U0)+" — Ulam presents that chain-probability argument as naive; he then says it is not the problem.\n\nDay's account of this passage ({BIs} — in Best They've Got I): 'But the transcript shows Ulam was agreeing with Eden's broader point while noting that the first five minutes of Eden's talk addressed a preliminary issue that was not the central problem.'".replace("{BIs}","The Best They've Got I, 2026-10-05"),
 "Ulam's logical position: (i) the product-of-probabilities chain argument ('probability raised to a millionth power ... practically nonexistent') is naive (his word); (ii) the random-construction framing of Eden's opening is 'not the problem'; (iii) a mathematical treatment must include the mechanism of advantage and selection; (iv) his own rate calculation (D4) then shows a time problem. In notation: Ulam rejects `P(random assembly) = A^-L` and the multiplicative chain `p^n` as models, and replaces them with a rate model T = n * t_sweep.",
 "- Stated: selection must be included.\n- Implicit: the rate model is the right quantity (not the probability of assembly).",
 "- Against: Day: Ulam 'agreed with Eden's broader point' (D2a); the text is compatible (his rate calc 'is illustrating something that I think Professor Eden had in mind', p.24). Day's reading of Rosenhouse's use of this quote as showing Ulam 'criticising Eden' is correct only for the random-construction framing.\n- In support: Rosenhouse (via Day); Wright (D6).\n- Weaknesses: it is notable that Day's own papers also use a product-of-probabilities argument (the Bernoulli Barrier 10^-47,262 and the Spetner chain D7a, which Day calls correct), i.e. the reading of Ulam (i) that 'the chain argument is naive' is in tension with D7a.",
 LIT0+"| Wistar p.21 (Ulam) | quoted above | accurate |",
 "No separate check (textual).","Textual audit, p.21.","None.")

# ---------------- D4b
M1=ex('W',"DR. MAYR: This gamma you chose is really quite unreasonable. Fisher and Wright also took extremely low gammas when they started; but the recent work indicates that very often a mutant has a 30 percent advantage-in other words, up to 70 percent advantage.")
M2=ex('W',"DR. MAYR: Couldn't they all go on simultaneously? DR. ULAM: This is extremely unlikely. DR. MAYR: No, no. DR. ULAM: Look, there will be only ten individuals which received an improvement in one generation.")
M3=ex('W',"DR. WALD: It is very good. You have exaggerated the difficulties, so your argument is going to be a minimum.")
write('D4b-mayr-gamma-unreasonable-and-simultaneous','D4b','Mayr and Wald on Ulam: gamma = 1e-6 is unreasonably low (mutants often have a 30 percent advantage); improvements can go on simultaneously','literature','D','D4',
 "[{type: attacks, target: D4}]",'false','D is not required for ROOT','firsthand',
 'n/a','','n/a','the claims are Mayr\'s; no citation is given at the symposium for the 30 percent figure','contested','the empirical distribution of selection coefficients is the question (cf. A4, Zeng 2021 in the fidelity ledger)',
 q(M1)+"\n\n"+q(M2)+"\n\n"+q(M3)+f"\n\nSource: discussion following Ulam, in {WP}, p.24 (Mayr, Ulam, Wald).",
 "Mayr: gamma ~ 0.3 (not 1e-6); with Ulam's M = 1e11 and p0 = 1e-10, t_sweep = ln(1e10)/0.3 = 77 generations (recomputed 76.8), so 10^6 serial improvements need 7.7e7 generations (7.7e7 < 3.65e11 available one-day generations). Simultaneity: if improvements at different loci proceed in parallel, T ~ t_sweep (+ waiting), independent of n up to interference limits.",
 "- Stated: recent work indicates mutants often have large advantages; simultaneous sweeps are possible.\n- Implicit: gamma is a typical rather than a selected-for (survivorship-biased) value; the 30 percent comes from cases where the mutant 'gets incorporated', i.e. observed substitutions are selected for being large.",
 "- Against: Ulam (p.24): simultaneous sweeps 'extremely unlikely' because only ten individuals carry the improvement per generation; Day (blog 2025-12-27, 'Hardcoded'; 2026-09-30) argues the average rate is indifferent to parallel vs serial (G1).\n- In support: Wald: Ulam's numbers are a minimum difficulty.\n- Weaknesses: both gamma values are assertions at the symposium. Mayr's 30% is an upward-selected value (substitutions observed because they were large), the same reasoning applied by critics to Day's Zeng 2021 s = 0.001 (fidelity ledger).",
 LIT0+"| Wistar p.24 | quoted above | primary |",
 "Written before the Ulam simulation. Under Mayr: completion time ~ 77 + small for parallel sweeps at gamma = 0.3. Under Ulam: ~10^13 for gamma = 1e-6 serial. These do not conflict: they differ in gamma by 3e5. A check can distinguish only the serial-vs-parallel question at fixed gamma (see D4).",
 "See D4 (specification only).","gamma distribution (including survivorship-biased tail); simultaneity switch.")

# ---------------- D5 Schutzenberger
S1=ex('W',"I intend to restrict my argument to show the existence of a serious gap in the current theory of evolution.")
S2=ex('W',"Thus, to conclude, we believe that there is a considerable gap in the neo-Darwinian theory of evolution, and we believe this gap to be of such a nature that it cannot be bridged within the current conception of biology.")
S3=ex('W',"Their experience is quite conclusive to most of the observers: without some built-in matching, nothing interesting can occur.")
S4=ex('W',"We do not know any general principle which would explain how to match blueprints viewed as typographic objects and the things they are supposed to control.")
S5=ex('W',"Further, there is no chance « I 0-1.000) to see this mechanism appear spontaneously and, if it did, even less for it to remain.")
S6=ex('W',"I mean less than one out")
S7=ex('W',"of 10100")
bi5=ex('b:2026-10-05-the-best-theyve-got-i',"concluded that “there is a considerable gap in the neo-Darwinian theory of evolution, and we believe that this gap cannot be bridged within the current conception of biology.”")
write('D5-schutzenberger-gap-between-typographic-and-functional-space','D5','Schützenberger: there is a considerable gap in neo-Darwinian theory, between the space of sequences and the space of organisms, which cannot be bridged within current biology','literature','D','D',
 "[{type: supports, target: D},{type: attacks, target: D1b}]",'false','D is not required for ROOT','firsthand',
 'pending','a conceptual argument (matching between spaces), not a calculation; internal validity depends on whether evolution can generate the matching','partial','Day\'s Best I quotation alters the wording ("we believe that this gap cannot be bridged" vs "we believe this gap to be of such a nature that it cannot be bridged")','contested','Lewontin, Waddington, Levins, Fraser replied at pp.76-80',
 q(S1)+"\n\n"+q(S2)+f"\n\nSource: Schützenberger, 'Algorithms and the Neo-Darwinian Theory of Evolution', in {WP}, p.73 and p.75.\n\n"+q(S3)+"\n\n"+q(S4)+"\n\nSource: same, p.75.\n\nDay's rendering:\n\n"+q(bi5)+f"\n\nSource: The Best They've Got I, 2026-10-05, para {para('b:2026-10-05-the-best-theyve-got-i','concluded that')} (the quotation marks enclose a paraphrase; the printed sentence is above).",
 "Schützenberger's structure: three spaces (typographic/genotype, phenotype/function, parameter/epigenetic), with relations between them given only by assumptions (his words: 'a topology'); the claim is that no principle is known that matches typographic proximity to functional proximity; programs written by random typographic changes do not compute; artificial-intelligence experience says 'without some built-in matching, nothing interesting can occur'. The probabilistic figures (D5a) are illustrative.",
 "- Stated: the gap exists and the matching mechanism is unknown; 'I intend to restrict my argument to show the existence of a serious gap'.\n- Implicit: random typographic changes are the only variation process; the matching cannot be itself produced by selection (the 'Ashby trap', p.79).",
 "- Against: Lewontin (p.76, p.79): known cases where single amino-acid changes alter but do not destroy enzymes; Levins (p.79): 'its topology is, itself, a product of evolution'; Waddington (p.78): typographic errors are absorbed by the logic of paragraphs; Fraser (p.80): a genetic system with multiple pathways reaches rational information fast; Ulam (p.76) replies that Darwinian theory is admittedly incomplete, which he says is not an objection to the scheme (paraphrase; the OCR interleaves two columns there).\n- In support: Day (D, D2); Rosenhouse's 'Kansas vs New Jersey' reply (via Day) is a rebuttal at the codon level only (D2 context).\n- Weaknesses: Schützenberger asks for a mechanism and a general principle; neither side supplies a measurement. This is the same open item as D2h. Fraser's and Lewontin's replies are descriptive. Schützenberger himself says (p.73) that his restricted aim is the 'existence of a serious gap'.",
 LIT0+"| Wistar p.76 (Ulam) | quoted in Responses | primary |",
 "Written before any check. Under the claimant: on empirically measured landscapes, adaptive walks without a pre-built matching reach high-fitness sequences rarely. Under the opposing model: they reach them readily when single-substitution neighbors are mostly functional. Result that would change a verdict: the p(neighbor functional) estimate (D2h).",
 "Specification: D, step S2/S3.","Genotype-phenotype map smoothness; epigenetic-parameter space.")

write('D5a-schutzenberger-probability-figures-1e-100-1e-1000','D5a','Schützenberger: typographic changes that preserve meaning are less than one in 10^100; no chance (< 10^-1000) for a self-correcting mechanism to appear spontaneously','literature','D','D5',
 "[{type: depends-on, target: D5}]",'false','D is not required for ROOT','firsthand',
 'pending','no derivation is given in the volume','accurate','the OCR text is two-column interleaved; the numbers are as read below','untestable','the figures concern a hypothetical class of programs, not a measured biological quantity',
 q(S5)+f"\n\nSource: Schützenberger, in {WP}, p.75 (OCR: '« I 0-1.000)' read as '< 10^-1000').\n\n'"+S6+"' ... '"+S7+"' (OCR: 'less than one out ... of 10100 •')\n\nSource: same, p.76, discussion (column-interleaved in the OCR; the words 'I mean less than one out' and 'of 10100' are separated by another speaker's column).",
 "Two assertions: P(a random typographic change preserves 'meaningful' function) < 10^-100 (for programs/meaningfulness in his sense); P(the self-correcting mechanism appears spontaneously) < 10^-1000. Neither is derived in the text; on p.73 he says the cycle numbers are quoted from other speakers ('From their talks it is clear that even on the most schematic models the number of cycles involved is truly enormous').",
 "- Stated: the figures are illustrative upper bounds for a class of systems.\n- Implicit: the system is computationally universal and biology resembles it (disputed by Waddington, p.77).",
 "- Against: Waddington: 'All proteins do something, so all changes in the program level have meaning' (p.79); Lewontin (p.79).\n- In support: Day (D5).\n- Weaknesses: the numbers are asserted; Day's own Bernoulli figures (10^-47,262; 10^-34,000,000) have the same status (asserted products, G).",
 LIT0+"| Wistar pp.73-76 | quoted above | primary |",
 "No check (no formula to test). Recorded for completeness; a 'asserted, not derived' tag applies.","None.","None.")

# ---------------- D6 Wright
W1=ex('W',"Natural selection may appear to be a vacuous and tautological principle if only a single step is considered, but considered over a long succession of little steps, it is the only guiding principle that has stood up under experiment. Eden refers to the 10 350 proteins, each consisting of 250 amino acids. He seems to imply that it would require something like this number of operations of natural selection to arrive at a particular useful one. On the principle of the children's game of twenty questions in which it is possible to arrive at the correct one of about a million objects by a succession of 20 yes-orono answers, it would require less than 1250 questions to arrive at a specified one of these proteins. While this is not a perfect analogy to natural selection, it is enormously more like natural selection than the typing at random of a library of 1,000 volumes with its infinitesimal chance of arriving at any sensible result.")
dice=ex('b:2024-07-13-evolutionists-are-retarded',"The previous die has no effect on the subsequent one and there is no cumulative result.")
write('D6-wright-twenty-questions-1250','D6','Wright: by the principle of twenty questions, fewer than 1250 steps suffice to reach a specified 250-residue protein; this is closer to natural selection than random typing','literature','D','D',
 "[{type: attacks, target: D3},{type: attacks, target: D}]",'false','D is not required for ROOT','firsthand',
 'holds','250 x 5 = 1250 >= log2(20^250) = 1080.5 bits; the analogy is internally valid as a statement about information per selected step','n/a','Wright\'s own words; page is 117 (Day-adjacent sources and the task cite 118)','contested','needs a per-step fitness signal; Eden replied (p.8) that Wright misunderstood his path-length argument',
 q(W1)+f"\n\nSource: Sewall Wright, 'Comments on the Preliminary Working Papers of Eden and Waddington', in {WP}, p.117 (first page of Wright's comments; the PDF text layer prints folio 117 at the foot and the book's index lists 'twenty questions' at pp.8 and 117; the label 'p.118' in earlier notes is one page too high). OCR: 'yes-orono' = 'yes-or-no'; '10 350' = 10^350 (the figure in Eden's working paper, D3, not the 10^325 of the talk).\n\nEden's reply, p.8: "+q(E10)+"\n\nDay's rebuttal (quoting Wright in the same post): "+q(dice)+"\n\nSource: [Evolutionists are Retarded](https://voxday.net/2024/07/13/evolutionists-are-retarded/), 2024-07-13, para "+str(para('b:2024-07-13-evolutionists-are-retarded','The previous die has no effect'))+".",
 "Information bound: identifying one of 20^250 sequences needs log2(20^250) = 250*log2(20) = 1080.5 bits, i.e. at most 1080.5 binary questions when each answer is an independent bit; Wright's 1250 = 250 residues x 5 questions per residue (5 > log2 20 = 4.32). Each question must be answered by an oracle that retains the result: in selection terms, a per-step fitness signal that keeps correct choices. Day's dice reply is correct for independent unretained trials; Wright's analogy is explicitly of retained answers.",
 "- Stated: the analogy is 'not a perfect analogy to natural selection'.\n- Implicit: an environment answers each question (fitness differences exist at each residue), and the answers are independent per residue.",
 "- Against: Eden (D3b, p.8): path-length is the issue; Day: dice have no cumulative effect (applies to unretained trials); Day D2i: designed fitness functions.\n- In support: Rosenhouse (D1); Day concedes selection is the reply by labelling it 'cumulative selection' and arguing it is not 'massively parallel fixation' (G).\n- Weaknesses: the analogy establishes only that large spaces can be searched in ~log steps when an oracle exists; the existence and smoothness of the oracle is D2h.",
 LIT0+"| Wistar p.117 | quoted above | primary |",
 "Written before the arithmetic. Under Wright: 250*log2(20) < 1250. Under Eden: the relevant quantity is path length on the fitness surface, not the information bound. Result that would change a verdict: none for the arithmetic; for the analogy, D2h.",
 "S1 (done): `python3 -I -c \"import math;print(250*5, 250*math.log2(20))\"` -> 1250, 1080.5. Reconciles.","Per-residue fitness signal availability; oracle noise; number of generations per retained bit.")
