import sys; sys.path.insert(0,os.environ.get("EVO_WORK","work")+"")
from gen_lib import *
BI='b:2026-10-05-the-best-theyve-got-i'; BII='b:2026-10-06-the-best-theyve-got-ii'
BIs="[The Best They've Got I](https://voxday.net/2026/10/05/the-best-theyve-got-i/), 2026-10-05, voxday.net"
BIIs="[The Best They've Got II](https://voxday.net/2026/10/06/the-best-theyve-got-ii/), 2026-10-06, voxday.net"
WP="Moorhead & Kaplan (eds), *Mathematical Challenges to the Neo-Darwinian Interpretation of Evolution*, Wistar Institute Monograph No. 5 (1967; symposium 25-26 Apr 1966), local copy = 1985 Liss reprint scan, OCR text; page = printed folio (OCR garbles noted in place)"
def bi(a,b=None): return ex(BI,a,b)
def pb(a): return para(BI,a)
def pbii(a): return para(BII,a)
LIT0="| Cited work | What it actually says (quote) | Fidelity |\n|---|---|---|\n"
OCRNOTE="OCR renders superscripts inline (e.g. 20^250 as '20250', 10^325 as '10 325')."
# ---------- D
d_q1=bi("Eden had already shown this: the space of 250-residue proteins is ~10^325, and the number of functional proteins that have ever existed is ~10^52.")
DINT_S="[Vox Day Interview on Evolutionary Theory](https://billdembski.substack.com/p/vox-day-interview-on-evolutionary) (Dembski Substack), 2026-09-28, appended chapter 'From Probability Zero (2nd ed.) on 1966 Wistar Symposium, Chapter 6: The 1966 Meeting of the Minds' (posted with Day's permission; primary Day text)"
d_c6a=ex('dint',"The biologists did not answer the mathematicians. They could not.")
d_c6b=ex('dint',"But the space of possible genetic sequences is unimaginably vast, the proportion of functional sequences within that space is vanishingly small, and the time available for the process to take place is insufficient for random search to find what needs to be found.")
d_c6c=ex('dint',"There is not one single example of a biologist producing one single calculation that even attempts to contradict the mathematicians’ conclusions.")
d_q2=bi("Eden calculated the size of sequence space. No one calculated a smaller space. Ulam calculated a rate. No one calculated a faster rate. Schützenberger asked for a mechanism. No one demonstrated one.")
write('D-sequence-space-wistar','D','Functional proteins are a vanishing fraction of sequence space (about 1e52 proteins ever vs 1e325 sequences), and the Wistar challenge was never answered quantitatively','day','D','ROOT',
 "[{type: supports, target: ROOT},{type: depends-on, target: D3},{type: depends-on, target: D4},{type: depends-on, target: D5},{type: depends-on, target: D2g},{type: attacks, target: D1}]",
 'false','ROOT has independent routes (A, B, G); D is a separate sequence-space route and a historical-priority claim; ROOT does not require D',
 'firsthand','pending','conclusion (evolution cannot search the space) needs a landscape-structure premise that D does not state','partial','Eden\'s 20^250 reproduces; Eden\'s 10^52 counts protein molecules, not functional proteins; Waddington conceded the minute-fraction premise','contested','functional-fraction estimates differ by ~53 orders of magnitude (Axe vs Taylor) and landscape structure is disputed',
 d_q1+f"\n\nSource: {BIs}, para {pb('Eden had already shown this')} of extracted text (Day's summary of Eden; the blog attributes the 10^325 and 10^52 to Eden).\n\n"+d_q2+f"\n\nSource: same, para {pb('Eden calculated the size of sequence space')}.\n\n"+q(d_c6b)+"\n\n"+q(d_c6a)+"\n\n"+q(d_c6c)+"\n\nSource for the three quotations above: "+DINT_S+". The chapter is Day's own fullest statement of D in the corpus (first-edition text not retrieved; the 2nd edition may differ).\n\nThe primary source for the two numbers is Eden, Wistar p.7 (see D3).",
 """Let L = 250, A = 20. Sequence space `S = A^L = 10^(250*log10 20) = 10^325.257`. Eden's upper bound on protein molecules that ever existed on Earth: `N_ever = 10^52` (Wistar p.7). Ratio `N_ever/S = 10^-273.3`.

D as Day uses it has two parts: (1) a size comparison S >> N_ever (arithmetic); (2) the historical claim that no Wistar biologist produced a counter-calculation (D2g). The step from (1) to 'evolution cannot work' is not in the sentence quoted; Eden states it needs one of two hypotheses (D3b): either functional proteins are common, or the topology of the space provides paths. Day adds the second horn: functional proteins are isolated (rugged landscape), citing Wald (D2c) and deep mutational scanning (D2h, unsourced). Derived expected-hit calculations (this file): hits = N_ever * f for fraction f functional; f = 1e-77 (Axe 2004, one beta-lactamase-type domain, any fold) gives 1e-25; f = 2e-24 (Taylor 2001, derived from the 5e23 library estimate for a 100-residue chorismate mutase) gives 2e28. These are different proteins and different lengths and are not comparable; they are shown only to display the spread.""",
 """- Stated (Day): sequence space is searched by variation plus selection; functional proteins are rare; no biologist at Wistar produced a quantitative reply.
- Implicit: (i) the relevant search is for novel protein folds or de novo functions, whereas the human-chimpanzee divergence that anchors ROOT is mostly 35M single-nucleotide differences; the link between D and A-H is not made in the retrieved text; (ii) the landscape is rugged (isolated functional islands); (iii) numbers for the number of molecules, not distinct sequences, set the exploration budget; (iv) no reuse of existing domains.
- Implicit in Eden: the explored part of the space is 'all useful proteins which have existed to date' (p.7), i.e. the set has been used, not just sampled.""",
 """- Against: Wright (D6, Wistar p.117): selection makes the search ~log, not linear; Eden replied (p.8) that Wright had misunderstood the argument and that path length is the issue. Ulam (D4a, p.21): random construction 'is not the problem'. Waddington (p.93, D2e): the part explored is 'quite large in comparison with all the things that could conceivably be made out of it in single steps', while granting the meaningful space is 'a minute fraction of the total nucleotide space'. Rosenhouse (D1; ch.4; secondhand). Camestros (D1d). Taylor 2001 and Keefe & Szostak 2001 measured functional frequencies in random libraries (D11, D12).
- In support: Wald (p.19, D2c): changes in hemoglobin rarely leave function untouched; Schützenberger (D5): a 'gap' between sequence space and organism space; Axe 2004 (D10): 1 in 10^77.
- Weaknesses in the responses: Wright's analogy is explicitly 'not a perfect analogy' and needs a fitness signal at each step; Waddington's and Lewontin's claims are assertions (no data at the symposium). On the Day side: Day's reading of Wistar silence ('No one calculated a smaller space') is contradicted in part: Wright p.117 gives a calculation (1250 questions) and p.119 gives a mutation-supply figure (D2g); and the 10^52 figure counts molecules, not functional proteins (D3a). Day's own chapter 6 (2nd ed., Dembski Substack) also contains quotations or attributions that do not match the volume: Lewontin's 'quasi-continuity ... I don't know' exchange and the Levins/Lewontin attribution (D2b), Mayr's 'The very fact that we have this conference' (D2f), a Bossert remark attributed to Eden (D2j), Eden's biosphere inputs (D3a) and Eden's hemoglobin result ('vastly exceeds' vs 'not implausible', D3c). These affect the fidelity of the historical half of D, not the arithmetic.""",
 LIT0+"| Eden (Wistar p.7) | 20^250 = 10^325; molecules ever = 10^52; 'species of protein molecules ... say 10^40' | accurate numbers; wording differs from Day's 'functional proteins' (partial) |\n| Waddington (Wistar p.93) | meaningful space 'a minute fraction of the total nucleotide space' | accurate; Day omits this concession (D2e) |\n| Axe 2004 (abstract) | 'roughly one in 10(64) signature-consistent sequences'; 'as low as 1 in 10(77)' | accurate (abstract only) |\n| Taylor 2001 | ~5e23 library needed for chorismate mutase in a fully randomized 100-mer | accurate (D11) |\n| Keefe & Szostak 2001 (abstract) | four ATP-binding proteins from 6e12 random 80-mers; frequency 'similar to ... RNA libraries' | abstract only (D12) |",
 """Written before the S1/S2 checks below.
- Under the claimant's model (rugged, isolated functional islands): in NK-type landscapes with high K, adaptive walks from random starts terminate at local optima well below the global optimum and the fraction of reachable high-fitness sequences from a random start collapses with N; reaching function from random sequences scales like 1/f.
- Under the opposing model (connected neutral/near-neutral networks, low effective K): walks reach the high-fitness plateau in O(L) to O(L ln L) steps for K small; reachability is high for starts within the connected network.
- What both sides already agree on (theorems, not predictions): K = 0 -> single peak, walk length ~L/2; K = L-1 (uncorrelated) -> walks end at local optima of expected rank ~1/(L+1) and take ~ln L steps (Kauffman-Levin 1987). The NK model therefore cannot adjudicate the empirical question of real-protein K; it can only map which ruggedness Eden's/Day's conclusion requires.
- Result that would change a verdict: an empirical estimate of K (or of the fraction of single-step neighbors of a functional protein that remain functional) from deep mutational scanning data would move D's external verdict: if p(neighbor functional) is high (> ~30%) and landscapes percolate, D's inference is contradicted; if low and non-percolating, supported.""",
 """S1 (arithmetic, done): `python3 -I -c "import math;print(250*math.log10(20), 10**((250*math.log10(20))%1))"` -> 325.257, 1.81; so 20^250 = 1.81e325. 10^325 - 10^52 gap: 273 orders. Reconciles.
S2 (NK reachability, exploratory): **specification only** (Branch D simulations are a separate later module). Alphabet 4 (nucleotides) and 20 (amino acids) variants; L in {10,16,24}; K in {0,1,2,4,8,L-1}; random-neighbor and adjacent epistasis; measure walk length, final fitness percentile, fraction of starts reaching top 1%, and generations under WF with N=1e4, s derived from fitness differences. Output: reachability vs K. Not decisive for real proteins.
S3 (data-based): estimate p(single-substitution neighbor functional) from published deep mutational scans (not in corpus; to be harvested).""",
 "Alphabet size A; sequence length L; epistasis K; functional threshold/fraction f; population size N and s (to convert fitness differences to generations); mutation supply u; neutral-network connectivity; domain reuse switch (de novo vs recombination of existing modules).")

# ---------- D1 family
ro1=ex('qc',"The Legacy of the Wistar Conference. Using the 1966 conference called by some mathematical critics of evolutionary biology, explains why their critiques were refuted, and how present-day creationists misrepresent what was said at that conference.")
ro2=ex('qc',"Information and Combinatorial Search. Information theory, claims that random mutations always decrease the information content of biological systems. Protein space. Dawkins' Weasel. The No Free Lunch Theorem.")
write('D1-rosenhouse-wistar-critiques-refuted','D1','Rosenhouse ch.4: the Wistar mathematicians\' critiques were refuted and present-day creationists misrepresent them','critic','D','D',
 "[{type: attacks, target: D}]",'false','D is not a premise of ROOT','secondhand',
 'pending','book not accessed','unverifiable','only Felsenstein\'s chapter summary seen','contested','depends on D2/D2g checks',
 ro1+"\n\nSource: Joe Felsenstein, [Jason Rosenhouse's book on mathematical anti-evolutionism is available](https://pandasthumb.org/archives/2022/05/rosenhouse-on-mathematical-anti-evolutionism.html), Panda's Thumb, 2022-05-18, annotated table of contents, chapter 4 entry (quotes-critics RO-01). `secondhand`: Felsenstein describing Rosenhouse, *The Failures of Mathematical Anti-Evolutionism* (Cambridge UP, 2022). Felsenstein states he commented on the manuscript and wrote a blurb (opponents/jason-rosenhouse.md).",
 "Claim form: for each Wistar mathematical challenge C in {Eden, Ulam, Schützenberger}, a biologist reply R exists at or after Wistar with R rebutting C. Plus a secondary claim about the modern creationist use of Wistar.",
 "- Stated: the critiques were refuted.\n- Implicit: refutation includes both the contemporaneous replies (Wright, Lewontin, Waddington, Mayr) and later molecular biology and computer science (p.124, D1a/D1b).",
 "- Against: Day (D2, D2a-D2i): contemporaneous replies were qualitative; ch.4 provides no quantitative refutation. Camestros says Day does not discuss developments after 1966 (D1d), which is the opposite complaint.\n- In support: Wistar text itself (Wright p.117; Lewontin pp.76-78, 92-93; Waddington p.78, p.93; Mayr p.30).\n- Weaknesses: Rosenhouse's book was not accessed; both Day's reading of it (via his quotes) and Felsenstein's summary are secondhand. Rosenhouse predates Probability Zero (2022 vs 2026) and Day's MITTENS; it cannot be a reply to the fixation arguments (branches A-H except D).",
 LIT0+"| Wistar 1967 | see D2a-D2i, D4-D6 | per claim |",
 "Written before any check. Under the claimant's model (Rosenhouse): the Wistar replies include at least one calculation or published measurement that contradicts each mathematician's conclusion. Under the opposing model (Day): none contradicts a conclusion quantitatively. Result that would change a verdict: a numeric reply in the transcript that bears on Eden's path-length argument or Ulam's serial-sweep time (Wright's 1250-question bound addresses only Eden's 'random assembly' reading, D6).",
 "No script: textual audit of the Wistar volume (D2a-D2i, D4, D5, D6).","None.")

d1a=bi("Molecular biology and computer science were both in a very rudimentary state","look hopelessly naive.”") if False else ex(BII,"Molecular biology and computer science were both in a very rudimentary state when the conference was held in 1966.","look hopelessly naive.”")
write('D1a-rosenhouse-eden-naive-combinatorics','D1a','Rosenhouse p.124: molecular biologists learned the geometry of protein space and it makes Eden\'s combinatorial calculations look hopelessly naive','critic','D','D1',
 "[{type: attacks, target: D3},{type: attacks, target: D}]",'false','D is not required for ROOT','secondhand',
 'pending','no argument visible in the quoted paragraph','unverifiable','book not accessed; quote is Day\'s transcription','contested','contradictory literature estimates and Day\'s unsourced DMS claim (D2h)',
 d1a+f"\n\nSource: Rosenhouse, *The Failures of Mathematical Anti-Evolutionism*, Cambridge UP 2022, p.124, as transcribed by Day in {BIIs}, para {pbii('Assertion 1')}. `secondhand` (Day's transcription, with 'ﬁ' ligatures as printed). Not independently verified against the book.",
 "A is-a claim: 'the geometrical structure of protein space (known since 1966) makes Eden's 20^250-vs-10^52 comparison irrelevant'. Equivalent to asserting that the topological hypothesis (Eden's second horn, D3b) is true.",
 "- Stated: molecular biologists 'have learned a lot about the geometrical structure of protein space'.\n- Implicit: that structure is path-connected for functional proteins; the results exist and are in ch.6 (promised 'We will discuss this work in Chapter 6', D1c).",
 "- Against: Day (D2): no citations, no quantification in the paragraph, 'either those results exist or they do not'; Day's DMS counter-claim is itself unsourced (D2h). Axe 2004 (D10) is consistent with Eden's concern for a particular fold.\n- In support: Taylor 2001 and Keefe & Szostak 2001 show functional proteins exist in random libraries at measurable frequency (D11, D12), but both also say single-step random search is infeasible for enzymes (Taylor) and neither measures connectivity.\n- Weaknesses: the paragraph is a pointer to ch.6; judging it requires ch.6.",
 LIT0+"| Taylor 2001 | 'a library of ~10^24 members would have been needed to obtain AroQ mutases' if every position were randomized | accurate; shows low density, not connectivity |",
 "Written before any check. Under the claimant (Rosenhouse): published measurements of protein-space geometry (e.g. neutral-network sizes, fraction of functional single mutants) show connectivity sufficient for selection. Under the opposing model: measured fractions of functional single mutants are low and decline with distance. Result that would change a verdict: a named study with a measured fraction of functional single-substitution neighbors (D2h).",
 "No check possible until ch.6 or the cited studies are obtained. Action: harvest ch.6 and DMS literature (neither in corpus).","Fraction of functional single-substitution neighbors; neutral network size; distance-decay of function.")

d1b=ex(BII,"Schützenberger’s arguments about computer simulations have likewise not held up, and computer simulations of the evolutionary process are now commonplace.")
write('D1b-rosenhouse-simulations-commonplace','D1b','Rosenhouse p.124: Schützenberger\'s arguments about computer simulation have not held up; simulations of evolution are commonplace','critic','D','D1',
 "[{type: attacks, target: D5}]",'false','D is not required for ROOT','secondhand',
 'pending','one-sentence assertion','unverifiable','book not accessed','contested','Day\'s reply (D2i) turns on designed fitness functions',
 d1b+f"\n\nSource: Rosenhouse 2022, p.124 (Assertion 2), via {BIIs}, para {pbii('Assertion 2')}. `secondhand`.",
 "Existence of working evolutionary computations is offered as evidence against the 'gap' between program space and function space (D5).",
 "- Stated: simulations are commonplace.\n- Implicit: simulations model the biological mapping from sequence to fitness, not merely a programmer-defined one.",
 "- Against: Day (D2i): every evolutionary algorithm has a programmer-designed fitness function, the very mapping Schützenberger said biology lacks.\n- In support: Wright's 1250-question analogy (D6) and Weasel-type demonstrations show cumulative selection works given a fitness signal.\n- Weaknesses: both sides agree on the logic: algorithm success shows what selection can do when a fitness mapping exists; it cannot by itself show biology supplies the mapping. Day's reply is therefore valid against a reading of Rosenhouse as an existence proof and does not address a reading as a plausibility argument.",
 LIT0+"| Schützenberger (Wistar p.75) | 'without some built-in matching, nothing interesting can occur' (artificial-intelligence experience) | accurate |",
 "Written before any check. Under the claimant (Rosenhouse): evolutionary computations with biologically derived fitness (e.g. protein-folding or measured-fitness landscapes) succeed. Under the opposing model: success occurs only where the designer builds in matching; with measured biological landscapes success rate falls with ruggedness. Result that would change a verdict: success of selection on an empirical, designer-independent landscape (DMS-derived).",
 "Specification: NK / DMS-derived landscapes in D, step S2 and S3. No script.","Fitness-function provenance (designed vs measured); landscape source.")

d1c=ex(BII,"The chapter ends by promising that “We will discuss this work in Chapter 6.”")
write('D1c-rosenhouse-ch6-protein-space-weasel','D1c','Rosenhouse ch.6: "Protein space. Dawkins\' Weasel. The No Free Lunch Theorem." answers the Wistar challenges','critic','D','D1',
 "[{type: attacks, target: D}]",'false','D is not required for ROOT','secondhand',
 'pending','chapter 6 not accessed','unverifiable','only the table-of-contents entry seen','contested','pending',
 ro2+"\n\nSource: Felsenstein, Panda's Thumb 2022-05-18, chapter 6 entry (quotes-critics RO-02); `secondhand`.\n\n"+d1c+f"\n\nSource: Rosenhouse 2022, end of ch.4, as quoted in {BIIs}, para {pbii('The chapter ends by promising')}; `secondhand`.",
 "Existence claim: ch.6 contains a quantitative treatment of protein-space geometry and of the Weasel program that answers Eden's and Schützenberger's challenges.",
 "- Stated: the chapter covers 'Protein space', 'Dawkins' Weasel' and 'No Free Lunch'.\n- Implicit: it answers Day's D2 complaint (no quantification in ch.4).",
 "- Against: Day (D2) promised a third post on whether ch.6 delivers; not found in the corpus (latest Day post is 2026-10-07, 'An Epic Test').\n- In support: n/a.\n- Weaknesses: unknown. Cambridge TOC and Cambridge Core pages failed to load during harvest (harvest-log-critics).",
 LIT0+"| Rosenhouse 2022 ch.6 | not retrieved | unverifiable |",
 "Not registered: nothing to check until ch.6 is read. Action item: obtain ch.6 (library copy) and extract (i) any quantification of protein space, (ii) its Weasel treatment, to be compared with D9.","None.","None.")

ca=ex('ca4',"if he was making a serious attempt to discuss maths and evolution he’d talk about what developments happened since 1966. He doesn’t.")
write('D1d-camestros-no-developments-since-1966','D1d','Camestros Felapton: a serious treatment of maths and evolution would discuss developments since 1966; Day\'s Wistar chapter does not','critic','D','D',
 "[{type: attacks, target: D}]",'false','D is not required for ROOT','firsthand',
 'n/a','observation about the book\'s coverage, not an argument','n/a','reviewer read the first edition only (opponents/camestros-felapton.md)','pending','pending (post-1966 literature is D10-D12, D1a)',
 ca+"\n\nSource: Camestros Felapton, [Reading Vox Day So You Don't Have To 2026 [4]](https://camestrosfelapton.wordpress.com/2026/01/29/reading-vox-day-so-you-dont-have-to-2026-4/), 2026-01-28/29, paragraph on chapter 6 of the first edition of Probability Zero (Wistar). The reviewer says Chapter 6 is a history of the 1966 conference.",
 "No formal content. Coverage claim: the book's D chapter omits post-1966 work.",
 "- Stated: Day should have addressed later developments.\n- Implicit: later developments (e.g. functional-frequency measurements D10-D12) bear on D.",
 "- Against: Day's rejoinder is in D2 (Best They've Got II): he says the post-1966 results Rosenhouse alludes to are not shown, and that DMS results confirm Eden (unsourced, D2h). Day does cite recent work in other chapters (Chapter 7 'The Darwillion', per the same review), but the Wistar chapter's coverage is unknown without the book.\n- In support: our corpus finds no Day citation of Axe 2004, Taylor 2001 or Keefe & Szostak 2001 in any retrieved text, which is consistent with the criticism for the retrieved material but not for the book.\n- Weaknesses: review of the 1st edition; the 2nd edition (2026-05-23) may differ. The reviewer's own disclaimer: 'I'm not a biologist, I'm not really a mathematician ...' (CA-13).",
 LIT0+"| none | | n/a |","None (no formal content). The question 'does the Day corpus cite post-1966 protein-space work' is answered by search: no hits for Axe, Taylor 2001, Keefe, 'deep mutational' with a citation in blog or Zenodo texts (see D2h).",
 "Search result only: `grep -n -E 'Axe|lactamase|Keefe|Szostak|Taylor 2001' sources/raw/day/*.txt` finds no relevant citation.","None.")

# ---------- D2
d2a=ex(BII,"But his own chapter provides no quantitative refutation of any of the three mathematical arguments provided by the biologists at the time or by anyone else since.")
d2b=ex(BII,"Eden’s sequence-space calculation stands unchallenged by any number Rosenhouse provides. Ulam’s rate calculation stands unchallenged by any rate Rosenhouse computes. Schützenberger’s formal-language argument stands unchallenged by any mechanism Rosenhouse identifies.")
d2c=ex(BII,"Rosenhouse provides no citations. He names no studies nor molecular biologists.")
write('D2-day-rosenhouse-ch4-no-quantification','D2','Rosenhouse ch.4 offers no quantitative refutation of Eden, Ulam or Schützenberger; evolutionary algorithms use designed fitness functions','day','D','D1',
 "[{type: attacks, target: D1},{type: attacks, target: D1a},{type: attacks, target: D1b},{type: depends-on, target: D2i}]",
 'false','D is not required for ROOT','firsthand',
 'pending','the complaint is conditional on ch.6 not delivering; Day has announced a third post','unverifiable','Day\'s claim about the content of ch.4 cannot be checked without the book','pending','depends on ch.6 and on D2g',
 d2a+f"\n\n"+d2b+f"\n\n"+d2c+f"\n\nSource: {BIIs}, paras {pbii('But his own chapter provides no quantitative')} and {pbii('Rosenhouse provides no citations')} of extracted text. (Day's text reads 'provided by the biologists'; context shows 'mathematicians' is meant; quoted as printed.)",
 "Claim form: Q(R) = 0 for each of three Wistar arguments, where Q counts quantitative refutations in ch.4. Plus Day's conditional: if molecular biology had shown dense stepping-stone connectivity 'that result would have a name, a date, and a journal'.",
 "- Stated: no citation, no number in Rosenhouse's p.124 paragraph.\n- Implicit: that ch.4 is the right place for the quantification (Day concedes that Rosenhouse defers to ch.6).",
 "- Against: ch.6 (D1c) not yet read; Day himself acknowledges the deferral and promises a third installment. The evidence for 'no citations' is Day's transcription of one paragraph.\n- In support: Felsenstein's summary of ch.4 lists no quantitative content (RO-01).\n- Weaknesses: Day's own counter-assertions in the same post (deep mutational scanning shows rugged landscapes; D2h) carry no citations either, which is the same defect he alleges.",
 LIT0+"| Rosenhouse 2022 ch.4 | not retrieved | unverifiable |",
 "Written before any check. Under the claimant (Day): ch.6 contains no numerical bound on reachability of function in sequence space and no Wistar-specific numbers. Under the opposing model: ch.6 gives quantitative protein-space results and a Weasel analysis. Result that would change a verdict: ch.6 content.",
 "Pending ch.6.","None.")

d2ai=bi("Ulam explicitly states: “What I am going to do will come to Eden’s conclusions.”")
d2aii=bi("He also says, in the discussion, “In contrast to the tone of the discussion I took, personally, I believe that the numbers I took are very optimistic”—meaning he believes the real situation for neo-Darwinism is worse than his model suggests")
u1=ex('W',"will not come to be as fantastically small as in Professor"); u2=ex('W',"Eden's conclusions; but we will come to that later.")
u3=ex('W',"This calculation is illustrating something that I think Professor Eden had in mind.")
u4=ex('W',"In contrast to the tone of the discussion I, personally, believe that the numbers I took are very optimistic rather than the opposite.")
write('D2a-day-ulam-sides-with-eden','D2a','Ulam: "What I am going to do will come to Eden\'s conclusions"; Ulam is an ally of Eden, not of the biologists','day','D','D2',
 "[{type: attacks, target: D4a},{type: depends-on, target: D4}]",'false','D is not required for ROOT','firsthand',
 'n/a','fidelity question first','partial','quoted sentence not found; nearest text says the opposite about magnitude; substance (Ulam finds the rate problem real) supported at pp.24-25','contested','',
 d2ai+"\n\n"+d2aii+f"\n\nSource: {BIs}, para {pb('Ulam explicitly states')}, Day's quotations of the Wistar transcript.\n\nWhat the volume contains ({WP}):\n\n"+q(u1)+" [page break, p.22 -> p.23] "+q(u2)+"\n— Ulam, p.22-23. Raw text lines 2008-2011.\n\n"+q(u3)+"\n— Ulam, p.24.\n\n"+q(u4)+"\n— Ulam, p.25.",
 "Day's claim: Ulam's computation reaches Eden's conclusion. Ulam's text: his 'final probabilities, even if we assume some values from the present guesses, will not come to be as fantastically small as in Professor Eden's conclusions' (p.22-23), yet the calculation 'is illustrating something that I think Professor Eden had in mind' (p.24) and he 'personally' believes the numbers 'very optimistic rather than the opposite' (p.25). Ulam's own result is a rate, 10^13 generations (D4), not Eden's 10^-273.",
 "- Stated: Ulam's contribution should be read as supporting Eden.\n- Implicit: the direction of the disagreement (evolution too slow) is the relevant parallel; magnitudes need not match.",
 "- Against: the verbatim sentence Day attributes to Ulam is not in the OCR text of the volume: searches for 'come to Eden', 'Eden's conclusions', 'conclusions' return only the p.22-23 passage above, which states that Ulam's probabilities will NOT be as small as Eden's. Day's quote looks like a splice of 'What I am going to do will con-[sist]' (p.21-22) with 'come to ... Eden's conclusions' (p.22-23). OCR error cannot be excluded for a spliced sentence of this length, but the physical copy Day says he consulted would settle it.\n- In support: pp.24-25 support the substance: Ulam says his calculation illustrates what Eden had in mind and that his numbers are optimistic. Day's own quotation of p.25 differs from the printed text ('discussion I took, personally, I believe' vs 'discussion I, personally, believe').\n- Weaknesses: Rosenhouse's reading (Ulam 'was not challenging the fundamental soundness') is also a reading, not a quote; both sides interpret.",
 LIT0+"| Wistar p.22-23 | 'will not come to be as fantastically small as in Professor Eden's conclusions' | contradicts the magnitude implied by Day's sentence |\n| Wistar p.24 | calculation 'illustrating something that I think Professor Eden had in mind' | supports direction |\n| Wistar p.25 | 'numbers I took are very optimistic rather than the opposite' | supports direction |",
 "Written before the text search was repeated on the PDF text layer. Under Day's reading: a sentence equivalent to 'comes to Eden's conclusions' exists. Under the critic reading: Ulam's tone is exploratory ('schematic', 'start the discussion', p.22). Result that would change the verdict: a physical-copy check of pp.21-23 or the original 1967 printing (the local file is the 1985 Liss reprint scan).",
 "Text search: python3 -I over `Wistar1967.txt` and `pdftotext -layout` of the PDF: no 'come to Eden'; only the p.22-23 sentence. Script: ad hoc, not committed.","None.")

d2bi=bi("The transcript records Lewontin saying, “That is a very good question. I don’t know.”")
d2b_c6=ex('dint',"“Dr. Schützenberger: I would like to know how you could use a notion like quasi-continuity.”","“Dr. Lewontin: That is a very good question. I don’t know.”")
d2b_c6b=ex('dint',"Lewontin’s response was circular. The fitness topology, he suggested, was “itself a product of evolution.”")
lev=ex('W',"DR. LEVINS: I think the missing ingredient in this analysis is that you have left out evolution.","In fact, its topology is, itself, a product of evolution")
d2bii=bi("He does not mention Lewontin’s admission, under direct questioning from Schützenberger, that he cannot justify the continuity assumption that small genetic changes typically produce small phenotypic changes.")
l1=ex('W',"DR. LEWONTIN: I think the answer is that you have over-estimated the number of absolutely meaningless changes that occur when you change a single nucleotide.","do not render the molecule meaningless in an absolute context.")
l2=ex('W',"DR. SCHUTZENBERGER: That's a good question. I don't think I have time to answer it now.")
l3=ex('W',"DR. LEWONTIN: The answer is no.")
write('D2b-day-lewontin-cannot-justify-continuity','D2b','Lewontin admitted he could not justify the continuity assumption: "That is a very good question. I don\'t know."','day','D','D2',
 "[{type: attacks, target: D1},{type: depends-on, target: D5}]",'false','D is not required for ROOT','firsthand',
 'n/a','','misread','quoted sentence not found in the volume; Lewontin gives examples and says "The answer is no" to Schützenberger\'s viability comparison','contested','',
 d2bi+"\n\n"+d2bii+f"\n\nSource: {BIs}, paras {pb('The transcript records Lewontin')} and {pb('Lewontin’s admission is buried')}.\n\nThe same exchange as printed in Day's chapter 6 (2nd ed.):\n\n"+d2b_c6+"\n\n"+d2b_c6b+"\n\nSource: "+DINT_S+".\n\nWhat the volume contains ({WP}):\n\n"+q(lev)+"\n— Richard Levins, p.79 (the 'topology ... product of evolution' remark is Levins's, in the discussion of Schützenberger's paper; it is not Lewontin's).\n\n"+q(l1)+"\n— Lewontin, p.79 (reply to Schützenberger on meaningless changes).\n\n"+q(l3)+"\n— Lewontin, p.92 (to Schützenberger's question whether viable configurations are rarer than grammatical sentences).\n\n"+q(l2)+"\n— Schützenberger, p.79 (answering Mayr's question 'why do molecules have such-and-such properties?'). This is the only 'good question ... time' exchange in the volume; the speaker is Schützenberger.",
 "Day's claim is a fact about the transcript: Lewontin answered a question of Schützenberger's about continuity ('small genetic changes produce small phenotypic changes') with 'I don't know'. Searched the OCR text and the PDF text layer for 'very good question', 'good question', 'quasi', 'continuity', 'continuous', and every Lewontin turn containing 'know'. 'quasi-continuity' does not occur anywhere in the volume ('quasi' occurs only in 'quasi equilibrium' and 'quasimathematical').",
 "- Stated: Lewontin made an admission, 'under direct questioning from Schützenberger'.\n- Implicit: continuity of the genotype-phenotype map is the load-bearing premise of hill-climbing (true in the sense of the NK literature, see D).",
 "- Against: neither the quoted question ('quasi-continuity') nor the answer occurs in the volume; the circularity claim (the topology is 'itself a product of evolution') is spoken by Levins (p.79), and Schützenberger's rejoinder ('the Ashby trap') answers Levins; the verbatim quote does not occur; the phrase 'That's a good question. I don't think I have time to answer it now' belongs to Schützenberger (p.79). Lewontin repeatedly asserts the opposite: single amino-acid changes in tryptophan synthetase and hemoglobin change enzyme properties without destroying the molecule (p.76, column-interleaved in the OCR and here read down the column: 'known cases where the enzyme, far from being destroyed, is changed in its pH optimum, changed in its isoelectric points'; p.79: 'a very large proportion of those do not render the molecule meaningless').\n- In support: Lewontin's examples are enzyme-function-preserving changes, which does not establish continuity at the level of organism fitness, which was Schützenberger's actual question ('the mapping between the first and second [space]').\n- Weaknesses: OCR coverage is complete for this passage (two-column interleaving affects some lines but not the speaker labels). The Day-claimed physical-copy check is not reproducible here. A misattribution (Schützenberger/Lewontin) by Day remains possible rather than invention.",
 LIT0+"| Wistar p.76 | Lewontin: single substitutions change 'pH optimum', 'isoelectric points' etc. without destroying the enzyme | in tension with Day |\n| Wistar p.79 | Lewontin: 'a very large proportion of those do not render the molecule meaningless' | in tension with Day |",
 "Written before verification of the other locators. Under Day's reading the phrase exists. Under the null reading it does not. Result that would change the verdict: a physical-copy check showing the sentence on a page missing or mangled in the scan.",
 "Text search over the OCR volume and the PDF text layer: no occurrence of 'very good question'.","None.")

wd1=ex('W',"One is hard put to find a single instance in which a change in one amino acid in sequence does not change markedly the properties. The restrictions are enormous.")
wd2=ex('W',"DR. GEORGE W ALD: I want to ask Fraser and Lerner why one doesn't find hemoglobin diseases in which this phenomenon you are talking about has occurred?")
d2ci=bi("Wald stated that he was “hard put to find a single instance” where a single amino acid change in hemoglobin did not “change markedly the properties.”")
d2cii=bi("This is relevant to Eden’s argument about the ruggedness of the fitness landscape—if nearly every single-residue change has significant functional consequences, then the space is rugged, not smooth, and local search is unreliable.")
l4=ex('W',"DR. LEWONTIN: No, that is not true.") 
write('D2c-day-wald-ruggedness','D2c','Wald: one is "hard put to find" a hemoglobin amino-acid change that does not markedly change properties; this supports a rugged landscape','day','D','D2',
 "[{type: supports, target: D},{type: attacks, target: D1}]",'false','D is not required for ROOT','firsthand',
 'pending','the inference from hemoglobin variants to landscape ruggedness is not worked out','accurate','Day\'s quotation matches Wald p.19 (two sentences combined)','contested','ascertainment bias and counter-examples (Lewontin, Wistar pp.76-79); modern DMS not in corpus',
 d2ci+"\n\n"+d2cii+f"\n\nSource: {BIs}, paras {pb('Wald stated that he was')} and the following paragraph.\n\nPrimary text ({WP}):\n\n"+q(wd1)+"\n— George Wald, p.19 (in discussion of Eden's paper; the surrounding passage says 'I want to add a further note which has a large bearing, I think, on Eden's discussion').",
 "Observation O: among known hemoglobin variants, a single amino-acid substitution that leaves function largely unchanged is rare (Wald's sample). Day's inference: O => the landscape is rugged (most single steps off a functional protein are not functional), so local search is unreliable. In parameter form: p_neutral-or-better(single substitution) is small. Wald's statement carries no number.",
 "- Stated: hemoglobin changes 'change markedly the properties'.\n- Implicit: (i) the hemoglobin variants Wald considers are an unbiased sample of single substitutions (they are the ones that appear in clinical practice, i.e. detected because they have effects); (ii) 'change markedly the properties' = loss of function rather than modified function; (iii) hemoglobin is typical.",
 "- Against: ascertainment (clinically detected variants over-represent functional effects); Wald himself says (p.16) he does not know of any hemoglobin with a long run of shifts, i.e. he is supporting the point that long substitution runs are not seen, not that single steps are lethal; Lewontin (p.76) offers enzymes with changed but retained function; Mayr (p.16): 'Because it doesn't survive' (reply on long runs).\n- In support: Wald's point is made by a biologist at the symposium, on factual grounds.\n- Weaknesses: both directions rest on anecdote at Wistar. The quantitative modern evidence (DMS: fraction of single mutants tolerated, typically a substantial share for most positions) is not in the corpus and Day cites none (D2h); the claim 'single-residue changes to most proteins tend to reduce or destroy function' is, as written, a statement about proteins in general.",
 LIT0+"| Wistar p.19 (Wald) | 'One is hard put to find such an instance ... a single instance in which a change in one amino acid in sequence does not change markedly the properties.' | accurate quotation |\n| Wistar p.16 (Wald) | 'I don't know of any instance in which one has yet discovered a hemoglobin with a long run of shifts.' | context: long runs |",
 "Written before any check. Under Day's inference: in a DMS dataset, the median fraction of tolerated single substitutions per position is low (< ~20%) for most globular proteins. Under the opposing inference: it is high (> ~40%) with most positions tolerating many substitutions, and most deleterious effects are mild. Result that would change a verdict: harvested DMS distributions (e.g. median tolerated fraction) from the literature.",
 "No script (data not in corpus). Action: harvest DMS datasets (e.g. ProteinGym-style summaries).","Distribution of single-substitution fitness effects; fraction tolerated per position; epistasis between substitutions.")

c1=ex('W',"But, your reading frame shift seems to decrease enormously the possibility of intermediate stages being viable. This isn't a set of models we have got on a bench or a set of pretty pictures on a blackboard. We are going through a series of stages, each of which has got to be capable of existing viably, if it is going to have any possibility of giving rise to the next.")
c2=ex('W',"It always seems to me that there is such an air of gorgeous unreality when mathematicians come to deal with biological subjects")
c3=ex('W',"you cannot really start with year Xo; it has to be ION, where N is 3, 4 or 5. That seems to me to place the whole of that calculation completely out of court.")
d2d=bi("Rosenhouse quotes Crosby’s exasperated comment about “gorgeous unreality” as though it refutes the mathematicians. He does not mention that in the discussion of Eden’s paper, Crosby actually supported Eden’s argument, noting that each intermediate stage “has got to be capable of existing viably” and that frame-shift mutations “decrease enormously the possibility of intermediate stages being viable.”")
write('D2d-day-crosby-supported-eden','D2d','Crosby supported Eden on viable intermediates and was only frustrated by Ulam\'s oversimplifications','day','D','D2',
 "[{type: attacks, target: D1}]",'false','D is not required for ROOT','firsthand',
 'n/a','','partial','both Crosby quotes are accurate (p.17, p.31); "supported Eden\'s argument" is an interpretation: Crosby objects to frame-shift mechanisms','contested','',
 d2d+f"\n\nSource: {BIs}, para {pb('Rosenhouse quotes Crosby')}.\n\nPrimary text ({WP}):\n\n"+q(c1)+"\n— J. L. Crosby, p.17 (discussion of Eden; he is addressing Eden's reading-frame-shift suggestion).\n\n"+q(c2)+"\n— Crosby, p.31 (discussion of Ulam).\n\n"+q(c3)+"\n— Crosby, p.31.",
 "No formal content. Interpretation of two speech acts: (p.17) intermediate stages must be viable; (p.31) Ulam's calculation is 'out of court' because it begins at an unrealistic starting time.",
 "- Stated: Crosby 'supported Eden' in noting viability constraints.\n- Implicit: viable-intermediate constraints are what make Eden's topology horn (D3b) bite.",
 "- Against: the p.17 remark is a criticism of the frame-shift route ('If your changes take place by reading frame shifts, we would need fewer of them. But...') that Eden floated as a way to shorten paths; it constrains one proposed mechanism and does not endorse a probability-zero conclusion. The p.31 remark is a dismissal of mathematicians' modelling ('amuse themselves').\n- In support: Day's point that viability of intermediates is a premise accepted by a biologist at the symposium is accurate.\n- Weaknesses: viable intermediates are required by any gradualist model; Crosby does not say they are rare.",
 LIT0+"| Wistar p.17, p.31 (Crosby) | quoted above | accurate quotations; interpretation contested |",
 "No separate check (textual).","Textual audit of Wistar pp.17, 31.","None.")

e1=ex('W',"In the part which it has explored, which is the only part that is relevant to a consideration of evolution, biologists are asserting that the meaningful section of it is quite large in comparison with all the things that could conceivably be made out of it in single steps. It is a much larger fraction than is the space of meaningful strings of English words. I think this is the point.")
e2=ex('W',"We are asserting that it is a large fraction of the total space which could be made from the nucleotides involved, but stiIl we are saying that the meaningful space is a minute fraction of the total nucleotide space.")
e0=ex('W',"Therefore, life has only explored a minute fraction of the total nucleotide space.")
d2e=bi("Waddington asserts that “the meaningful section” of explored sequence space “is quite large in comparison with all the things that could conceivably be made out of it in single steps.” This is an empirical claim. He provides no data to support it. He provides no calculation. He simply asserts it.")
write('D2e-day-waddington-summary-asserted-not-shown','D2e','Waddington\'s summary ("the meaningful section is quite large") is an empirical assertion with no data or calculation','day','D','D2',
 "[{type: attacks, target: D1},{type: supports, target: D}]",'false','D is not required for ROOT','firsthand',
 'holds','Day\'s point that the summary supplies no data is borne out by the passage','partial','quote accurate (p.93); Day omits the same speaker\'s concession that the meaningful space is a minute fraction of the total','contested','',
 d2e+f"\n\nSource: {BIs}, para {pb('Waddington asserts that')}.\n\nPrimary text ({WP}):\n\n"+q(e1)+"\n\n"+q(e2)+"\n— The Chairman, C. H. Waddington, summing up on the Schützenberger question, p.93. Preceding sentence: "+q(e0)+" (the OCR attributes the summary to 'the Chairman, DR. WADDINGTON'.)",
 "Waddington's statement has two parts. (1) Life explored only 'a minute fraction of the total nucleotide space', exploring 'sequentially from the last position to some neighboring position'. (2) In the explored region, the meaningful section 'is quite large in comparison with all the things that could conceivably be made out of it in single steps' (a local-density claim), 'a much larger fraction than ... meaningful strings of English words'. Part (1) concedes Eden's premise; part (2) is the topology horn (D3b) in biologists' form. In notation: local functional fraction f_local >> global fraction f_global.",
 "- Stated: local density of function around explored sequences is high.\n- Implicit: exploration proceeds by single steps from functional starting points, so f_local, not f_global, governs the search.",
 "- Against: Day: no data, no calculation (accurate for this passage). Waddington adds a footing: 'they would have eaten anything else before it had a chance to get going', i.e. an early-life narrative.\n- In support: the principle is the standard 'evolution does not sample uniformly' reply.\n- Weaknesses: the concession ('minute fraction of the total') is omitted in Day's account, which makes the rebuttal seem to deny Eden's premise; and Waddington's claim is as unsupported as Day alleges.",
 LIT0+"| Wistar p.93 (Waddington) | meaningful space 'a minute fraction of the total nucleotide space' (concession) | accurate; omitted by Day |",
 "Written before any check. Under Day's reading: no number in the passage (confirmed by reading). Under the critic's reading: the claim is the topology horn and is testable (D2h). Result that would change a verdict: DMS-based estimate of f_local.",
 "Textual (above). Quantitative follow-up in D2h.","f_local vs f_global; step-wise exploration constraint.")

m1=ex('W',"So all I am saying is we have so much variation in all of these things that somehow or other by adjusting these figures we will come out all right. We are comforted by knowing that evolution has occurred.")
m2=ex('W',"Kappa somehow or other has to incorporate this. If a given gene is selected for because it does something good in the eye, what does this same gene do in all the other cells of the organism? That is a thing we have never taken into consideration and the evolutionist is very simple-minded about this.")
d2f_c6=ex('dint',"“The very fact that we have this conference,” he observed at one point, “is evidence that evolution has occurred.”")
d2f=bi("But the transcript shows Mayr was simply retreating to the argument from existence. “We are comforted by knowing that evolution has occurred” is not a mathematical rebuttal. It is not even a scientific argument. It is a profession of blind faith.")
write('D2f-day-mayr-argument-from-existence','D2f','Mayr\'s "adjusting these figures we will come out all right" is an argument from existence, not a rebuttal','day','D','D2',
 "[{type: attacks, target: D1}]",'false','D is not required for ROOT','firsthand',
 'n/a','','partial','quote accurate (p.30); context shows Mayr also argues the model\'s parameters (kappa, gamma) are underdetermined','contested','',
 d2f+f"\n\nSource: {BIs}, para {pb('Mayr’s “adjust the figures” quote')} onward.\n\nDay's chapter 6 (2nd ed.) gives a different wording for the same idea:\n\n"+d2f_c6+"\n\nSource: "+DINT_S+". This sentence is not in the volume (searched 'this conference', 'evidence that evolution has occurred' in the OCR text and PDF text layer); the nearest text is the p.30 sentence below.\n\nPrimary text ({WP}):\n\n"+q(m1)+"\n— The speaker turn that contains this sentence begins 'DR. MAYR: I must say I am really impressed by the tremendous agreement ...' (p.29) and ends p.30; page 30 per the PDF text layer.\n\n"+q(m2)+"\n— same turn, p.30, on the parameter kappa.",
 "No formal content. Interpretive. Mayr's turn comments on each of Ulam's parameters (alpha, gamma, kappa) and says the evolutionist has 'so much variation' that the figures can be adjusted; he adds 'We are comforted by knowing that evolution has occurred'.",
 "- Stated: parameters of Ulam's model are not known well enough to constrain the outcome.\n- Implicit: the last sentence reads as the argument from existence in Day's account, and as a statement about ignorance in the surrounding turn.",
 "- Against: Rosenhouse (via Day) claims Mayr's point was that Ulam's model is too simple to be useful; the surrounding text supports parts of that reading (the paragraph discusses unmodelled gene-tissue interactions) and also supports Day's reading of the last sentence.\n- In support: 'comforted by knowing' is a fair reading of an argument from existence.\n- Weaknesses: Mayr also says, in the same turn, that 'the chance of having a favorable mutation is possibly higher by an order of maybe 10^5' (p.30), an estimate with no basis given; and at p.24 that 'very often a mutant has a 30 percent advantage' (no citation), i.e. he does offer numbers, unsourced (D4b).",
 LIT0+"| Wistar p.30 | quoted above | accurate quotation |","No separate check.","Textual audit (Wistar p.30, p.24).","None.")

g1=bi("Rosenhouse never acknowledges that not one biologist at the conference produced a single calculation that contradicted the mathematicians’ conclusions")
g2=ex('W',"In a population as large as the human species, 3 x 10 9 , a mutation rate of 10 5 at each locus implies that all single step mutations from the common alleles will recur in every generation.")
fr=ex('W',"What is surprising is how fast rational information is produced by the machine within the meaning of the original context.")
g3=ex('W',"it would require less than 1250 questions to arrive at a specified one of these proteins.")
write('D2g-day-no-biologist-produced-a-calculation','D2g','No biologist at Wistar produced a single calculation that contradicted the mathematicians\' conclusions','day','D','D',
 "[{type: supports, target: D},{type: attacks, target: D1}]",'false','D is not required for ROOT','firsthand',
 'pending','depends on what counts as a calculation that "contradicts"','partial','the transcript contains numbers from biologists (Wright pp.117, 119; Mayr pp.24, 30); whether they "contradict" is interpretive','contested','',
 d_q2+f"\n\nSource: {BIs}, para {pb('Eden calculated the size of sequence space')}.\n\n"+g1+f"\n\nSource: same, para {pb('Rosenhouse never acknowledges that not one biologist')}.\n\nBiologist numbers in the volume ({WP}):\n\n"+q(g3)+"\n— Sewall Wright, p.117 (arithmetic: 250 residues x 5 yes/no answers; recomputed 250*5 = 1250; the information bound log2(20^250) = 1080 bits).\n\n"+q(g2)+"\n— Wright, p.119 (mutation supply; arithmetic 3e9 x 1e-5 = 3e4 new mutants per locus per generation).\n\n"+q(fr)+"\n— Alex Fraser, p.80, describing his computer experiments on a genetic system (qualitative statement of a simulation result; no numbers in this turn).",
 "Universal over biologist contributions B at Wistar: for all b in B, not (b is a calculation and b contradicts C_Eden/C_Ulam/C_Schützenberger). Counter-examples need (i) a calculation, (ii) bearing on a conclusion. Candidates: Fraser's simulation result (p.80), Bossert's and Lewontin's computer models (Day concedes Lewontin's simulations are 'technically impressive' but 'missed the point', ch.6); Wright's 1250-question bound (bears on the 'typing at random' reading of Eden, which Eden said at p.8 was a misreading); Wright's mutation-supply figure (bears on Ulam's 'ten individuals per generation'); Mayr's gamma (30 percent, no source) vs Ulam's 1e-6.",
 "- Stated: no calculation contradicted a conclusion.\n- Implicit: a numerical analogy (Wright) is not a calculation about biology; unsourced estimates (Mayr) do not count.",
 "- Against: the three items above. Whether they 'contradict' is the open point: Wright's 1250 vs 10^325 contradicts the reading that selection needs ~10^325 steps; Eden's reply (p.8) accepts the arithmetic ('Of course, he is correct') and re-bases the argument on path length. So at least one contradiction of one reading of Eden was calculated and conceded.\n- In support: no biologist computed the time to fix 10^6 successive improvements (Ulam, p.24) or the path-length distribution (Eden p.8, which Eden himself says he cannot compute).\n- Weaknesses: both statements are about a 60-year-old transcript; and the universal claim is contestable by a single counter-example. Day's own post of 2024-07-13 reproduces Wright's 1250-question passage (as an example of an 'attempt' that fails), so the existence of Wright's calculation is not in dispute.",
 LIT0+"| Wistar p.117 (Wright) | quoted above | accurate |\n| Wistar p.119 (Wright) | quoted above | accurate |\n| Wistar p.8 (Eden) | 'Of course, he is correct, but I believe he has misunderstood my argument.' | accurate |",
 "Written before the arithmetic. Under Day's claim: no biologist number contradicts the conclusions as stated. Under the critic's claim: Wright's calculation contradicts the random-assembly reading, and Mayr's gamma contradicts Ulam's gamma. Result that would change a verdict: Eden's agreement that Wright's arithmetic is correct (found, p.8) moves the fidelity verdict to partial; internal verdict depends on whether Eden's revised argument (path length) was ever quantitatively answered at Wistar (not found).",
 "Arithmetic: `python3 -I -c \"import math;print(250*5, 250*math.log2(20), 3e9*1e-5)\"` -> 1250, 1080.5, 30000.0. Reconciles with Wright's 1250 (rounded up from 1080.5 bits).","None.")

dms=ex(BII,"The most relevant empirical work, deep mutational scanning studies, actually shows the opposite of what Rosenhouse implies. Single-residue changes to most proteins tend to reduce or destroy function. The fitness landscape is rugged, not smooth. Eden’s 1966 concerns about the rarity of functional proteins in sequence space have been confirmed by subsequent experimental work, not refuted by it.")
write('D2h-day-deep-mutational-scanning-shows-ruggedness','D2h','Deep mutational scanning shows single-residue changes mostly reduce or destroy function; the landscape is rugged, which confirms Eden','day','D','D2',
 "[{type: supports, target: D},{type: attacks, target: D1a}]",'false','D is not required for ROOT','firsthand',
 'pending','no data or citation offered','unverifiable','no study cited; the claim concerns "most proteins" as a class','contested','requires harvest of DMS literature (not in corpus)',
 dms+f"\n\nSource: {BIIs}, para {pbii('The most relevant empirical work')}. No citation in the post (Day uses the same standard against Rosenhouse in the previous paragraph).",
 "Claim: for typical proteins, the share of single-substitution mutants with reduced/destroyed function is large (the DFE is shifted toward deleterious) and the landscape (functional sequences) is non-connected. Parameters: `p_del` = fraction of single substitutions that substantially reduce function; `K` or a pair-correlation of effects. Day gives neither.",
 "- Stated: DMS studies exist and support ruggedness.\n- Implicit: 'reduce or destroy' is equivalent to 'rugged'. Reduction is not destruction; ruggedness needs local optima that block ascent, not mean deleterious effect. Most random mutations being deleterious is compatible with smooth landscapes (Fisher's geometric model) and with selection finding the rare beneficial ones.",
 "- Against: Rosenhouse (D1a) says the opposite and also gives no citation. Wistar-era data (Lewontin) point the other way (D2b).\n- In support: Wald (D2c). Axe 2004 (D10) measured low prevalence for one fold under a hydropathic-signature restriction, not DMS.\n- Weaknesses: symmetrical lack of citations on both sides; the corpus has no DMS source. The quoted sentence is a general factual claim about the field.",
 LIT0+"| Deep mutational scanning literature | not in corpus; no study cited by Day | unverifiable |",
 "Written before any check. Under Day: a harvest of DMS datasets shows median single-substitution fitness effects strongly deleterious for most positions and landscape-wide epistasis that creates local optima. Under the opposing model: most positions tolerate several substitutions, deleterious effects are typically mild, and high-fitness sequences form connected networks (percolating neutral networks). Result that would change a verdict: harvested p_del and epistasis distributions; the NK-reachability module (D, S2) mapped to measured K.",
 "Specification only (separate later module). Harvest list: classic DMS sets with published per-position tolerance fractions (beta-lactamase TEM-1, GFP, ubiquitin, Gb1, hemoglobin variants); compute p_del and pairwise epistasis; feed into S2.","p_del; epistasis structure; connectivity of high-fitness sequences.")

ea=ex(BII,"every evolutionary algorithm ever written has a programmer-designed fitness function that does exactly what Schützenberger said biology lacks: it provides the mapping between typographic changes and functional outcomes.")
eb=ex(BII,"Dawkins’s WEASEL program is the perfect example: it works because Dawkins specified the target string, the fitness function, and the selection rule.")
write('D2i-day-evolutionary-algorithms-designed-fitness','D2i','Every evolutionary algorithm has a programmer-designed fitness function, supplying the mapping Schützenberger said biology lacks','day','D','D2',
 "[{type: attacks, target: D1b},{type: depends-on, target: D5}]",'false','D is not required for ROOT','firsthand',
 'holds','valid against an existence-proof reading; silent on plausibility readings','n/a','','contested','biological fitness feedback exists (survival/reproduction) but the sequence-to-fitness map is not designed; whether it is smooth is the open question',
 ea+"\n\n"+eb+f"\n\nSource: {BIIs}, para {pbii('This is a non sequitur')}.",
 "Evolutionary-algorithm success is conditional on a fitness mapping F: sequence -> reproductive success with exploitable gradient. Day: programmers supply F; biology must supply F too, so the algorithms show nothing about the origin of F. Dawkins's Weasel uses F = number of letters matching a fixed target (known endpoint), which Day also criticises in his Weasel post (D9: 'the target phrase is known from the start, which is not the case in the evolutionary context').",
 "- Stated: designed F is what Schützenberger said biology lacks.\n- Implicit: biological F is not simply 'designed'; it is the survival and fertility consequence of the sequence, which exists whether or not it is smooth. The dispute is whether natural F gives local gradients.",
 "- Against: Wright (D6) says his analogy is 'not a perfect analogy to natural selection'; Weasel's own defenders (not in corpus) typically note it illustrates cumulative selection, not target-free evolution. Computational biology uses empirically measured landscapes (not in corpus).\n- In support: Schützenberger, p.75: 'without some built-in matching, nothing interesting can occur' (observation about AI programs).\n- Weaknesses: the point is correct about Weasel and equally shows Day's own Weasel recomputation (D9) inherits the target-known feature he rejects.",
 LIT0+"| Schützenberger (Wistar p.75) | 'Their experience is quite conclusive to most of the observers: without some built-in matching, nothing interesting can occur.' | accurate |",
 "Written before any check. Under Day: evolutionary algorithms on empirical landscapes without built-in gradient fail to find high-fitness sequences. Under the opposing model: they succeed whenever measured landscapes have local gradients (low K). Result that would change a verdict: success/failure on DMS-derived landscapes (D2h step S2/S3).",
 "Specification only: reuse the S2/S3 module.","Landscape provenance (designed vs empirical) switch in the simulator.")

# ---------- D2j: Eden/Waddington 'show me the math' (ch6)
j1=ex('dint',"Eden’s response was polite but he showed Waddington no mercy: “I must apologize for being so vague on the nature of R,” he said, referring to the fitness function, “but let me say just one thing that led me to this conclusion: it requires a more complete definition of fitness or survival in which case one can discuss the absolute magnitude of the probabilities.”")
j2=ex('dint',"To put it in plain English, he was saying “show me the math.” Waddington couldn’t do it.")
j3=ex('W',"DR. WADDINGTON: The variation is about 0.75 and you come to 0.001 away from the optimum in your earlier figure?","I agree with you now, that it is important to complete the discussion of this point.")
write('D2j-day-eden-apologises-for-vagueness-ch6','D2j','Eden answered Waddington\'s fitness-landscape point with "I must apologize for being so vague on the nature of R ... show me the math"','day','D','D2',
 "[{type: attacks, target: D1},{type: supports, target: D2e}]",'false','D is not required for ROOT','firsthand',
 'n/a','','misread','the quoted remark is William Bossert\'s answer to Waddington about the parameter R^2 in Bossert\'s own population model (p.40), not Eden on the fitness function','contested','',
 j1+"\n\n"+j2+"\n\nSource: "+DINT_S+".\n\nPrimary text ("+WP+"):\n\n"+q(j3)+"\n— W. Bossert, p.40 (discussion of Bossert's paper). The sentence 'I must apologize for having been so vague on the nature of R2' continues 'which appears in the figures. To explain it in detail requires a more complete definition of the abstract problem which led to the fitness function used'; R2 is a distance measure in Bossert's simulation, and the abstract problem is the solution of simultaneous linear equations.",
 "Day's claim is a fact about the transcript: Eden, responding to Waddington's smooth-landscape point, deferred to a missing definition of fitness. The text shows a different speaker (Bossert), a different topic (a simulation's plotted axis) and a different context (the discussion of Bossert's paper, not Eden's).",
 "- Stated: Eden's reply amounts to 'show me the math'.\n- Implicit: the remark is evidence that biologists could not supply a fitness landscape.",
 "- Against: the quotation is from Bossert (p.40); Day's wording is almost verbatim ('so vague' vs 'having been so vague', 'for the nature of R' vs 'on the nature of R2'), the near-verbatim match indicates that the source of the sentence is this Bossert passage.\n- In support: the substantive point that Waddington's smooth-landscape suggestion lacked data is made by Day at D2e and is supported by the p.93 passage.\n- Weaknesses: the misattribution does not alter D2e.",
 LIT0+"| Wistar p.40 (Bossert) | quoted above | accurate text; wrong speaker in Day's account |",
 "No separate check (textual).","Textual audit (Wistar p.40; Day ch.6).","None.")

import glob
for f in glob.glob(OUT+'D*.md'):
    t=open(f,encoding='utf8').read()
    if '{WP}' in t:
        open(f,'w',encoding='utf8').write(t.replace('{WP}',WP)); print('fixed',f)
