import sys; sys.path.insert(0,os.environ.get("EVO_WORK","work")+"")
from gen_lib import *
LIT0="| Cited work | What it actually says (quote) | Fidelity |\n|---|---|---|\n"
EC='b:2024-04-25-every-critique-is-correct'
ECs="[Every Critique is Correct](https://voxday.net/2024/04/25/every-critique-is-correct/), 2024-04-25, voxday.net"
f1=ex(EC,"Sir Ronald Fisher, a world expert on the mathematics of evolution, has shown that the odds of the survival of a single mutation with a survival benefit of 0.1% greater than the rest of the population is 500 to 1 against – because the majority of mutants are eradicated by random effects. In other words, only 1 in 500 mutants with a positive benefit of 0.1% will end up taking over the entire population.")
k62=ex('k62',"For a positive s and very large N we obtain the known result that the probability of ultimate survival of an ad- vantageous mutant gene is approximately twice the selection coefficient (HAL- DANE 1927).")
write('D7-fisher-500-to-1-against-fixation','D7','Fisher: a mutation with a 0.1% benefit has 500 to 1 odds against surviving; only 1 in 500 takes over the population','day','D','D',
 "[{type: supports, target: D7a}]",'false','this is a premise of the Spetner chain (D7a), not of ROOT; Day\'s MITTENS papers use Kimura\'s 2s separately','secondhand',
 'holds','2s for s = 0.001 is 1/500; exact Kimura value for N = 1e4 is 0.00200','partial','the 2s formula is verified (Kimura 1962 p.716), but Kimura credits the approximation to Haldane (1927) and the general formula to Fisher (1930) and Wright (1931); Day\'s attribution to Fisher alone is unverified','supported','for large N, additive (genic) selection, new mutant in one copy; standard result',
 f1+f"\n\nSource: {ECs}, para {para(EC,'Sir Ronald Fisher')}. `secondhand`: Day reproduces the argument from darwinsmaths.com (link in the post's first sentence) and from Spetner (named in the following paragraph); neither retrieved.\n\nPrimary check text:\n\n"+q(k62)+"\n\nSource: Kimura, Genetics 47:713, 1962, p.716 (user-downloaded copy; `sources/raw/sources/manual/Kimura1962.txt`).",
 "P_fix = 2s for small s and large N (Haldane 1927, via Kimura 1962); Kimura's diffusion value: u(p) = (1 - e^(-4Nsp))/(1 - e^(-4Ns)) with p = 1/(2N). For s = 0.001: 2s = 0.002 = 1/500, i.e. odds 499 to 1 against. Recomputed: for N = 10,000, u = (1 - e^-0.002)/(1 - e^-40) = 0.001998 (from `research/checks/wf.py kimura_u`; a 1.2e6-replicate simulation gave 0.00201). Reconciles.",
 "- Stated: s = 0.001; survival odds; 'the majority of mutants are eradicated by random effects'.\n- Implicit: s is a mean benefit for a new mutant; N large; heterozygote advantage s (genic); one copy.",
 "- Against: none on the number. Dependence on s: Zeng 2021 (the cited source for 0.001 elsewhere, fidelity ledger) reports ~0.001 as a mean for negative selection.\n- In support: Kimura 1962 p.716.\n- Weaknesses: attribution; and the figure applies to a single new copy. Standing variation, soft sweeps and larger s change it (ROOT-M row 3).",
 LIT0+"| Kimura 1962 p.716 | 'probability of ultimate survival of an advantageous mutant gene is approximately twice the selection coefficient (HALDANE 1927)' | accurate for the formula; credits Haldane 1927, formula to Fisher 1930/Wright 1931 |\n| Fisher 1930 | not retrieved | unverified |",
 "Written before the computation. Prediction (Day): 1/500. Prediction (standard theory): 2s = 1/500; Kimura u within 1% of 2s at N = 1e4, s = 1e-3. Result that would change a verdict: Kimura u deviating from 2s by more than 5% at the stated parameters (it does not).",
 "`python3 -I` with `research/checks/wf.py kimura_u(10000,0.001)` -> 0.001998 (reconciles with 2s = 0.002).","N, s, initial frequency 1/(2N), P_fix.")

c1=ex(EC,"The chance that a specific change to a specific nucleotide will occur during a step is thus 1/600, and the odds that it will also take over the population is 1/500. The total odds are thus 1/600 * 1/500 or 1/300,000. This needs to happen 500 times in a row (the number of steps required to arrive at a new species). We thus need to multiply 1/300,000 by itself 500 times. The odds against this happening are approximately 3.6 x 102738 to 1, or viewed the other way round, the chance of this happening is 2.7 x 10-2739.")
c2=ex(EC,"Of course, one cannot simply assume that only one mutation is available at every step.")
c3=ex(EC,"All of them can be safely assumed to be valid.")
c4=ex(EC,"The thing to keep in mind is that all of them are correct.")
write('D7a-spetner-chain-3.6e2738-to-1','D7a','The odds against 500 sequential specific mutations each with probability 1/300,000 are about 3.6 x 10^2738 to 1','day','D','D',
 "[{type: depends-on, target: D7},{type: supports, target: D}]",'false','not a premise of ROOT; Day endorses it as one of many "correct" challenges but calls his own Impossibility of Mutational Fixation argument better because it leaves "no room ... for epicycles"','secondhand',
 'holds','arithmetic reproduces: (3e5)^500 = 10^2738.56 = 3.64e2738; reciprocal 2.75e-2739 (Day prints 2.7)','unverifiable','Spetner (Not By Chance) and darwinsmaths.com not retrieved; 1/600 and "500 steps" have no source here','contested','single-specific-path model; the same post disowns it in the next paragraph',
 c1+f"\n\nSource: {ECs}, para {para(EC,'The chance that a specific change')}. OCR/extraction note: superscripts are flattened in the extracted text ('102738' = 10^2738, '10-2739' = 10^-2739). `secondhand` (the argument is Spetner's, via darwinsmaths.com).\n\n"+c2+"\n\n"+c3+"\n\n"+c4+f"\n\nSource: same post, paras {para(EC,'Of course, one cannot simply assume')}, {para(EC,'All of them can be safely assumed')}, {para(EC,'The thing to keep in mind')}.",
 "Model: a specific path of n = 500 steps; at each step a specific nucleotide change must (i) occur, with probability a = 1/600, and (ii) fix, with probability b = 1/500 (2s, D7). Per-step success p1 = a*b = 1/300,000. All steps independent. P(path) = p1^n = (1/300000)^500. Recomputed: log10 = -500*log10(3e5) = -2738.56, so P = 2.75e-2739 and odds against = 3.64e2738 to 1 (Day: 3.6 x 10^2738 'to 1' and 2.7 x 10^-2739; the 2.7 vs 2.75 is a rounding/truncation difference of 2%). Reconciles.",
 "- Stated: one specific nucleotide per step; 500 steps for a new species; independence; 'Nobody knows' how many positive mutations are available, so Spetner turns the question around (D7b).\n- Implicit: 'step' is not defined (generation? fixation event?); 1/600 has no stated referent; the 500 is unsourced; the product treats the path as pre-specified (the specific-vs-any issue G3).",
 "- Against: Camestros and McCarthy on specific-vs-any (G3); Day's own paragraph 'one cannot simply assume that only one mutation is available'. Ulam (D4a, p.21) called the chain argument 'naive'.\n- In support: Day: 'all of them are correct'. Ulam wrote the same multiplicative form in the opening of his talk (D4a) before saying it was not the problem.\n- Weaknesses: the arithmetic is right, and it is a statement about one specified path. Day's text does not claim it as the probability of evolution; the next two paragraphs reframe it as a requirement on the number of available mutations (D7b). Calling it 'correct' while not using it as the main case is consistent.",
 LIT0+"| Spetner, Not By Chance (1997) | not retrieved | unverifiable |\n| Fisher 1930 / Haldane 1927 | see D7 | partial |",
 "Written before the computation. Prediction (Day): 3.6e2738. Standard arithmetic: 10^(500*log10(3e5)). Result that would change a verdict: |log10 - 2738.56| > 0.05.",
 "`python3 -I -c \"import math;L=500*math.log10(300000);print(L, 10**(L%1), 10**(1-L%1))\"` -> 2738.5606, 3.636, 2.750. Reconciles (Day: 3.6, 2.7).","Path length n; per-step probability a*b; specific-site vs any-site switch; number of beneficial mutations per step.")

c5=ex(EC,"The chance of a single step succeeding must be large – because we need to multiply it by itself 500 times (for the 500 steps) so that it comes out as close to 1/1,000,000 as possible (i.e. the chance of 1 in a million). The smallest number that will do this is 0.9727 as 1 – (1 – 1/300,000 ) 1,080,000 = 0.9727")
c6=ex(EC,"So if the odds that a specific nucleotide will mutate and take over a population are to be 0.9727 for each step, there must be 1,080,000 potential positive adaptive copying errors for each of the 500 steps to arrive at a 1 in a 1,000,000 chance for the development of a new species.")
write('D7b-0.9727-needs-1.08-million-beneficial-mutations-per-step','D7b','To reach a 1-in-a-million chance over 500 steps each step needs success probability 0.9727, which requires 1,080,000 candidate beneficial mutations per step','day','D','D',
 "[{type: depends-on, target: D7a}]",'false','not a premise of ROOT','secondhand',
 'holds','1 - (1 - 1/300000)^1080000 = 0.97268; 0.9727^500 = 9.8e-7; required n = 1,080,259 (0.9727) or 1,080,778 (exact p^500 = 1e-6)','unverifiable','Spetner not retrieved','untestable','the required number of beneficial mutations per step is a biological quantity nobody in the corpus measures; the 1e-6 target is a stipulation',
 c5+"\n\n"+c6+f"\n\nSource: {ECs}, paras {para(EC,'The chance of a single step succeeding')}-{para(EC,'So if the odds that a specific nucleotide')} (the formula is laid out across two lines in the extraction). `secondhand`.",
 "Let q = 1/300,000 be the per-candidate success probability and n the number of independent candidate beneficial mutations at each step. Step success P1 = 1 - (1 - q)^n. Required: P1^500 = 1e-6, i.e. P1 = 10^(-6/500) = 0.972747. Then n = ln(1 - P1)/ln(1 - q) = 1,080,778. Day: P1 = 0.9727 -> n = 1,080,259 -> '1,080,000'. Check: 1 - (1 - 1/300000)^1080000 = 0.972676 (Day prints 0.9727); 0.9727^500 = 9.76e-7 (~1e-6). Also n*q = 3.6 and 1 - e^-3.6 = 0.97268. All reconcile.",
 "- Stated: 'reasonable chance' = 1 in a million (stasis argument: species go for a very long time without changing); 500 steps; independence across steps; each candidate acts with probability 1/300,000.\n- Implicit: the 1e-6 target is chosen by Spetner and is not derived; 'a step' undefined; 1.08 million candidates are the number of beneficial mutations at a single step, which Day says 'Nobody knows'.",
 "- Against: the requirement is a statement about biology (how many beneficial single-nucleotide options exist at a time) that the post does not test. For scale: 1.08e6 out of ~9.6e9 possible single-nucleotide changes in a 3.2 Gb genome (3 alternatives each) is 1.1e-4 (derived, not a Day figure); whether that many beneficial options exist at each step is the empirical question.\n- In support: Day (post).\n- Weaknesses: both the target (1e-6) and the model (500 sequential steps each requiring a success) are stipulations.",
 LIT0+"| Spetner 1997 | not retrieved | unverifiable |",
 "Written before computation. Prediction (Day): 0.9727 and 1.08e6. Standard arithmetic reproduces both. Result that would change a verdict: |P1 - 0.9727| > 0.0005 or n outside 1.07-1.09e6.",
 "`python3 -I -c \"import math;q=1/3e5;print(1-(1-q)**1080000, 0.9727**500, math.log(1-10**(-6/500))/math.log(1-q))\"` -> 0.97268, 9.76e-7, 1080778. Reconciles.","Number of beneficial candidate mutations per step; steps per species; target probability.")

# D8 Milton
m1=ex('milton',"When he examines the probability calculations for even a single protein forming by chance (1 in 10^65), he finds odds so astronomical that they’re equivalent to winning the lottery every week for a thousand years with the same numbers.")
m2=ex('milton',"Richard Milton’s Shattering the Myths of Darwinism arrived in 1992 like a stone through the stained glass window of scientific orthodoxy.")
m3=ex('milton',"It was obvious from the time of the 1967 symposium held by the Wistar Institute that evolution was not a real science.")
write('D8-milton-single-protein-1-in-1e65','D8','Richard Milton: the probability of a single protein forming by chance is 1 in 10^65','ally','D','D',
 "[{type: supports, target: D}]",'false','not a premise of ROOT','secondhand',
 'n/a','no derivation','unverifiable','Milton\'s 1992 book not retrieved; the blockquote is an unattributed summary','pending','no model stated',
 m1+"\n\n"+m2+f"\n\nSource: voxday.net, [The Foundation of Sand](https://voxday.net/2025/10/02/the-foundation-of-sand/), 2025-10-02 (post id 68823), as reproduced in the tag archive page `sources/raw/day/tags/evo-11.html`; the passage is a blockquote that Day introduces as 'a death that has been in the making for at least the last 30 years' and which is not attributed to an author in the extracted text. `secondhand`: it summarises Milton, *Shattering the Myths of Darwinism* (1992). Day's own sentence closing the post:\n\n"+q(m3),
 "Single stated number: P(single protein by chance) = 10^-65, no length, function or fold stated. Candidate reconstruction (this file; not in the source): a specific 50-residue sequence has probability 20^-50 = 10^-65.05 (50*log10(20) = 65.05), so the figure is consistent with a specific 50-mer; no source says this.",
 "- Stated: 'even a single protein forming by chance'.\n- Implicit: a specific sequence; random assembly (the model Ulam called 'not the problem', D4a).",
 "- Against: Taylor 2001 and Keefe & Szostak 2001 (D11, D12) measured frequencies of function in random libraries, which are not 10^-65-scale; Axe 2004 (D10) is lower for a 150-residue domain.\n- In support: n/a.\n- Weaknesses: unsourced; the model is the one Ulam and Eden's own reply treat as not the real argument. Note Day writes '1967 symposium' where the meeting was 25-26 April 1966 (the proceedings are 1967).",
 LIT0+"| Milton 1992 | not retrieved | unverifiable |",
 "No check (no definition of the event). Action: obtain Milton 1992 and the page.","None.","Sequence length and function definition would be needed.")

# D9 Weasel
BW='b:2026-09-12-probability-weasel'
w1=ex(BW,"If we apply Dawkins’s proposed 5% advantage to the population in the correct manner, we assume a selection advantage of five percent. Or s=.05. With the appropriate reproductive limit of 12 rather than 100, that means it will take 400 generations for the initial letter M to propagate throughout the species, and 11,000 generations for all 27 letters required to complete the phrase to do so.")
w2=ex(BW,"However, Dawkins’s 5% probability was referring to the initial mutation, not the actual selection advantage, which is usually much more subtle, around s=0.001. And this gives us 20,000 generations for the initial letter M and 540,000 generations to complete the full phrase.")
w3=ex(BW,"First, note that Dawkins’s “population of 100” is really just one weasel that has 100 kits a year, where you keep those with the desired letter and kill the others. That’s not a species. A real weasel has about six kits, up to twice a year. So plug in the real animal, with a minimum population of 10,000 so it’s not going extinct,")
w4=ex(BW,"A phrase letter initially appears in one weasel out of 10,000. For that letter to count toward completing the phrase, all 10,000 weasels have to end up carrying it. And the only way that happens is the slow way: that one weasel’s descendants slightly out-breeding everyone else’s, litter after litter after litter, until the whole population has it. That process is called fixation.")
w5=ex('b:2026-10-01-the-education-of-a-population-geneticist',"The MITTENS calculation does not assume sequential fixation.")
WSs="[Probability Weasel](https://voxday.net/2026/09/12/probability-weasel/), 2026-09-12, voxday.net"
write('D9-weasel-540000-generations','D9','Under N = 10,000 weasels, 12 offspring and s = 0.001, each Weasel letter takes 20,000 generations to fix and the 27-letter phrase 540,000 generations','day','D','D',
 "[{type: depends-on, target: D2i},{type: attacks, target: D}]",'false','illustrative; ROOT does not depend on the Weasel recomputation','firsthand',
 'holds','27 x 20,000 = 540,000; (2/s)ln(2N) = 19,807 for s = 0.001 and 396 for s = 0.05; but it assumes letters fix one after another and uses a deterministic sweep time','n/a','Day\'s own calculation; no source','contested','conditional fix time is ~8,500 not ~20,000 (B0.4); parallel loci would complete in ~13,000; the Weasel as published is a different algorithm (D9a)',
 w1+"\n\n"+w2+"\n\n"+w3+"\n\n"+w4+f"\n\nSource: {WSs}, paras {para(BW,'If we apply Dawkins')}, {para(BW,'However, Dawkins')}, {para(BW,'First, note that')}, {para(BW,'A phrase letter initially appears')}.\n\nFor comparison, Day on MITTENS (different claim): "+q(w5)+"\n\nSource: [The Education of a Population Geneticist](https://voxday.net/2026/10/01/the-education-of-a-population-geneticist/), 2026-10-01.",
 "Parameters (Day's stated): N = 10,000 weasels; offspring 12 (not used in the formulas given); selection coefficient s = 0.05 (Dawkins 'advantage') or 0.001; L = 27 letters to be fixed. Per-letter time t_letter = (2/s)*ln(2N) (the deterministic logistic sweep time; this reproduces Day's figures: s = 0.05: 396 ~ '400'; s = 0.001: 19,807 ~ '20,000'). Total T = 27*t_letter serial: s = 0.05: 10,696 (Day '11,000'; 27*400 = 10,800); s = 0.001: 534,788 (Day '540,000' = 27*20,000). Ratio to Dawkins's 50 generations: 540,000/50 = 10,800 = 10^4.03 (Day: 'about 11,000x', 'four orders of magnitude'). All Day figures reconcile with these formulas. B0.4 shows (2/s)ln(2N) overshoots the mean time of an allele conditioned on fixing by ~2.3x at N = 1e4, s = 1e-3 (8,480 diffusion; 8,532 stochastic approximation).",
 "- Stated: (i) each letter must reach fixation in a population of 10,000; (ii) s = 0.001 is the 'actual selection advantage'; (iii) letters fix sequentially (sum over 27, 'all 27 letters required to complete the phrase'); (iv) 12 offspring is the reproductive limit.\n- Implicit: no mutation-supply limit (a letter 'initially appears in one weasel'); no parallel fixation (contradicts the stance in D9's comparison quote, where Day says MITTENS 'does not assume sequential fixation'); haploid or genic, N is the size for the 2N copies in 20,000 = (2/s)ln(2N) (matches 2N = 20,000 copies); the Weasel 'target' fitness is replaced by a constant s.",
 "- Against: (a) 8,525 +- 39 generations is the simulated mean conditional fixation time at N = 1e4, s = 1e-3 (exploratory run, below; B0.4 gives 8,480 diffusion): the per-letter figure is overstated 2.3x. (b) Independent loci complete in parallel: the maximum over 27 loci has mean ~13,100 generations (exploratory), 41x below 540,000. (c) The published Weasel is a truncation-selection algorithm, not an s = 0.001 population (D9a). (d) Mutation supply: with realistic u the waiting time for each specific letter dominates: W = 1/(2N*u*2s); for u = mu/3 = 4e-9 per copy per generation, W = 6.25e6 per letter and the parallel maximum of 27 is H27 x W = 2.4e7 (derived), which exceeds 540,000; with Dawkins-like u = 0.05/27 per copy, W = 13.5 and the parallel completion ~53. So the figure depends on which of the two limits (sweep time vs mutation waiting) governs, which Day does not address.\n- In support: Day's seriality is the same assumption as Ulam's (D4); if fixations are strictly sequential the sum is right.\n- Weaknesses: both the Day and critic sides here are model-dependent; the exploratory numbers are not pre-registered.",
 LIT0+"| Dawkins (as quoted in Day's post, from approxion.com) | 'a random sequence of 28 letters ... chooses the one which, however slightly, most resembles the target phrase' | secondhand quote |\n| Kimura & Ohta 1969 | t_bar = 4Ne for neutral; conditional sweep times for beneficial: see B0.4 | accurate (ledger) |",
 """Written before the formal check (which is specified, not run). The numbers below in 'Check' were from a scratch run made while drafting and are exploratory, not pre-registered; the formal check is pre-registered here.
- Under the claimant's model (Day): letters fix serially, total T = 27*t_letter with t_letter = (2/s)ln(2N): 534,788-540,000 generations.
- Under the opposing model: independent loci each follow a conditional sweep time (mean ~8,500, sd ~1,900 at N = 1e4, s = 1e-3); the phrase completes at the maximum over 27 independent loci: ~13,000 (+ mutation waiting). Under a strictly serial rule the total would be 27 x 8,500 = 230,000.
- Result that would change a verdict: (i) a simulation with 27 linked, selected loci at s = 0.001 whose completion time exceeds ~10x the independent-locus maximum would support Day's seriality; (ii) any realistic u that makes mutation waiting dominate would support the 'longer than 540,000' direction; (iii) a completion time near 540,000 under any parallel implementation would support Day.""",
 """Exploratory scratch run (python3 -I, venv numpy, `research/checks/wf.py single_locus`, seed 20261007; not committed): N = 10,000 diploid (2N = 20,000 copies), genic s, start at one copy, conditional on fixation:
- s = 0.001: 2,409 fixations of 1.2e6 replicates (P_fix 0.00201; Kimura 0.00200); mean fixation time **8,525 +- 39**, sd 1,914. Serial 27 letters: mean total 230,053. Parallel, maximum of 27 independent draws (bootstrap): mean **13,092** (5th-95th percentile 10,992-15,417).
- s = 0.05: 5,656 fixations of 60,000 replicates (P_fix 0.0943; Kimura 0.0952); mean **332**; diffusion 326; Day's 396. Serial 27: 8,956; parallel max of 27: 422 (5th-95th 380-477).
Does not include mutation waiting, linkage or the 12-offspring rule (which Day's formulas do not use). Does it reconcile with Day? The per-letter time does not (8.5k vs 20k); the serial sum does not (230k vs 540k); the arithmetic of 27 x 20,000 does.
Formal check specification (later module, not run): WF with 2N = 20,000 copies, 27 loci, s in {0.001, 0.05}, mutation u from {0.05/27, 1.2e-8/3}, recombination r in {0, 0.5 free}, outputs: time to all-27 fixed; compare serial vs parallel predictions.""",
 "N, s, L=27 loci, offspring number (12), mutation supply u per letter, recombination r (linkage), serial/parallel switch, deterministic vs conditional-sweep time, truncation vs fitness-proportional selection.")

# D9a
bw5=ex(BW,"So Dawkins’s little program which was meant to demonstrate the viability of evolution by natural selection actually demonstrates the precise opposite, since his estimate of 50 generations was off by four orders of magnitude, or about 11,000x.")
bw6=ex(BW,"Although, obviously, it doesn’t make sense, since as the usual critique correctly points out, the target phrase is known from the start, which is not the case in the evolutionary context.")
write('D9a-weasel-demonstrates-the-opposite','D9a','Dawkins\'s Weasel actually demonstrates the opposite of its purpose, since its 50-generation estimate is off by four orders of magnitude','day','D','D9',
 "[{type: depends-on, target: D9},{type: attacks, target: D}]",'false','illustrative','firsthand',
 'non-sequitur','the published Weasel is a truncation-selection algorithm; the 540,000 figure is for a different system (a population with constant s); a Weasel with Day\'s own 12 offspring and 5% mutation (exploratory run) completes in ~1,760 generations, not 540,000','n/a','Day\'s inference, not a source quote','contested','the "known target" objection (also Day\'s) cuts the other way',
 bw5+"\n\n"+bw6+f"\n\nSource: {WSs}, paras {para(BW,'So Dawkins’s little program')} and {para(BW,'Although, obviously')}.",
 "Claim: T_Weasel(Dawkins parameters) = 50 generations; T_real(population-genetic model, s = 0.001) = 540,000; hence Weasel is 'off' by 10^4. The comparison treats the Weasel's per-generation selection (pick the best of N offspring; truncation selection, effective advantage of the best offspring over the mean is large) as an advantage s that applies to every individual of a standing population of 10,000. Those are different systems; the Weasel 'estimate' of 50 is a runtime of an algorithm, not an estimate of anything biological, and Dawkins's own description of the algorithm is the first quotation in Day's post.",
 "- Stated: the 5% is a mutation probability, not a selection advantage (Day says so), and the relevant s is ~0.001.\n- Implicit: Weasel-as-published is meant to model a real species.",
 "- Against: (a) T(original Weasel, N = 100, P = 0.05) is itself ~50-80 generations (exploratory: mean 78, median 73, p5-p95 49-121; Day's 'about 50' is within a factor 1.6 and Dawkins's published runs vary), so the original estimate is right for the algorithm. (b) With Day's own 12 offspring, same algorithm: mean 1,763, median 1,302 (p5-p95 387-4,761), i.e. 1,300-1,800 generations, not 540,000. (c) Dembski (ally) agrees the Weasel's fitness function is chosen (D13).\n- In support: the Weasel's known target is a real disanalogy (Day, Dembski).\n- Weaknesses: the 'precise opposite' does not follow from the figures. Day makes the 'target known' objection himself two paragraphs earlier, i.e. he treats the Weasel as non-representative, then uses it to claim evolution's numbers are off.",
 LIT0+"| Dawkins 1986 (via approxion.com) | quoted in Day's post | secondhand |",
 "Written before the algorithm runs. Under Day: T(N=12, P=0.05, truncation) is much larger than 50 and scales as 540,000/50 = 10^4. Under the opposing model: T scales weakly with N (log N) and is 10^2-10^3. Result that would change a verdict: T(N=12, P=5%) >= 10^5 (not observed).",
 "Exploratory scratch run (python3 -I, numpy, seed 20261007/8, not committed): Weasel with 28 letters, alphabet 27, 400 replicates each: N = 100, P = 0.05: mean 78.3 (elitist and always-different-letter variants 78-79); N = 12, P = 0.05: mean 1,763 (300 replicates); N = 100, P = 0.01: mean 140. Not reproducing 50 (Day) is a 1.6x difference. Ranks of the claim: arithmetic of the 'four orders' holds only for the non-Weasel system.","Selection scheme (truncation vs proportional); offspring number; per-letter mutation probability P; alphabet; target-known flag.")

# D10 Axe
a1=ex('axe',"The prevalence of low-level function in four such experiments indicates that roughly one in 10(64) signature-consistent sequences forms a working domain. Combined with the estimated prevalence of plausible hydropathic patterns (for any fold) and of relevant folds for particular functions, this implies the overall prevalence of sequences performing a specific function by any domain-sized fold may be as low as 1 in 10(77)")
a2=ex('axe',"Using these simplifications, the difficulty of specifying a working beta-lactamase domain is assessed here.")
write('D10-axe-2004-1-in-1e77','D10','Axe: sequences performing a specific function by any domain-sized fold may be as rare as 1 in 10^77','literature','D','D',
 "[{type: supports, target: D}]",'false','not a premise of ROOT','firsthand',
 'pending','full text not available; the extrapolation from four experiments on one domain to 10^77 is not auditable from the abstract','accurate','abstract quote only','contested','Taylor 2001 and Keefe & Szostak 2001 give far higher frequencies for different functions; Axe\'s 10^64 is conditional on a hydropathic signature and low-level function',
 q(a1)+"\n\n"+q(a2)+"\n\nSource: Axe DD (2004) Estimating the prevalence of protein sequences adopting functional enzyme folds, J Mol Biol 341(5):1295-1315, abstract (`sources/raw/sources/abs/Axe2004.txt`; full text paywalled). Note: no Day text in the corpus cites Axe (searched 'Axe', 'lactamase', '10^77' in all Day blog and Zenodo texts); the 'Day cites 1e-77' entry in the pass-1 plan is unsupported by the harvested corpus.",
 "Prevalence f_fold-function = f_signature * f_pattern * f_fold: f_signature = 10^-64 (four experiments, 10-residue clusters, low-level function); overall f = 10^-77 'as low as'. Derived here: expected random hits among Eden's 10^52 molecules = 10^52 * 10^-77 = 10^-25; among the 10^55 of the working paper 10^-22. For comparison with D3: the fraction among all 20^150 sequences of a 150-residue chain is not stated in the abstract.",
 "- Stated: simplifications (hydropathic signature; coupled local problems); 'four such experiments'.\n- Implicit: independence of local problems when multiplying; low-level function counts as working; one fold (beta-lactamase) generalises; the sampled ten-residue clusters are representative.",
 "- Against: Taylor 2001 (D11) and Keefe & Szostak 2001 (D12) measure higher frequencies for other functions; the multiplication assumes independent local problems (epistasis could raise or lower f). Rosenhouse (D1a) says protein space geometry makes such counts naive.\n- In support: Day-side usage (D).\n- Weaknesses: Axe's number is a prevalence of function, not reachability: it estimates f, not whether selection can reach functional sequences from nearby ones.",
 LIT0+"| Axe 2004 abstract | quoted above | accurate |",
 "Written before any check. Under the claimant: further data on other folds give prevalence values at or below 10^-30. Under the opposing model: prevalence for any enzyme function is 10^-10 to 10^-25. Result that would change a verdict: a re-estimate with the full methods (needs the paper).",
 "Arithmetic only: 10^52 * 10^-77 = 10^-25. No simulation.","Functional fraction f; domain length; hydropathic-signature restriction.")

# D11 Taylor
t1=ex('taylor',"However, a 100-residue protein has 20100 (1.3 ⫻ 10130) possible sequences. Even a library with the mass of the Earth itself—5.98 ⫻ 1027 g—would comprise at most 3.3 ⫻ 1047 different sequences, or a miniscule fraction of such diversity.")
t2=ex('taylor',"we can estimate that if every position in the protein had been randomized, a library of ⬇1024 members would have been needed to obtain AroQ mutases.")
t3=ex('taylor',"The required library size can thus be calculated as follows: 4,500 (binary patterned H1) ⫻ 17,500 (binary patterned H2兾H3) ⫻ 206 (randomized active site residues) ⫻ 102 (fully randomized L1) ⫻ 102 (fully randomized L2) ⫻ 104 (templating effects) ⫽ 5 ⫻ 1023.")
t4=ex('taylor',"Our estimate of the low frequency of protein catalysts in sequence space indicates that it will not be possible to isolate enzymes from unbiased random libraries in a single step.")
t5=ex('taylor',"natural evolution, the design of new enzymes will require incremental strategies in which, for instance, a suitable scaffold is first generated")
write('D11-taylor-2001-1-in-5e23','D11','Taylor et al.: a fully randomized library of about 5 x 10^23 (approx. 10^24) members would be needed to obtain chorismate mutases','literature','D','D',
 "[{type: attacks, target: D10},{type: supports, target: D}]",'false','not a premise of ROOT','firsthand',
 'holds','4,500 x 17,500 x 6.4e7 x 1e2 x 1e2 x 1e4 = 5.04e23; reproduces','accurate','full text read (user-downloaded copy); quotes verified','contested','different protein, length and function than Axe; extrapolation with stated assumptions',
 q(t1)+"\n\n"+q(t2)+"\n\n"+q(t3)+"\n\n"+q(t4)+"\n\n"+q(t5)+"\n\nSource: Taylor SV, Walter KU, Kast P, Hilvert D (2001) Searching sequence space for protein catalysts, PNAS 98(18):10596-10601; p.10596 (first), p.10600 (second and third), p.10601 (fourth, fifth); full text `sources/raw/sources/manual/Taylor2001.pdf` (user-downloaded). Extraction: '⬇' is the glyph for 'approximately', '1024' = 10^24, '206' = 20^6, '102' = 10^2, '104' = 10^4, '20100' = 20^100.",
 "Required library size N_req = 4,500 * 17,500 * 20^6 * 10^2 * 10^2 * 10^4 = 5.0e23. Recomputed: 4500*17500 = 7.875e7; 20^6 = 6.4e7; 7.875e7*6.4e7 = 5.04e15; x1e8 = 5.04e23. Implied frequency of catalysts among fully randomized 100-residue sequences f ~ 1/N_req = 2e-24 (derived). The 100-residue space is 20^100 = 1.27e130 (Taylor 1.3e130, reproduced). Expected hits among Eden's 10^52 molecules at f = 2e-24: 2e28 (derived; different length and function from Eden's 250-mers, so not a like-for-like count).",
 "- Stated: single amino acid tolerated at six conserved active-site positions; 1-10% of turn segments active; templating factor 1e4 'could turn out to be larger'; selection to a modest activity.\n- Implicit: independence among the factors; AroQ-type chorismate mutase is representative; the binary-patterned modules are a good proxy for sequence families.",
 "- Against (for D): the frequency (2e-24) is vastly larger than Eden's implied 10^-273 and Axe's 10^-77, so at the 100-residue scale a large random library is not ruled out in principle; Taylor himself: libraries of this size 'far exceed what is currently accessible by experiment'.\n- In support (for D): the paper says 'extremely low incidence of enzymes in completely unbiased libraries' and that single-step random isolation is infeasible; it recommends 'incremental strategies' as in natural evolution (i.e. the topology horn of Eden's dichotomy).\n- Weaknesses: the paper neither measures connectivity nor evolutionary reachability, only frequency; Day-side uses of it as a 'counter-estimate' (in the task's labelling) must be read with that.",
 LIT0+"| Taylor 2001 p.10600 | quoted above | accurate |",
 "Written before the arithmetic. Under Taylor: N_req ~ 5e23. Result that would change the arithmetic verdict: product outside 4-6e23 (it is 5.04e23).",
 "`python3 -I -c \"print(4500*17500*20**6*1e2*1e2*1e4, 20**100)\"` -> 5.04e23, 1.27e130. Reconciles.","Functional frequency f; library/budget size; tolerated residues per position; templating factor.")

# D12 Keefe
k1=ex('keefe',"Starting from a library of 6 x 1012 proteins each containing 80 contiguous random amino acids, we selected functional proteins by enriching for those that bind to ATP. This selection yielded four new ATP-binding proteins that appear to be unrelated to each other or to anything found in the current databases of biological proteins. The frequency of occurrence of functional proteins in random-sequence libraries appears to be similar to that observed for equivalent RNA libraries.")
write('D12-keefe-szostak-2001-atp-binding','D12','Keefe & Szostak: four ATP-binding proteins from a library of 6 x 10^12 random 80-mers; frequency similar to RNA libraries','literature','D','D',
 "[{type: attacks, target: D}]",'false','not a premise of ROOT','firsthand',
 'n/a','','unverifiable','abstract only; the numerical frequency is not in the abstract and the full text (PMC4476321) was not read','contested','binding is not catalysis; function is weak ATP binding after enrichment',
 q(k1)+"\n\nSource: Keefe AD, Szostak JW (2001) Functional proteins from a random-sequence library, Nature 410:715-718, abstract (`sources/raw/sources/abs/KeefeSzostak2001.txt`; PubMed 11287961). Extraction: '1012' = 10^12.",
 "Library size M = 6e12; selected functional (ATP-binding) clones = 4. Derived lower bound (this file): if all four were present in the starting library, the frequency of ATP binding among random 80-mers is >= 4/6e12 = 6.7e-13. The paper's own estimate of the frequency is not in the corpus: unsourced here. 20^80 = 1.2e104 sequences in the full 80-residue space (derived).",
 "- Stated: in vitro selection by mRNA display; ATP binding; unrelated to known proteins.\n- Implicit: weak binding counts as function; selection recovers all binders present.",
 "- Against (for D): functional proteins from a random library at a frequency orders above the 10^-65 to 10^-77 scale.\n- In support (for D): binding is not catalysis; Taylor 2001 (D11) says the ATP-binding case is far easier than catalysis ('many orders of magnitude' smaller library).\n- Weaknesses: full text unread.",
 LIT0+"| Keefe & Szostak 2001 abstract | quoted above | accurate |",
 "No separate check. Action: read PMC4476321 for the stated frequency.","Arithmetic only: 4/6e12 = 6.7e-13.","Functional frequency f for binding vs catalysis.")

# D13 Dembski Whoppers
dw1=ex('whop',"Rosenhouse’s book is objectively bad. It purports to be a critique of mathematics as used by ID proponents and of my mathematical work in particular. Yet it betrays a lack of comprehension throughout. It makes a virtue of misrepresentation.")
dw2=ex('whop',"Take a simple example, one that Rosenhouse finds deeply convincing and emblematic for biological evolution, namely, Richard Dawkins’ famous METHINKS IT IS LIKE A WEASEL simulation (pp. 192–194 of Rosenhouse’s book).")
dw3=ex('whop',"The problem is not with the letter sequences, their randomization, or even the activity of a fitness function in guiding such an evolutionary process, but the very choice of fitness function.")
dd1=ex('b:2026-10-05-the-best-theyve-got-i',"Rosenhouse’s book is objectively bad. It purports to be a critique of mathematics as used by ID proponents and of my mathematical work in particular. Yet it betrays a lack of comprehension throughout. It makes a virtue of misrepresentation.")
write('D13-dembski-whoppers-reply-to-rosenhouse','D13','Dembski: Rosenhouse\'s book is objectively bad; the Weasel\'s fitness function is the source of its information','ally','D','D1',
 "[{type: attacks, target: D1},{type: supports, target: D2i}]",'false','not a premise of ROOT','firsthand',
 'pending','a reply to Rosenhouse\'s treatment of ID (specified complexity, NFL, information), not of the Wistar chapters','accurate','Day\'s Best I reproduces Dembski\'s paragraph (in italics) word for word and attributes it to "Dembke\'s summary"','contested','',
 dw1+"\n\nSource: Bill Dembski, [Jason Rosenhouse's Whoppers: More Guidance on Reading Rosenhouse](https://billdembski.com/intelligent-design/jason-rosenhouses-whoppers/), 2022-08-26, section 3 'Appealing to the Unwashed Middle' (retrieved 2026-10-07 during R2; sha256 of saved HTML 42aed3b9d29993a5a232c07d19caca8f40cd8068cf4d010b172fbeecbd8a4236; not yet in bib-critics.md).\n\n"+dw2+"\n\n"+dw3+"\n\nSource: same, section 5 'The Environment as a Source of Information'.\n\nDay's use: "+q(dd1)+f"\n\nSource: The Best They've Got I, 2026-10-05, para {para('b:2026-10-05-the-best-theyve-got-i','Rosenhouse’s book is objectively bad')} (the paragraph is in italics in the HTML, with the preceding sentence linking to Dembski's post; Day then writes 'Dembke’s summary' and 'I'm not in a position to have an opinion one way or the other').",
 "No formal content. Two points: (1) the book is bad (assertion); (2) in the Weasel, the choice of the target-based fitness function is the information source (conservation-of-information argument; technical work by Dembski and colleagues, not retrieved).",
 "- Stated: Weasel's fitness function is chosen by the environment/designer; 'most fitness functions would evolve toward random sequences'.\n- Implicit: the choice of fitness function in biology is analogous to choosing a target.",
 "- Against: Rosenhouse's own 2022 reply to Dembski (referred to in the post) and his Cambridge blog essay (RO-3, `rosenhouse-cbblog.html` in the corpus) were not examined here for Wistar or Weasel content. No Rosenhouse reply to Day found.\n- In support: D2i (Day's designed-fitness-function argument) is the same point.\n- Weaknesses: Dembski does not discuss Wistar, Eden or sequence space in this post (search: 'Wistar', 'Eden', 'protein', 'sequence space' have no matches), so D13 supports D2i and not D. Day says he is 'not familiar with their work'. Dembski's 18,000-word June 2022 review (linked in the post) was not retrieved.",
 LIT0+"| Rosenhouse 2022 pp.192-194, p.215 | quoted by Dembski | secondhand |",
 "No separate check.","None.","Fitness-function provenance (D2i).")

# D14 Davis/Eden 10^36
r1=ex('qc',"it would take about 10 to the 36th power of genetic transmissions to do that.")
write('D14-davis-relays-eden-1e36-genetic-transfers','D14','Rebekah Davis (relaying Eden): about 10^36 genetic transfers would be needed to form one ordered pair of genes','ally','D','D',
 "[{type: supports, target: D}]",'false','not a premise of ROOT','secondhand',
 'holds','1/(1e-15 x 1e-21) = 1e36; population needed 1e36/(1e12 x 1e-6) = 1e30; reproduces from Eden\'s printed inputs','accurate','Eden p.9 prints "1036 genetic transfers" (= 10^36)','contested','Eden calls it a "very rough estimate" built on unsourced probabilities; a different mechanism (transposition of operon genes) from point-mutation evolution',
 q(r1)+"\n\nSource: Rebekah Davis (Examining Origins), [Can Evolutionists Finally Face the Math? Challenge Issued!](https://www.youtube.com/watch?v=jDxFtCOGZ3A), 2026-09-23, t=00:12:05 (quotes-critics RD-03). `secondhand`: she relays Eden.\n\nPrimary text:\n\n"+q(ex('W',"Then to achieve a single ordered pair of genes on these assumptions would require something like 1036 genetic transfers."))+"\n\nSource: Eden, Wistar p.9 ('1036' = 10^36).",
 "Eden's chain (p.9): a transposition of chromosomal material 'should occur in an unselected environment with a frequency of 10^-15 for each sequential pair of genetic transfers'; a specific transposition has probability 10^-21 (uniform chain segmenting); so a single ordered gene pair needs 1/(10^-15 * 10^-21) = 10^36 genetic transfers. E. coli: 10^12 two-hour periods since life began, 10^-6 of the population mating at any instant, so the required population is 10^36/(10^12 * 10^-6) = 10^30 cells (Eden: 'about 10^13 tons or a layer ... two centimeters thick'). All reproduce arithmetically.",
 "- Stated (Eden): 'a very rough estimate'; unselected environment; uniform chain segmenting.\n- Implicit: no selection for intermediate rearrangements; transposition frequency 10^-15 and 10^-21 are unsourced.",
 "- Against: Eden's own caveat ('a discovery of a new transposition mechanism can make such speculations an exercise in futility', p.9); selection on operon organisation, recombination, horizontal transfer.\n- In support: Davis (relay); Day (D).\n- Weaknesses: Davis says she has not read the book (RD-01) and relays Duffy's presentation; the claim is Eden's and concerns bacterial operon organisation, not human-chimpanzee divergence.",
 LIT0+"| Wistar p.9 (Eden) | quoted above | accurate |",
 "Written before the arithmetic. Under Eden: 10^36 and 10^30. Standard arithmetic reproduces both. Result that would change a verdict: none; the input probabilities are what is uncertain.",
 "`python3 -I -c \"print(1/(1e-15*1e-21), 1e36/(1e12*1e-6))\"` -> 1e36, 1e30. Reconciles.","Transposition/rearrangement frequency; population size; number of mating periods.")
