import sys; sys.path.insert(0,os.environ.get("EVO_WORK","work")+"")
from gen_lib import *
BI='b:2026-10-05-the-best-theyve-got-i'
q1=ex(BI,"my own demonstration of the mathematical impossibility of evolution by natural selection","and every other imagined mechanism")
p1=para(BI,"my own demonstration of the mathematical impossibility")
q2=ex('mitt3',"The post-Darwinian polythesis fails comprehensively under the most favorable experimental conditions ever constructed.")
q3=ex('mitt3',"Three independent lines of genomic evidence confirm that no supermutational phase occurred on the human lineage.")
q4=ex('z:18452504',"Alternative mechanisms—incomplete lineage sorting, soft sweeps, standing variation, hitchhiking—do not rescue the model.","cannot account for them in the available time.")
q5=ex('b:2024-04-25-every-critique-is-correct',"evolution by natural selection not only never happened, but was never even possible")
q6=ex('mitt3',"Defenders of the theory have constructed what we term the post-Darwinian polythesis: a shifting constellation of supplementary mechanisms","but never tested collectively.")
q7=ex('mitt3',"Each mechanism was invoked to answer a specific objection. None was invoked alongside the others.","No efforts were made to show how these various mechanisms were sufficient to supply the observed shortfall.")
q8=ex('b:2026-09-30-math-teacher-cant-math',"So is any and every evolutionary mechanism, with the exception of three minor ones.")
print(q1);print(q4)
write('ROOT-no-mechanism-suffices','ROOT','No evolutionary mechanism can produce the observed human-chimpanzee divergence in the available time','day','ROOT','null',
 "[{type: depends-on, target: A},{type: depends-on, target: B},{type: depends-on, target: C},{type: depends-on, target: D},{type: depends-on, target: E},{type: depends-on, target: F},{type: depends-on, target: G},{type: depends-on, target: H},{type: depends-on, target: ROOT-M}]",
 'true','this is the root claim; it fails if its universal quantifier fails for any mechanism (see ROOT-M)','firsthand',
 'pending','branches A-H and ROOT-M must be resolved first','n/a','aggregate claim; fidelity is audited per branch','pending','depends on A-H',
 q1+f"\n\nSource: [The Best They've Got I](https://voxday.net/2026/10/05/the-best-theyve-got-i/), 2026-10-05, voxday.net, para {p1} of extracted text. Day's own summary of his scope: eight named mechanism classes plus an unnamed remainder.\n\n"
 +q4+"\n\nSource: [The Universal Failure of Fixation: MITTENS Applied Across the Tree of Life](https://zenodo.org/records/18452504) (Z18452504), 2026-02-02 (v1), Sections 4.3-4.4 / Conclusion, extracted-text lines "+str(lineno('z:18452504',"do not rescue the model."))+" and "+str(lineno('z:18452504',"cannot account for them in the available time."))+"\n\n"
 +q2+"\n\nSource: [MITTENS 3.0: The Mathematical Impossibility of the Post-Darwinian Polythesis](https://zenodo.org/records/23003785) (Z23003785), published 2026-09-28, record modified 2026-10-04 (content drift not yet diffed, see ledgers/versions.md), Abstract, p.1.\n\n"
 +q5+"\n\nSource: [Every Critique is Correct](https://voxday.net/2024/04/25/every-critique-is-correct/), 2024-04-25, para "+str(para('b:2024-04-25-every-critique-is-correct',"never happened, but was never even possible"))+" (earlier, stronger-worded form: 'never happened' as well as 'never possible').",
 """ROOT as an implication:
- For every mechanism M in a set S = {natural selection (hard and soft sweeps), parallel fixation, neutral drift, neutral sweeps, hitchhiking, ILS, biased gene conversion, relictation-type bottleneck drift, recombination, hypermutation, ... and "every other imagined mechanism"}:
  `F_M(T) < F_req`, where F_M(T) is the number of lineage-specific fixations (or equivalent) mechanism M can deliver in T generations and F_req is the number required by the observed divergence.
- Day's operational form (MITTENS 3.0): `F_max = T_gen / G_f` with `T_gen = 252,000` (parameters.yaml `generations_available.day_2026`), `F_req = 2.05e8` (`required_fixations.day_2026`), `G_f = 1,322` (`ltee.gens_per_fixation.day_mittens3_nonmutator`); shortfall `F_req / F_max = 2.05e8 / (252000/1322) = 1.075e6` (derived, reproduces the stated 1,075,000 to 3 sig figs: 2.05e8/190.62 = 1.0754e6).
- The universal quantifier ("every other imagined mechanism") is the part that needs an argument per mechanism; see ROOT-M.""",
 """- Stated: (i) the divergence is the 205M (2026) or 20M (2025) fixations; (ii) T = 252,000 or 202,500 or 146,250 generations (versions drift, see ledgers/versions.md); (iii) the LTEE throughput of 1,322 gens/fixation is an upper bound on any mechanism ("the fastest fixation rate ever observed in any organism under any conditions"); (iv) the LTEE includes "almost every way evolution can theoretically take place" (blog 2026-09-30).
- Implicit: the fixation of an allele is the unit of work (not haplotype blocks, not polymorphism sorting); a bacterial asexual aggregate bounds a sexual vertebrate; ancestral Ne and the starting pipeline state do not matter; dates of divergence are independent of the neutral-clock mechanism being tested.
- Implicit: absence of a computed argument for a mechanism is treated by Day as non-rescue (burden of the alternative; Z18452504: "they gesture at alternative mechanisms without demonstrating that any alternative can accomplish the required work").""",
 """- Against (as of R2): No critic in the corpus addresses ROOT as a whole; critics attack the supporting branches (A5 scaling, B1/B3/B5 neutral theory, F1 latency vs throughput, G serial vs parallel, C1 ascertainment). See hierarchy.yaml for the edges. A5, B3, B7 and A3x have verified fidelity problems on the Day side (ledgers/fidelity.md); the ally Hossjer re-derives a ~2x (not 10^6x) gap after scaling (HO-01, HO-02, claim ROOT-H).
- In support: allies endorse the conclusion (ROOT-K, ROOT-T, ROOT-H, ROOT-DE) but contribute no independent calculation, with the partial exception of Hossjer's scaling.
- Weaknesses in the responses: "no critic addressed ROOT as a whole" is a statement about our corpus (23 opponent profiles); the Gutsick Gibbon / Hancock 3.5 h response (2026-10-03) was transcribed but only parts mapped. Day's characterisation of the critics' answer as "qualitative" ("The response ... was not a quantitative rebuttal", MITTENS 3.0 section 1) is contradicted by at least KITTENS, Hancock, Mansfield and Nesslig20, who give numbers (balance ledger); equally, several critics' numbers are off (balance ledger).""",
 """| Cited work | What it actually says | Fidelity |
|---|---|---|
| See branch files A-H | ROOT cites no literature of its own | n/a |
| Kimura 1962; Kimura & Ohta 1969; Zeng 2021; Yoo 2025; Langergraber 2012 (inputs to A, B) | see ledgers/fidelity.md | misread/partial/not-found (as recorded there) |""",
 """Written before any ROOT-level check (ROOT has no check of its own; it is the conjunction of A-H plus ROOT-M).
- Under the claimant's model: every branch check with defensible parameters returns a shortfall of at least ~10^2 for every mechanism in ROOT-M; no mechanism in ROOT-M has an unaddressed quantitative route.
- Under the opposing model: at least one of (A5 scaling, B1/B3 equilibrium state, F1/G pipelining, C1 ascertainment) removes most of the shortfall, so that the required fixations are within ~1-2 orders of magnitude of achievable; the mechanisms are not individually excluded.
- Result that would change a verdict: ROOT is **refuted** if any single mechanism class in ROOT-M is shown (by forward simulation under parameters.yaml values and Day's own T, with scaling validated) to deliver the required F_req within T; ROOT is **supported** only if all of A (after scaling), B and G survive the R4 checks and every row of ROOT-M carries a computed exclusion. Rows tagged "asserted, not computed" cannot count as support.""",
 "No ROOT-level script. Component checks: B0, B0.4, B1, B1b, B2a, B3, F1 (done); A, C, E, G, H (queued); Branch D (this module): arithmetic only so far, simulations specified in D, D2h, D9, D4. Arithmetic here: `python3 -I -c \"print(2.05e8/(252000/1322))\"` -> 1.0754e6 (reconciles with the stated 1,075,000).",
 "T_gen (generations available), F_req (required fixations: SNV-only vs bp), G_f or a mechanistic fixation process, mechanism switches (selection, drift, linkage/hitchhiking, recombination, bottleneck family replacement, mutation supply), population structure, demographic history, scaling parameters.")

write('ROOT-excluded-mechanisms','ROOT-M','Which named mechanisms Day says are excluded, and whether the corpus holds a quantitative argument for each','day','ROOT','ROOT',
 "[{type: depends-on, target: ROOT},{type: supports, target: ROOT}]",
 'true','ROOT is a universal claim over mechanisms; each row without a computed exclusion is a gap in the quantifier','firsthand',
 'pending','per-row verdicts live in the branch claims','n/a','catalogue, not a single assertion','pending','depends on the rows below',
 q1+f"\n\nSource: [The Best They've Got I](https://voxday.net/2026/10/05/the-best-theyve-got-i/), 2026-10-05, para {p1}.\n\n"+q6+f"\n\nSource: MITTENS 3.0 (Z23003785), Abstract, p.1.\n\n"+q7+"\n\nSource: MITTENS 3.0 (Z23003785), Section 1 'The Post-Darwinian Polythesis', extracted-text line "+str(lineno('mitt3',"None was invoked alongside the others."))+".\n\n"+q8+"\n\nSource: [Math Teacher Can't Math](https://voxday.net/2026/09/30/math-teacher-cant-math/), 2026-09-30, para "+str(para('b:2026-09-30-math-teacher-cant-math',"with the exception of three minor ones"))+"; the three are named later in the post as sexual recombination, incomplete lineage sorting and horizontal gene transfer.",
 """Table of the mechanisms Day names as excluded. "Computed" means the corpus contains an equation, a worked number or a dataset-based count that targets that mechanism (whether or not it is right). "Asserted, not computed" means the only support found is a sentence of assertion. Searches were run over every Day blog post and Zenodo text in `sources/raw/day/` (keywords listed per row); a negative result means "not found in the harvested corpus" and excludes the paywalled books (Probability Zero 1st/2nd ed., The Frozen Gene, Hardcoded) which were not accessed.

| # | Mechanism (Day's term) | Where Day excludes it (key, locator) | Quantitative argument in corpus? | Hierarchy / claim ID | Notes |
|---|---|---|---|---|---|
| 1 | Natural selection, hard sweeps | MITTENS (Z18165980; Z23003785) | **Computed**: F_max = T_gen/G_f, G_f from LTEE | A, A1-A5, F, H | Inputs and scaling contested (A3x, A5, B7 fidelity findings). |
| 2 | Parallel fixation | Bernoulli paper Z18167588; MITTENS 3.0 | **Computed** (Bernoulli product; ~230 simultaneous-sweep cap "working backward from the constraint"); LTEE G_f is an empirical aggregate that includes parallelism | G, G1-G3 | The ~230 cap is stated as derived from the constraint, not independently (versions ledger). |
| 3 | Soft sweeps / standing variation | Z18452504 section 4.3 | **Computed**: t ~ (2/s)ln(1/p0); ratio ln(20)/ln(10,000) = 0.325 (recomputed: ln 20 = 2.996, ln 10^4 = 9.210, ratio 0.3253) -> "factor of ~3" | G / A | Deterministic approximation; Wistar-era and modern sweep-time results not compared (B0.4 found (2/s)ln(2N) overshoots the conditional time by ~2.3x at Day's parameters). |
| 4 | Neutral drift | Z22129121 Hard Limits; Z18441321 section 3.2; blog 2026-09-30 'Math Teacher Can't Math'; Z18429937 | **Computed**: X = (Vk+2)G/16 ceiling; 4Ne latency; 'Drift Deathmarch' load argument (75% harmful mutations; collapse in 9 generations) | B, B1-B3, B2, F, F1 | Latency vs throughput (F1) and N vs Ne (B3/B7) disputes apply. Load argument: assumed share of harmful mutations and damage per mutation are unsourced here (to extract). |
| 5 | Neutral sweeps | Named only in Best They've Got I (para @P5@) | **Asserted, not computed**: no occurrence of 'neutral sweep' anywhere else in the Day corpus | ROOT-M | The term may refer to hitchhiking (row 6) or to drift (row 4); no separate argument found. |
| 6 | Hitchhiking / linked neutral fixations | Z18452504 section 4.3 ('Linkage and Hitchhiking'); MITTENS 3.0 section on hitchhikers | **Computed**: block size r/s (r=1e-8, s=0.01 -> 1e-6/bp -> 1 Mb; recomputed); 3,200-32,000 blocks; ~20.5 neutral hitchhikers per 50,000 gens in the LTEE counted inside the 56.0 fixations | E1, A2 | Static-block calculation; the LTEE count is an empirical subset of the fixations. |
| 7 | Incomplete lineage sorting (ILS) | Z18452504 section 4.3; Z18441321 section 3.3; blog 2026-04-28 'Less Than Zero' ('four independent reasons' in the first edition, not retrieved) | **Computed**: 4*Ne*mu*L = 4*1e5*1.5e-8*3.2e9 = 1.92e7 (recomputed 1.92e7), x 0.15 mean reciprocal-sorting probability = 2.88e6 ('~2.9 million') | B / C (new ILS claim to extract) | Ne 50k-100k used, versus 132k-198k in Yoo 2025 (parameters.yaml). 4*Ne*mu*L is theta*L (expected pairwise-difference scale), not the number of segregating sites; whether this is the right ceiling is for the branch-B owner. The 0.15 average is an assumption. Yoo's 39.5% ILS (blog 2026-04-28) is not reconciled with the 2.9M ceiling in any retrieved Day text. |
| 8 | Biased gene conversion (gBGC) | Named only in Best They've Got I (para @P8@) | **Asserted, not computed**: searched 'gene conversion', 'gBGC', 'BGC' in all Day blog and Zenodo texts; only that sentence | ROOT-M | No argument, no equation, no citation. |
| 9 | Hypermutation / supermutation | MITTENS 3.0 abstract and sections; Z23020792; Z23034852 | **Computed/empirical**: mutator populations achieve 8.5-17x, not 100x, throughput; 'three independent lines of genomic evidence' that no supermutational phase occurred | E | Empirical LTEE statistic; the three 'lines of evidence' are in Z23003785 (to be extracted under E). |
| 10 | Epistasis, clonal interference, compensatory mutation, frequency-dependent selection, eco-evolutionary dynamics | MITTENS 3.0 section 1 and LTEE argument; blog 2026-10-01 'They Never Stop Lying' | **Bounded empirically, not computed individually**: all operate in the LTEE, so the aggregate G_f is said to include them; Day states of the defenders' mechanisms: 'No calculations of their effects, individual or cumulative, were ever attempted or provided.' | A2, G1 | Day does not compute their separate effects either; the argument is that the aggregate is a ceiling. LTEE-to-vertebrate transfer is A5. |
| 11 | Sexual recombination | blog 2026-09-30 ('only recombination could even theoretically speed things up, and the reproductive constraints ... more than compensate'); Z18637297 transmission-channel-capacity survey | **Partly computed**: Z18637297 surveys mu/r across six taxa; the net-effect sentence in the blog is **asserted, not computed** | B / G (new) | Z18637297 argues recombination is saturated in mammals (mu/r ~ 1-1.5); not extracted yet. |
| 12 | Horizontal gene transfer | blog 2026-09-30 ('populations are maintained in isolation'; 'Of those three, only recombination could even theoretically speed things up') | **Asserted, not computed** | ROOT-M | For a human-chimpanzee comparison HGT is not claimed by critics in the corpus; row kept for completeness. |
| 13 | Hybridization / introgression / gene flow | blog 2026-01-07 ('Hybridization and introgression ... actively work against the fixation of lineage-specific mutations') | **Asserted, not computed** | ROOT-M | Day treats it as opposing fixation, not as a source of divergence. |
| 14 | Gene duplication, whole-genome duplication, de novo genes, exon shuffling, regulatory evolution | blog 2026-05-13 (WGD 'totally irrelevant to the throughput argument, for three reasons'); blog 2026-03-04 (critic's list) | **Asserted/argued in prose, not computed** for the human lineage | A3x (event vs bp) | The structural-variant bp-vs-event dispute (A3x) is the quantitative handle. |
| 15 | Punctuated equilibrium / founder events | Z23020792; Z23034852; blog 2026-09-29 | **Computed** (hazard ~2.3% per founder event; strong-s zones, per hierarchy.yaml; not re-verified here) | E | Not extracted here. |
| 16 | Non-random (biased) mutation | blog 2026-01-19 Q&A | Day **adds it as a further penalty**: 209,500 -> 157,125 effective generations (ratio 0.750) | A | Direction: Day treats non-random mutation as hurting evolution, i.e. a constraint, not a mechanism. |
| 17 | Cost of selection (Haldane) | Z18168236, Z19984826 | **Computed** but partially retracted 2026-05-07 (Term 3) | H, H1 | See versions ledger. |
| 18 | Relictation (bottleneck family replacement) | Z23188201, 2026-10-06 | Day **does not exclude it**: presented as a 'third evolutionary mechanism' alongside selection and drift | ROOT-M | Its effect on divergence timing relative to ROOT is not computed in the retrieved text; the abstract says fixation operates on haplotype blocks. This is Day-side material that sits awkwardly with a universal exclusion; flagged, not judged. |
| 19 | 'Every other imagined mechanism' | Best They've Got I | **Open**: unbounded set; cannot be computed | ROOT-M | A universal over unnamed mechanisms is untestable until each is named (Z18452504 'burden of the alternative' places the burden on critics). |
| - | Intelligent Genetic Manipulation (IGM) | blog 2024-05-06 | **Not excluded** by Day: 'not mathematically ruled out by MITTENS' | ROOT-M | ROOT is a claim about unguided mechanisms; Day's alternative is outside it. |

Totals (rows 1-18 named mechanisms): computed or empirically bounded: 1, 2, 3, 4, 6, 7, 9, 15, 17 (9 rows) plus partial: 10, 11, 16; **asserted, not computed: 5, 8, 12, 13, 14** (5 rows); Day-accepted: 18.""".replace("@P5@",str(para(BI,"neutral sweeps"))).replace("@P8@",str(para(BI,"biased gene conversion"))),
 """- Stated: each mechanism either fails the same rate bound (LTEE G_f) or is separately bounded.
- Implicit: a mechanism with no named quantitative bound is covered by the aggregate LTEE bound (rows 10-12) or by the burden of the alternative (row 19). Both are positions on who must compute, not computations.""",
 """- Against: no critic engages the table as such. For rows 3-4 and 7 critics argue ILS and drift differently (Mansfield B5/B6; McCarthy; Yoo 2025's 39.5% ILS figure quoted by Day), but the corpus has no critic calculation of ILS.
- In support: Day points to the LTEE as a single experiment in which rows 1, 2, 4, 6, 9, 10 all operate. This is a real strength of the design and equally a limit: the LTEE is asexual, so rows 7, 11, 12 are outside it (Day says so himself: blog 2026-09-30).
- Weaknesses: counts of rows are by keyword search over harvested text; paywalled books may contain computations for the five 'asserted' rows (esp. the first-edition 'bestiary of failed defenses' with 'four independent reasons' for ILS, which Day says exists in print).""",
 "| Cited work | What it actually says | Fidelity |\n|---|---|---|\n| Yoo 2025 | ILS 39.5% of the autosomal genome (as cited by Day, blog 2026-04-28) | not verified in this file |\n| Takahata 1993; Chen & Li 2001 (Ne 50-100k, cited in Z18452504) | not retrieved | unverified |\n| Yoo 2025 ancestral Ne | 132k-198k (parameters.yaml) | verified (ledger) |",
 """Written before any per-row check.
- Under the claimant's model: every 'computed' row's check returns a shortfall > 10^2 once scaling is validated; the 'asserted' rows contribute negligible divergence in T (gBGC, HGT and introgression cannot supply 10^7-10^8 differences).
- Under the opposing model: ILS plus neutral substitution along a full pipeline supplies most of the observed differences with no shortfall (B6), because the ancestral Ne was 132k-198k and the ancestral polymorphism budget is far above 1.9e7; hitchhiking and recombination change what counts as an independent fixation.
- Result that would change a verdict: a forward simulation under Day's own T and a validated scaling in which any single row delivers >= F_req changes ROOT; a computed bound for rows 5, 8, 12, 13, 14 would remove the 'asserted' tag.""",
 "Arithmetic recomputed in this file (python3 -I): 4*1e5*1.5e-8*3.2e9 = 1.92e7; 1.92e7*0.15 = 2.88e6; ln(20)/ln(1e4) = 0.3253; 1e-8/0.01 = 1e-6 per bp (1.0 Mb); 157125/209500 = 0.7500. All reproduce Day's stated values. No simulation run.",
 "Mechanism switches (sweep/hitchhike/drift/ILS/gBGC/recombination), ancestral Ne and polymorphism budget (4*Ne*mu*L vs S), reciprocal-sorting probability distribution, recombination rate r and block size, per-mechanism fixation counts reported separately, event-vs-bp unit.")
