from gen import *
Z3='[MITTENS 3.0, Zenodo 23003785](https://zenodo.org/records/23003785) (key Z23003785), 2026-09-28 (modified 2026-10-04)'
ZB='[The Bernoulli Barrier, Zenodo 18167588](https://zenodo.org/records/18167588) (key Z18167588), pub. 2026-01-04 (modified 2026-01-07)'
Z25='[MITTENS 2025, Zenodo 18165980](https://zenodo.org/records/18165980) (key Z18165980), pub. 2025-12-28 (modified 2026-01-06)'
EDU='[The Education of a Population Geneticist](https://voxday.net/2026/10/01/the-education-of-a-population-geneticist/) (key B2026-10-01), blog, 2026-10-01'
NSL='[They Never Stop Lying](https://voxday.net/2026/10/01/they-never-stop-lying/) (key B2026-10-01b), blog, 2026-10-01'
SNK='[Snikker Snak](https://voxday.net/2026/10/01/snikker-snak/) (key B2026-10-01-snikker-snak), blog, 2026-10-01'

claim('A5e','human-derived-rate-27600','A rate derived from human parameters alone gives one fixation per 27,600 effective generations, so 8 are achievable','day','A','A5',
 [('attacks','A5b'),('depends-on','A4')],False,'firsthand','checked',('arithmetic-error','unverifiable','pending'),
 q('yields approximately one fixation per 27,600 effective generations (Day and Athos 2025, Appendix D). Applied to 252,000 generations provides 8 achievable fixations against the 205 million required.',Z3+', p.15 (s8.6). The derivation is in the book appendix, not harvested.'),
 '''G_f(human) = 27,600 effective generations per fixation; achievable = 252,000 / 27,600.
`derived:` (python3 -I) 252,000/27,600 = 9.13, not 8 (8 x 27,600 = 220,800, which would correspond to t_div = 5.5 My at 25 y, 220,000 generations). A 12% discrepancy in the paper\'s own sentence; immaterial to the 205M shortfall, but the figure does not reconcile. For scale: Day\'s Q&A formula (2/s) ln(2Ne) with s = 0.001, Ne = 10,000 gives 19,807 (Q44-Q46); 27,600/19,807 = 1.39; the reason for the ratio is not stated in the paper.
Method flag: the text says the rate was "calculated … using Kimura\'s fixation time formula and the Bio-Cycle correction". If a fixation time (latency) is inverted into a rate, the calculation takes the serial form; the repo check F1 shows latency and throughput differ (see Check).''',
 '- Stated: human parameters alone; Kimura fixation time; Bio-Cycle correction for overlapping generations.\n- Implicit: a fixation time t_fix sets the rate 1/t_fix (serial form); s = 0.001 beneficial (Zeng 2021 coefficient is for negative selection: ledger misread).',
 '''- Against: KITTENS (A5b §11) says "§8.2 and Appendix D revert to the interval form for drift". Mansfield (MF-04): "The time it takes for one allele to get fixed is not important, it is the time BETWEEN successive fixations that is important." (F branch).
- In support: none beyond Day.
- Weaknesses in the responses: Appendix D itself was not retrieved by either side in the corpus; the critics\' characterization is of the 3.0 text, not the appendix.''',
 LITH+'''| Zeng et al. 2021 | "predicted mean selection coefficient of ~0.001" for negative selection on trait variants | verified-misread when used as a beneficial s |
| Kimura & Ohta 1969 | "takes about 4Ne generations until fixation"; no recombination discussed | t_fix accurate; recombination attribution misread |''',
 'Linked result: F1 (research/checks/RESULTS.md): steady-state rate = 2N·U_b·u(s) independent of latency; simulated 0.3972 ± 0.0018 vs predicted 0.3960; t_fix = 847 generations but G_f = 3 generations; in-transit count ≈ 336 (computed, not measured). Caveat in RESULTS.md: parameters unrealistic (0.4 substitutions per generation, no interference or cost), so pipelining is shown possible, not feasible at realistic parameters. B0.4 result: (2/s)ln(2N) overshoots the diffusion mean fixation time by 1.6–2.2x (at Day\'s N=1e4, s=0.001: 19,807 vs 8,480).',
 'Link: `research/checks/RESULTS.md` F1, B0.4. Arithmetic audit (python3 -I, scratch). Review: pending.', '- Selectable rate model: aggregate throughput vs 1/t_fix; Bio-Cycle toggle.')

claim('A5f','clonal-lineage-vs-recombining','The LTEE is nonrecombining, one clone, one environment; sex and population-size variability change the fixation rate in mammals','critic','A','A5',
 [('attacks','A2e')],False,'firsthand','extracted',('pending','partial','contested'),
 q('It follows largely nonrecombining bacteria descended from one clone, repeatedly transferred into the same glucose-limited environment.',
   '[r/DebateEvolution, Dumb-and-Dumber](https://www.reddit.com/r/DebateEvolution/comments/1wss2wj/), 2026-09-28 (RE-07).')+'\n'+
 q('Fixation rate in single cell organism is not equal to fixation rate in mammal. And there is two reasons for it. One is sexual reproduction. The second is variability of population size.',
   '[Whopping the floor](https://voxday.net/2019/02/11/whopping-the-floor/), 2019-02-11, ¶4 (GA-01). Gariépy\'s words as transcribed and posted by Day: secondhand.'),
 '''Claim: rate_human(recombining) ≠ rate_LTEE(asexual), direction unspecified by the quotes. The KITTENS text (A5b) argues the LTEE is where "interference is worst", so the LTEE rate is a lower bound for recombining genomes. Day\'s side (blog 2026-10-01): "recombination is a double-edged sword that also breaks linkage, imposes segregation costs, and exposes deleterious recessives".''',
 '- Stated: the asexual setting differs from a sexual one; the direction of the effect is argued by KITTENS (interference reduces rate in clonal populations) and by Day (recombination hurts).\n- Implicit: effects can be summed into a single factor.',
 '''- Against (Day): [They Never Stop Lying](https://voxday.net/2026/10/01/they-never-stop-lying/) ¶6: "he also assumes that recombination will help speed up the fixation rate, which it won\'t"; Bowers reply (2026-03-04, point 3): "Recombination reshuffles existing variation; it does not accelerate the rate at which any individual allele increases in frequency. Kimura and Ohta (1969) established that expected time to fixation does not depend on recombination rate." The Bernoulli paper (Z18167588 s7.3) repeats this, citing Hartfield and Bataillon (2020). Z18165980 lists "recombination requirements" and Hill-Robertson interference as mechanisms that reduce fixation probabilities under concurrent fixation.
- In support: Good et al. 2017: the separation of timescales between inter- and intra-clade fixations "cannot be explained by clonal interference" (so clonal interference does not explain at least that observation); KITTENS §8: "in a 3-gigabase genome with several crossovers per meiosis, selected sweeps at distant loci proceed nearly independently, whereas the LTEE genome is one linkage group."
- Weaknesses in the responses: Kimura & Ohta 1969 is a single-locus model and the word "recombination" does not occur in it (ledger: misread/misattribution), so the cited authority does not address the point; the Hartfield and Bataillon citation was not retrieved. KITTENS gives no simulation. The Day-side statement that recombination is a cost does not quantify it, and the Z18167588 paper elsewhere (s7.10) distinguishes the Bernoulli Barrier from Hill-Robertson interference.''',
 LITH+'''| Kimura & Ohta 1969 | "recombination" appears 0 times; a single-locus model | verified-misread (misattribution) |
| Good et al. 2017 | "This striking separation of timescales between inter- and intra-clade fixations cannot be explained by clonal interference" | verified; limited scope |''',
 'No check run. Proposed A-sim arm: recombination on/off at fixed supply. Prediction (critics): rate per generation higher with free recombination. Prediction (Day): no gain, or net loss, from segregation cost. Result that would change a verdict: a monotone dependence of fixation rate on recombination rate in simulation at human-scale supply.',
 'Script: none. Review: pending.', '- Recombination rate (0 to free), mating system toggle, population-size variability.')
